package composeproject

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/aphronio/dorf/internal/deployment"
	"github.com/aphronio/dorf/internal/release"
)

const (
	testPostgresImageID  = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	testControlReaderKey = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
)

func testComposeImage() release.ComposeImage {
	return release.ComposeImage{
		Version: "0.5.2", Reference: "dorf-local:0.5.2",
		ImageID: "sha256:" + strings.Repeat("e", 64), BinarySHA256: strings.Repeat("b", 64),
	}
}

func TestRenderProducesExactVersionedProject(t *testing.T) {
	sources := t.TempDir()

	configDir := filepath.Join(sources, "config")
	dataDir := filepath.Join(sources, "data")
	stateDir := filepath.Join(sources, "state")
	project, err := Render(Spec{
		Image:     testComposeImage(),
		UID:       1000,
		GID:       1001,
		ConfigDir: configDir,
		DataDir:   dataDir,
		StateDir:  stateDir,
		Deployment: deployment.Config{
			ControlReaderKey: testControlReaderKey,
			Database: deployment.Database{
				Host: "127.0.0.1", Port: 54329, Name: "dorf", User: "dorf", Password: "database-secret",
				Image: "postgres:17.10-bookworm", ImageID: testPostgresImageID,
			},
			E2B: &deployment.E2B{APIKey: "e2b-secret"},
		},
	})
	if err != nil {
		t.Fatal(err)
	}

	if project.Image != testComposeImage() {
		t.Fatalf("image=%+v", project.Image)
	}
	if project.Runtime.ProjectVersion != ProjectVersion ||
		project.Runtime.UID != 1000 || project.Runtime.GID != 1001 ||
		project.Runtime.ConfigDir != configDir || project.Runtime.DataDir != dataDir || project.Runtime.StateDir != stateDir ||
		project.Runtime.DeploymentPath != filepath.Join(configDir, "deployment.json") ||
		project.Runtime.Deployment.Database.Password != "database-secret" || project.Runtime.Deployment.ControlReaderKey != testControlReaderKey ||
		project.Runtime.Deployment.E2B == nil || project.Runtime.Deployment.E2B.APIKey != "e2b-secret" {
		t.Fatalf("runtime=%+v", project.Runtime)
	}
	compose, found := project.Files[ComposeFile]
	if !found {
		t.Fatalf("missing artifact %q", ComposeFile)
	}
	if compose.Mode != 0o644 {
		t.Fatalf("%s mode=%o want=644", ComposeFile, compose.Mode)
	}
	if !strings.HasPrefix(string(compose.Contents), "name: dorf\n\nservices:\n") {
		t.Fatalf("%s is not the Dorf Compose service document:\n%s", ComposeFile, compose.Contents)
	}

	wantEnvironment := fmt.Sprintf(`# Generated by Dorf from protected deployment configuration. Do not edit.
DORF_PROJECT_VERSION='3'
DORF_RELEASE='0.5.2'
DORF_IMAGE_ID='sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'
DORF_UID='1000'
DORF_GID='1001'
DORF_CONFIG_DIR='%s'
DORF_DATA_DIR='%s'
DORF_STATE_DIR='%s'
DORF_POSTGRES_IMAGE_ID='sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
DORF_POSTGRES_PORT='54329'
DORF_POSTGRES_DB='dorf'
DORF_POSTGRES_USER='dorf'
DORF_POSTGRES_PASSWORD='database-secret'
DORF_DATABASE_URL='postgresql://dorf:database-secret@postgres:5432/dorf?sslmode=disable'
DORF_CONTROL_READER_TOKEN='%s'
E2B_API_KEY='e2b-secret'
`, configDir, dataDir, stateDir, controlReaderToken(testControlReaderKey, testComposeImage().ImageID))
	assertArtifact(t, project, EnvironmentFile, 0o600, []byte(wantEnvironment))
	assertArtifact(t, project, ImageFile, 0o600, []byte(`{"version":"0.5.2","reference":"dorf-local:0.5.2","image_id":"sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee","binary_sha256":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}`+"\n"))
	if len(project.Files) != 4 {
		t.Fatalf("files=%v", project.Files)
	}
	if strings.Contains(string(project.Files[ComposeFile].Contents), "build:") || strings.Contains(string(project.Files[EnvironmentFile].Contents), "DORF_BINARY_SHA256") {
		t.Fatal("rendered project retained a local image build authority")
	}
}

func TestRenderGivesEachServiceOnlyItsRuntimeEnvironment(t *testing.T) {
	project := renderEnvironmentProject(t)
	compose := string(project.Files[ComposeFile].Contents)
	withLayout := func(keys ...string) []string {
		return append([]string{"XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_STATE_HOME"}, keys...)
	}
	services := []struct {
		name string
		next string
		want []string
	}{
		{name: "postgres", next: "migrate", want: []string{"POSTGRES_DB", "POSTGRES_USER", "POSTGRES_PASSWORD"}},
		{name: "migrate", next: "worker", want: withLayout("DORF_DATABASE_URL")},
		{name: "worker", next: "control-reader", want: withLayout("DORF_DATABASE_URL", "E2B_API_KEY")},
		{name: "control-reader", next: "control-api", want: withLayout("DORF_DATABASE_URL", "DORF_CONTROL_READER_TOKEN", "E2B_API_KEY")},
	}
	for _, service := range services {
		t.Run(service.name, func(t *testing.T) {
			block := composeServiceBlock(t, compose, service.name, service.next)
			if strings.Contains(block, "env_file:") {
				t.Fatalf("service receives the whole protected project environment:\n%s", block)
			}
			if got := composeEnvironmentKeys(t, block); strings.Join(got, ",") != strings.Join(service.want, ",") {
				t.Fatalf("runtime environment keys=%v want=%v\n%s", got, service.want, block)
			}
			if service.name != "postgres" {
				assertFixedContainerXDGLayout(t, block)
			}
		})
	}
	t.Run("control-api", func(t *testing.T) {
		block := composeFinalServiceBlock(t, compose, "control-api")
		if strings.Contains(block, "env_file:") {
			t.Fatalf("service receives the whole protected project environment:\n%s", block)
		}
		want := withLayout("DORF_DATABASE_URL", "DORF_CONTROL_READER_ORIGIN", "DORF_CONTROL_READER_TOKEN")
		if got := composeEnvironmentKeys(t, block); strings.Join(got, ",") != strings.Join(want, ",") {
			t.Fatalf("runtime environment keys=%v want=%v\n%s", got, want, block)
		}
		assertFixedContainerXDGLayout(t, block)
	})
}

func TestRenderSeparatesControlAPIFromSandboxProviderAuthority(t *testing.T) {
	spec := optionalServicesSpec(t)
	spec.Deployment.E2B = &deployment.E2B{APIKey: "e2b-provider-secret"}
	project, err := Render(spec)
	if err != nil {
		t.Fatal(err)
	}
	compose := string(project.Files[ComposeFile].Contents)

	reader := composeServiceBlock(t, compose, "control-reader", "control-api")
	for _, wanted := range []string{
		`command: ["serve", "--control-reader", "--listen", "0.0.0.0:8756", "--allow-container-listen"]`,
		`test: ["CMD", "/usr/local/bin/dorf", "_compose-control-reader-health"]`,
		`E2B_API_KEY: "${E2B_API_KEY:-}"`,
	} {
		if !strings.Contains(reader, wanted) {
			t.Fatalf("Sandbox reader is missing provider authority %q:\n%s", wanted, reader)
		}
	}
	control := composeServiceBlock(t, compose, "control-api", "provider-gateway")
	for _, forbidden := range []string{"E2B_API_KEY", "DORF_INCUS_SOCKET", "DORF_INCUS_SOCKET_GID", "DORF_CONFIG_DIR", "DORF_DATA_DIR", "DORF_PROVIDER_GATEWAY_INTERNAL_ORIGIN"} {
		if strings.Contains(control, forbidden) {
			t.Fatalf("control API received Sandbox provider authority %q:\n%s", forbidden, control)
		}
	}
	for _, wanted := range []string{
		`DORF_CONTROL_READER_ORIGIN: "http://control-reader-rpc:8756"`,
		`DORF_CONTROL_READER_TOKEN: "${DORF_CONTROL_READER_TOKEN}"`,
		`source: "./control-config"`,
		`target: /var/lib/dorf/.config`,
	} {
		if !strings.Contains(control, wanted) {
			t.Fatalf("control API is missing narrow reader/config custody %q:\n%s", wanted, control)
		}
	}

	artifact, found := project.Files[ControlDeploymentFile]
	if !found || artifact.Mode != 0o600 {
		t.Fatalf("sanitized control deployment artifact=%+v found=%t", artifact, found)
	}
	if strings.Contains(string(artifact.Contents), "e2b") || strings.Contains(string(artifact.Contents), "incus") || strings.Contains(string(artifact.Contents), "provider-secret") || strings.Contains(string(artifact.Contents), "control_reader_key") {
		t.Fatalf("sanitized control deployment leaked provider authority:\n%s", artifact.Contents)
	}
	var sanitized deployment.Config
	wantDatabase := spec.Deployment.Database
	wantDatabase.VolumeState = ""
	if err := json.Unmarshal(artifact.Contents, &sanitized); err != nil || sanitized.Database != wantDatabase || sanitized.ControlReaderKey != "" || sanitized.E2B != nil || sanitized.Incus != nil {
		t.Fatalf("sanitized deployment=%+v err=%v", sanitized, err)
	}
}

func TestRenderUsesSeparateDatabaseApplicationReaderAndIngressNetworks(t *testing.T) {
	project := renderOptionalServicesProject(t)
	compose := string(project.Files[ComposeFile].Contents)
	services := []struct {
		name, next string
		want       []string
	}{
		{name: "postgres", next: "migrate", want: []string{"database"}},
		{name: "migrate", next: "worker", want: []string{"database"}},
		{name: "worker", next: "control-reader", want: []string{"application", "database", "worker-egress"}},
		{name: "control-reader", next: "control-api", want: []string{"database", "provider", "reader", "reader-egress"}},
		{name: "control-api", next: "provider-gateway", want: []string{"database", "reader"}},
		{name: "provider-gateway", next: "cloudflared", want: []string{"application", "ingress", "provider"}},
	}
	for _, service := range services {
		block := composeServiceBlock(t, compose, service.name, service.next)
		if got := composeNetworkNames(t, block); strings.Join(got, ",") != strings.Join(service.want, ",") {
			t.Fatalf("%s networks=%v want=%v\n%s", service.name, got, service.want, block)
		}
	}
	reader := composeServiceBlock(t, compose, "control-reader", "control-api")
	if !strings.Contains(reader, "          - control-reader-rpc") {
		t.Fatalf("control reader lacks reader-network-only DNS identity:\n%s", reader)
	}
	control := composeServiceBlock(t, compose, "control-api", "provider-gateway")
	if !strings.Contains(control, "condition: service_healthy") {
		t.Fatalf("control API does not wait for authenticated reader health:\n%s", control)
	}
	cloudflared := composeFinalServiceBlock(t, compose, "cloudflared")
	if got := composeNetworkNames(t, cloudflared); strings.Join(got, ",") != "ingress" {
		t.Fatalf("cloudflared networks=%v want=[ingress]\n%s", got, cloudflared)
	}
	for _, internal := range []string{"application", "database", "provider", "reader"} {
		marker := "  " + internal + ":\n    internal: true\n"
		if !strings.Contains(compose, marker) {
			t.Fatalf("network %s is not internal:\n%s", internal, compose)
		}
	}
}

func TestRenderDerivesReaderTokenFromIndependentDeploymentKey(t *testing.T) {
	spec := optionalServicesSpec(t)
	first, err := Render(spec)
	if err != nil {
		t.Fatal(err)
	}
	replayed, err := Render(spec)
	if err != nil {
		t.Fatal(err)
	}
	token := dotenvValue(t, first.Files[EnvironmentFile].Contents, "DORF_CONTROL_READER_TOKEN")
	if len(token) != 64 || token != dotenvValue(t, replayed.Files[EnvironmentFile].Contents, "DORF_CONTROL_READER_TOKEN") {
		t.Fatalf("reader token=%q is not stable 256-bit hex", token)
	}
	if strings.Contains(string(first.Files[EnvironmentFile].Contents), testControlReaderKey) {
		t.Fatal("raw control reader key entered the generated environment")
	}
	changedPassword := spec
	changedPassword.Deployment.Database.Password = "different-database-secret"
	passwordProject, err := Render(changedPassword)
	if err != nil {
		t.Fatal(err)
	}
	if changed := dotenvValue(t, passwordProject.Files[EnvironmentFile].Contents, "DORF_CONTROL_READER_TOKEN"); changed != token {
		t.Fatalf("database password change altered independently keyed reader token: %q", changed)
	}
	changedKey := spec
	changedKey.Deployment.ControlReaderKey = strings.Repeat("d", 64)
	keyProject, err := Render(changedKey)
	if err != nil {
		t.Fatal(err)
	}
	changedImage := spec
	changedImage.Image.ImageID = "sha256:" + strings.Repeat("f", 64)
	imageProject, err := Render(changedImage)
	if err != nil {
		t.Fatal(err)
	}
	for label, project := range map[string]Project{"reader key": keyProject, "image": imageProject} {
		if changed := dotenvValue(t, project.Files[EnvironmentFile].Contents, "DORF_CONTROL_READER_TOKEN"); changed == token {
			t.Fatalf("%s change retained reader token %q", label, token)
		}
	}
}

func TestValidateSpecRequiresIndependentControlReaderKey(t *testing.T) {
	for _, key := range []string{"", strings.Repeat("a", 63), strings.Repeat("A", 64)} {
		spec := optionalServicesSpec(t)
		spec.Deployment.ControlReaderKey = key
		if err := validateSpec(spec); err == nil || !strings.Contains(err.Error(), "control reader key") {
			t.Fatalf("validateSpec() key=%q error=%v", key, err)
		}
	}
}

func TestRenderAddsOnlyPreparedOptionalSiblingServices(t *testing.T) {
	project := renderOptionalServicesProject(t)
	compose := string(project.Files[ComposeFile].Contents)
	environment := string(project.Files[EnvironmentFile].Contents)

	if project.Runtime.Gateway == nil || project.Runtime.Cloudflare == nil {
		t.Fatalf("optional runtime=%+v", project.Runtime)
	}
	for _, forbidden := range []string{"network_mode: host", "/var/run/docker.sock", "env_file:"} {
		if strings.Contains(compose, forbidden) {
			t.Fatalf("optional services gained forbidden authority %q:\n%s", forbidden, compose)
		}
	}
	gateway := composeServiceBlock(t, compose, "provider-gateway", "cloudflared")
	for _, wanted := range []string{
		`command: ["_compose-provider-gateway"]`,
		`DORF_PROVIDER_GATEWAY_STATE: "` + ContainerGatewayStatePath + `"`,
		`source: "${DORF_PROVIDER_GATEWAY_HOST_STATE_PATH}"`,
		`target: "` + ContainerGatewayStatePath + `"`,
		`"${DORF_PROVIDER_GATEWAY_PUBLISH}:8317:8317"`,
		`dev.dorf.config-digest: "${DORF_PROVIDER_GATEWAY_DIGEST}"`,
	} {
		if !strings.Contains(gateway, wanted) {
			t.Fatalf("Gateway service is missing %q:\n%s", wanted, gateway)
		}
	}
	cloudflared := composeFinalServiceBlock(t, compose, "cloudflared")
	for _, wanted := range []string{
		`command: ["_compose-cloudflared"]`,
		`DORF_CLOUDFLARE_STATE: "` + ContainerCloudflareStatePath + `"`,
		`source: "${DORF_CLOUDFLARE_HOST_STATE_PATH}"`,
		"target: \"/var/lib/dorf/.local/share/dorf/provider-gateway/cloudflare\"\n        read_only: true",
		`target: "` + ContainerCloudflareStatePath + `"`,
		`dev.dorf.config-digest: "${DORF_CLOUDFLARE_DIGEST}"`,
	} {
		if !strings.Contains(cloudflared, wanted) {
			t.Fatalf("Cloudflare service is missing %q:\n%s", wanted, cloudflared)
		}
	}
	for _, service := range []string{"worker", "control-reader"} {
		block := composeServiceBlock(t, compose, service, map[string]string{"worker": "control-reader", "control-reader": "control-api"}[service])
		for _, wanted := range []string{`DORF_PROVIDER_GATEWAY_INTERNAL_ORIGIN: "http://provider-gateway:8317"`} {
			if !strings.Contains(block, wanted) {
				t.Fatalf("%s is missing sibling Gateway access %q:\n%s", service, wanted, block)
			}
		}
		if strings.Contains(block, "DORF_PROVIDER_GATEWAY_STATE") {
			t.Fatalf("%s received a second Gateway state locator instead of its fixed HOME layout:\n%s", service, block)
		}
	}
	for _, wanted := range []string{
		"DORF_PROVIDER_GATEWAY_HOST_STATE_PATH='" + filepath.Join(project.Runtime.DataDir, "provider-gateway") + "'",
		"DORF_PROVIDER_GATEWAY_DIGEST='" + strings.Repeat("a", 64) + "'",
		"DORF_PROVIDER_GATEWAY_PUBLISH='10.44.0.1'",
		"DORF_CLOUDFLARE_HOST_STATE_PATH='" + filepath.Join(project.Runtime.DataDir, "provider-gateway", "cloudflare") + "'",
		"DORF_CLOUDFLARE_DIGEST='" + strings.Repeat("c", 64) + "'",
	} {
		if !strings.Contains(environment, wanted) {
			t.Fatalf("generated environment is missing %q:\n%s", wanted, environment)
		}
	}
}

func TestRenderRejectsCloudflareWithoutGateway(t *testing.T) {
	spec := optionalServicesSpec(t)
	spec.Gateway = nil
	if _, err := Render(spec); err == nil || !strings.Contains(err.Error(), "Cloudflare") {
		t.Fatalf("Render() error=%v", err)
	}
}

func TestRenderRejectsOptionalStateOutsideResolvedHostDataLayout(t *testing.T) {
	spec := optionalServicesSpec(t)
	spec.Gateway.StatePath = filepath.Join(t.TempDir(), "provider-gateway")
	if _, err := Render(spec); err == nil || !strings.Contains(err.Error(), "resolved host data layout") {
		t.Fatalf("Render() Gateway state error=%v", err)
	}

	spec = optionalServicesSpec(t)
	spec.Cloudflare.StatePath = filepath.Join(t.TempDir(), "cloudflare")
	if _, err := Render(spec); err == nil || !strings.Contains(err.Error(), "resolved host data layout") {
		t.Fatalf("Render() Cloudflare state error=%v", err)
	}
}

func TestRenderMountsOnlyTheConfiguredLocalIncusSocket(t *testing.T) {
	spec := optionalServicesSpec(t)
	spec.Gateway, spec.Cloudflare = nil, nil
	socketPath := filepath.Join(t.TempDir(), "incus.socket")
	listener, err := net.Listen("unix", socketPath)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = listener.Close() })
	spec.Deployment.Incus = &deployment.Incus{Endpoint: "unix://" + socketPath}
	project, err := Render(spec)
	if err != nil {
		t.Fatal(err)
	}
	if project.Runtime.IncusSocket == nil || project.Runtime.IncusSocket.Path != socketPath || project.Runtime.IncusSocket.GID < 0 {
		t.Fatalf("Incus socket runtime=%+v", project.Runtime.IncusSocket)
	}
	runtimeEndpoint := project.Runtime.Deployment.Incus.Endpoint
	spec.Deployment.Incus.Endpoint = "unix:///changed-after-render.socket"
	if project.Runtime.Deployment.Incus.Endpoint != runtimeEndpoint {
		t.Fatal("rendered runtime retained the caller's mutable Incus pointer")
	}
	compose := string(project.Files[ComposeFile].Contents)
	for _, service := range []string{"worker", "control-reader"} {
		block := composeFinalServiceBlock(t, compose, service)
		if service == "worker" {
			block = composeServiceBlock(t, compose, service, "control-reader")
		} else {
			block = composeServiceBlock(t, compose, service, "control-api")
		}
		for _, wanted := range []string{`source: "${DORF_INCUS_SOCKET}"`, `target: "${DORF_INCUS_SOCKET}"`, "create_host_path: false", `- "${DORF_INCUS_SOCKET_GID}"`} {
			if !strings.Contains(block, wanted) {
				t.Fatalf("%s is missing local Incus socket custody %q:\n%s", service, wanted, block)
			}
		}
	}
	control := composeFinalServiceBlock(t, compose, "control-api")
	if strings.Contains(control, "DORF_INCUS_SOCKET") || strings.Contains(control, "group_add:") {
		t.Fatalf("control API received local Incus authority:\n%s", control)
	}
	for _, forbidden := range []string{"network_mode: host", "/var/run/docker.sock"} {
		if strings.Contains(compose, forbidden) {
			t.Fatalf("local Incus gained forbidden authority %q", forbidden)
		}
	}
}

func TestDeriveIncusSocketOmitsRemoteAndRejectsSymlink(t *testing.T) {
	remote, err := deriveIncusSocket(&deployment.Incus{Endpoint: "https://incus.example:8443"})
	if err != nil || remote != nil {
		t.Fatalf("remote Incus socket=%+v err=%v", remote, err)
	}

	directory := t.TempDir()
	realPath := filepath.Join(directory, "real.socket")
	listener, err := net.Listen("unix", realPath)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = listener.Close() })
	linkPath := filepath.Join(directory, "linked.socket")
	if err := os.Symlink(realPath, linkPath); err != nil {
		t.Fatal(err)
	}
	if socket, err := deriveIncusSocket(&deployment.Incus{Endpoint: "unix://" + linkPath}); err == nil || socket != nil {
		t.Fatalf("symlink Incus socket=%+v err=%v", socket, err)
	}
}

func TestMaterializeWritesOnlyProtectedRuntimeArtifacts(t *testing.T) {
	t.Setenv("E2B_API_KEY", "ambient-key-must-not-enter-the-project")
	sources := t.TempDir()
	project, err := Render(Spec{
		Image: testComposeImage(), UID: 1000, GID: 1000,
		ConfigDir: filepath.Join(sources, "config"), DataDir: filepath.Join(sources, "data"), StateDir: filepath.Join(sources, "state"),
		Deployment: deployment.Config{ControlReaderKey: testControlReaderKey, Database: deployment.Database{
			Host: "127.0.0.1", Port: 54329, Name: "dorf", User: "dorf", Password: "secret",
			Image: "postgres:17.10-bookworm", ImageID: testPostgresImageID,
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if environment := string(project.Files[EnvironmentFile].Contents); strings.Contains(environment, "E2B_API_KEY") || strings.Contains(environment, "ambient-key") {
		t.Fatalf("generated environment fell back to an ambient E2B credential:\n%s", environment)
	}

	directory := filepath.Join(t.TempDir(), "project")
	if err := project.Materialize(directory); err != nil {
		t.Fatal(err)
	}
	info, err := os.Stat(directory)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o700 {
		t.Fatalf("project directory mode=%o want=700", info.Mode().Perm())
	}
	for path, artifact := range project.Files {
		materializedPath := filepath.Join(directory, filepath.FromSlash(path))
		contents, err := os.ReadFile(materializedPath)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		if string(contents) != string(artifact.Contents) {
			t.Fatalf("%s does not contain the rendered artifact", path)
		}
		info, err := os.Stat(materializedPath)
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode().Perm() != artifact.Mode.Perm() {
			t.Fatalf("%s mode=%o want=%o", path, info.Mode().Perm(), artifact.Mode.Perm())
		}
	}

	environmentPath := filepath.Join(directory, EnvironmentFile)
	if err := os.WriteFile(environmentPath, []byte("manual competing authority\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	staleCredential := filepath.Join(directory, "control-config", "dorf", "integrations", "github", "credentials.json")
	if err := os.MkdirAll(filepath.Dir(staleCredential), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(staleCredential, []byte("stale provider authority\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := project.Materialize(directory); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Lstat(staleCredential); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("stale projected credential survived materialization: %v", err)
	}
	contents, err := os.ReadFile(environmentPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(contents) != string(project.Files[EnvironmentFile].Contents) {
		t.Fatal("materialization retained a manually edited derived environment")
	}
	info, err = os.Stat(environmentPath)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Fatalf("derived environment mode=%o want=600", info.Mode().Perm())
	}
}

func TestMaterializeRejectsSymlinkedControlConfigParent(t *testing.T) {
	project := renderEnvironmentProject(t)
	project.Runtime.UID, project.Runtime.GID = os.Geteuid(), os.Getegid()
	directory := filepath.Join(t.TempDir(), "project")
	if err := os.Mkdir(directory, 0o700); err != nil {
		t.Fatal(err)
	}
	outside := t.TempDir()
	sentinel := filepath.Join(outside, "sentinel")
	if err := os.WriteFile(sentinel, []byte("outside\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(directory, "control-config")); err != nil {
		t.Fatal(err)
	}
	if err := project.Materialize(directory); err == nil || !strings.Contains(err.Error(), "operator-owned 0700 directory") {
		t.Fatalf("Materialize() error=%v", err)
	}
	contents, err := os.ReadFile(sentinel)
	if err != nil || string(contents) != "outside\n" {
		t.Fatalf("outside symlink target changed: contents=%q err=%v", contents, err)
	}
}

func TestMaterializeCommitsLiveControlProjectionOnlyAfterInertArtifacts(t *testing.T) {
	project := renderEnvironmentProject(t)
	project.Runtime.UID, project.Runtime.GID = os.Geteuid(), os.Getegid()
	directory := filepath.Join(t.TempDir(), "project")
	if err := project.Materialize(directory); err != nil {
		t.Fatal(err)
	}
	controlPath := filepath.Join(directory, filepath.FromSlash(ControlDeploymentFile))
	before, err := os.ReadFile(controlPath)
	if err != nil {
		t.Fatal(err)
	}

	next := project
	next.Files = make(map[string]File, len(project.Files))
	for path, artifact := range project.Files {
		next.Files[path] = artifact
	}
	next.Files[ControlDeploymentFile] = File{Contents: []byte("changed live authority\n"), Mode: 0o600}
	imagePath := filepath.Join(directory, ImageFile)
	if err := os.Remove(imagePath); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(imagePath, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := next.Materialize(directory); err == nil {
		t.Fatal("Materialize() succeeded with a directory blocking an inert artifact")
	}
	after, err := os.ReadFile(controlPath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(after, before) {
		t.Fatal("failed materialization changed the running control projection")
	}
}

func TestMaterializeRejectsSymlinkedProjectRootWithoutChangingTarget(t *testing.T) {
	project := renderEnvironmentProject(t)
	project.Runtime.UID, project.Runtime.GID = os.Geteuid(), os.Getegid()
	parent := t.TempDir()
	target := filepath.Join(parent, "target")
	if err := os.Mkdir(target, 0o755); err != nil {
		t.Fatal(err)
	}
	directory := filepath.Join(parent, "project")
	if err := os.Symlink(target, directory); err != nil {
		t.Fatal(err)
	}
	if err := project.Materialize(directory); err == nil || !strings.Contains(err.Error(), "operator-owned 0700 directory") {
		t.Fatalf("Materialize() error=%v", err)
	}
	info, err := os.Stat(target)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o755 {
		t.Fatalf("symlink target mode=%o want=755", info.Mode().Perm())
	}
}

func TestLoadImageAuthorityIsOfflineAndBoundToCurrentBinary(t *testing.T) {
	binary := filepath.Join(t.TempDir(), "dorf")
	contents := []byte("exact running binary")
	if err := os.WriteFile(binary, contents, 0o555); err != nil {
		t.Fatal(err)
	}
	digest := sha256.Sum256(contents)
	project := renderEnvironmentProject(t)
	project.Image.BinarySHA256 = hex.EncodeToString(digest[:])
	imageJSON := fmt.Sprintf(`{"version":"%s","reference":"%s","image_id":"%s","binary_sha256":"%s"}`+"\n", project.Image.Version, project.Image.Reference, project.Image.ImageID, project.Image.BinarySHA256)
	project.Files[ImageFile] = File{Contents: []byte(imageJSON), Mode: 0o600}
	project.Runtime.UID, project.Runtime.GID = os.Geteuid(), os.Getegid()
	directory := filepath.Join(t.TempDir(), "compose")
	if err := project.Materialize(directory); err != nil {
		t.Fatal(err)
	}
	image, err := LoadImageAuthority(directory, project.Image.Version, binary, os.Geteuid(), os.Getegid())
	if err != nil || image != project.Image {
		t.Fatalf("image=%+v err=%v", image, err)
	}
	if err := os.Chmod(binary, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(binary, []byte("changed binary"), 0o555); err != nil {
		t.Fatal(err)
	}
	if _, err := LoadImageAuthority(directory, project.Image.Version, binary, os.Geteuid(), os.Getegid()); err == nil || !strings.Contains(err.Error(), "running binary") {
		t.Fatalf("binary drift error=%v", err)
	}
}

func TestValidateSpecRejectsUnrepresentableE2BCredential(t *testing.T) {
	base := Spec{
		Image: testComposeImage(),
		UID:   1000, GID: 1000, ConfigDir: "/home/dorf/.config/dorf", DataDir: "/home/dorf/.local/share/dorf", StateDir: "/home/dorf/.local/state/dorf",
		Deployment: deployment.Config{ControlReaderKey: testControlReaderKey, Database: deployment.Database{
			Host: "127.0.0.1", Port: 54329, Name: "dorf", User: "dorf", Password: "secret",
			Image: "postgres:17.10-bookworm", ImageID: testPostgresImageID,
		}},
	}
	for _, credential := range []string{"contains'quote", `contains\backslash`} {
		t.Run(credential, func(t *testing.T) {
			spec := base
			spec.Deployment.E2B = &deployment.E2B{APIKey: credential}
			if err := validateSpec(spec); err == nil || !strings.Contains(err.Error(), "cannot be represented") {
				t.Fatalf("validateSpec() error=%v", err)
			}
		})
	}
}

func TestValidateSpecRejectsUnrepresentableGeneratedEnvironmentValues(t *testing.T) {
	base := Spec{
		Image: testComposeImage(),
		UID:   1000, GID: 1000, ConfigDir: "/home/dorf/.config/dorf", DataDir: "/home/dorf/.local/share/dorf", StateDir: "/home/dorf/.local/state/dorf",
		Deployment: deployment.Config{ControlReaderKey: testControlReaderKey, Database: deployment.Database{
			Host: "127.0.0.1", Port: 54329, Name: "dorf", User: "dorf", Password: "secret",
			Image: "postgres:17.10-bookworm", ImageID: testPostgresImageID,
		}},
	}
	tests := map[string]func(*Spec){
		"database password": func(spec *Spec) { spec.Deployment.Database.Password = "secret'fragment" },
		"bind source path":  func(spec *Spec) { spec.DataDir = "/srv/dorf's-data" },
	}
	for name, mutate := range tests {
		t.Run(name, func(t *testing.T) {
			spec := base
			mutate(&spec)
			if err := validateSpec(spec); err == nil || !strings.Contains(err.Error(), "cannot be represented") {
				t.Fatalf("validateSpec() error=%v", err)
			}
		})
	}
}

func TestValidateSpecRequiresOrdinaryOperatorAndDisjointMounts(t *testing.T) {
	base := Spec{
		Image: testComposeImage(),
		UID:   1000, GID: 1000, ConfigDir: "/home/dorf/.config/dorf", DataDir: "/home/dorf/.local/share/dorf", StateDir: "/home/dorf/.local/state/dorf",
		Deployment: deployment.Config{ControlReaderKey: testControlReaderKey, Database: deployment.Database{
			Host: "127.0.0.1", Port: 54329, Name: "dorf", User: "dorf", Password: "secret",
			Image: "postgres:17.10-bookworm", ImageID: testPostgresImageID,
		}},
	}
	tests := map[string]func(*Spec){
		"root operator":      func(spec *Spec) { spec.UID = 0 },
		"overlapping mounts": func(spec *Spec) { spec.StateDir = filepath.Join(spec.DataDir, "state") },
	}
	for name, mutate := range tests {
		t.Run(name, func(t *testing.T) {
			spec := base
			mutate(&spec)
			if err := validateSpec(spec); err == nil {
				t.Fatal("validateSpec() accepted unsafe Compose runtime")
			}
		})
	}
}

func renderEnvironmentProject(t *testing.T) Project {
	t.Helper()
	sources := t.TempDir()
	project, err := Render(Spec{
		Image:     testComposeImage(),
		UID:       1000,
		GID:       1001,
		ConfigDir: filepath.Join(sources, "config"),
		DataDir:   filepath.Join(sources, "data"),
		StateDir:  filepath.Join(sources, "state"),
		Deployment: deployment.Config{
			ControlReaderKey: testControlReaderKey,
			Database: deployment.Database{
				Host: "127.0.0.1", Port: 54329, Name: "dorf", User: "dorf", Password: "database-secret",
				Image: "postgres:17.10-bookworm", ImageID: testPostgresImageID,
			},
			E2B: &deployment.E2B{APIKey: "e2b-secret"},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	return project
}

func optionalServicesSpec(t *testing.T) Spec {
	t.Helper()
	root := t.TempDir()
	dataDir := filepath.Join(root, "data")
	return Spec{
		Image: testComposeImage(), UID: 1000, GID: 1001,
		ConfigDir: filepath.Join(root, "config"), DataDir: dataDir, StateDir: filepath.Join(root, "state"),
		Deployment: deployment.Config{ControlReaderKey: testControlReaderKey, Database: deployment.Database{
			Host: "127.0.0.1", Port: 54329, Name: "dorf", User: "dorf", Password: "database-secret",
			Image: "postgres:17.10-bookworm", ImageID: testPostgresImageID,
		}},
		Gateway: &OptionalService{
			StatePath: filepath.Join(dataDir, "provider-gateway"), Digest: strings.Repeat("a", 64), PublishAddress: "10.44.0.1",
		},
		Cloudflare: &OptionalService{
			StatePath: filepath.Join(dataDir, "provider-gateway", "cloudflare"), Digest: strings.Repeat("c", 64),
		},
	}
}

func renderOptionalServicesProject(t *testing.T) Project {
	t.Helper()
	project, err := Render(optionalServicesSpec(t))
	if err != nil {
		t.Fatal(err)
	}
	return project
}

func composeServiceBlock(t *testing.T, compose, service, nextService string) string {
	t.Helper()
	startMarker := "\n  " + service + ":\n"
	start := strings.Index(compose, startMarker)
	if start < 0 {
		t.Fatalf("missing Compose service %q", service)
	}
	start += len(startMarker)
	endMarker := "\n  " + nextService + ":\n"
	end := strings.Index(compose[start:], endMarker)
	if end < 0 {
		t.Fatalf("missing service %q after %q", nextService, service)
	}
	return compose[start : start+end]
}

func composeFinalServiceBlock(t *testing.T, compose, service string) string {
	t.Helper()
	startMarker := "\n  " + service + ":\n"
	start := strings.Index(compose, startMarker)
	if start < 0 {
		t.Fatalf("missing Compose service %q", service)
	}
	start += len(startMarker)
	end := strings.Index(compose[start:], "\nvolumes:\n")
	if end < 0 {
		t.Fatalf("missing volumes section after %q", service)
	}
	return compose[start : start+end]
}

func composeEnvironmentKeys(t *testing.T, service string) []string {
	t.Helper()
	lines := strings.Split(service, "\n")
	for index, line := range lines {
		if line != "    environment:" {
			continue
		}
		var keys []string
		for _, entry := range lines[index+1:] {
			if !strings.HasPrefix(entry, "      ") || strings.HasPrefix(entry, "        ") {
				break
			}
			key, _, ok := strings.Cut(strings.TrimSpace(entry), ":")
			if !ok {
				t.Fatalf("invalid environment entry %q", entry)
			}
			keys = append(keys, key)
		}
		return keys
	}
	t.Fatalf("service has no explicit environment allowlist:\n%s", service)
	return nil
}

func assertFixedContainerXDGLayout(t *testing.T, service string) {
	t.Helper()
	for _, entry := range []string{
		`XDG_CONFIG_HOME: "/var/lib/dorf/.config"`,
		`XDG_DATA_HOME: "/var/lib/dorf/.local/share"`,
		`XDG_STATE_HOME: "/var/lib/dorf/.local/state"`,
	} {
		if !strings.Contains(service, entry) {
			t.Errorf("service is missing fixed container layout %q:\n%s", entry, service)
		}
	}
}

func composeNetworkNames(t *testing.T, service string) []string {
	t.Helper()
	lines := strings.Split(service, "\n")
	for index, line := range lines {
		if line != "    networks:" {
			continue
		}
		var names []string
		for _, entry := range lines[index+1:] {
			if strings.HasPrefix(entry, "      - ") {
				names = append(names, strings.TrimSpace(strings.TrimPrefix(entry, "      - ")))
				continue
			}
			if strings.HasPrefix(entry, "      ") && !strings.HasPrefix(entry, "        ") && strings.HasSuffix(entry, ":") {
				names = append(names, strings.TrimSuffix(strings.TrimSpace(entry), ":"))
				continue
			}
			if strings.HasPrefix(entry, "        ") {
				continue
			}
			break
		}
		return names
	}
	t.Fatalf("service has no explicit networks:\n%s", service)
	return nil
}

func dotenvValue(t *testing.T, environment []byte, key string) string {
	t.Helper()
	prefix := key + "='"
	for _, line := range strings.Split(string(environment), "\n") {
		if strings.HasPrefix(line, prefix) && strings.HasSuffix(line, "'") {
			return strings.TrimSuffix(strings.TrimPrefix(line, prefix), "'")
		}
	}
	t.Fatalf("environment is missing %s:\n%s", key, environment)
	return ""
}

func assertArtifact(t *testing.T, project Project, path string, mode os.FileMode, contents []byte) {
	t.Helper()
	file, ok := project.Files[path]
	if !ok {
		t.Fatalf("missing artifact %q", path)
	}
	if file.Mode != mode {
		t.Fatalf("%s mode=%o want=%o", path, file.Mode, mode)
	}
	if string(file.Contents) != string(contents) {
		t.Fatalf("%s contents differ\n--- got ---\n%s\n--- want ---\n%s", path, file.Contents, contents)
	}
}
