// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actions.sql

package dbsql

import (
	"context"

	"github.com/aphronio/dorf/internal/core"
)

const getActionByIDForUpdate = `-- name: GetActionByIDForUpdate :one
select id,job_id,kind,state,scope_key,created_at,settled_at
from dorf.actions
where id=$1
for update
`

func (q *Queries) GetActionByIDForUpdate(ctx context.Context, id string) (DorfAction, error) {
	row := q.db.QueryRowContext(ctx, getActionByIDForUpdate, id)
	var i DorfAction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.State,
		&i.ScopeKey,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getScopedAction = `-- name: GetScopedAction :one
select id,job_id,kind,state,scope_key,created_at,settled_at
from dorf.actions
where job_id=$1 and kind=$2 and scope_key=$3
`

type GetScopedActionParams struct {
	JobID    string
	Kind     core.ActionKind
	ScopeKey string
}

func (q *Queries) GetScopedAction(ctx context.Context, arg GetScopedActionParams) (DorfAction, error) {
	row := q.db.QueryRowContext(ctx, getScopedAction, arg.JobID, arg.Kind, arg.ScopeKey)
	var i DorfAction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.State,
		&i.ScopeKey,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const insertScopedAction = `-- name: InsertScopedAction :execrows
insert into dorf.actions(id,job_id,kind,state,scope_key)
values($1,$2,$3,'unsettled',$4)
on conflict do nothing
`

type InsertScopedActionParams struct {
	ID       string
	JobID    string
	Kind     core.ActionKind
	ScopeKey string
}

func (q *Queries) InsertScopedAction(ctx context.Context, arg InsertScopedActionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertScopedAction,
		arg.ID,
		arg.JobID,
		arg.Kind,
		arg.ScopeKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActions = `-- name: ListActions :many
select a.id,a.job_id,a.kind,a.state,a.scope_key,a.created_at,a.settled_at
from dorf.actions a
where a.job_id=$1
order by a.created_at,a.id
`

func (q *Queries) ListActions(ctx context.Context, jobID string) ([]DorfAction, error) {
	rows, err := q.db.QueryContext(ctx, listActions, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DorfAction
	for rows.Next() {
		var i DorfAction
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Kind,
			&i.State,
			&i.ScopeKey,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSandboxActionSuccess = `-- name: RecordSandboxActionSuccess :execrows
update dorf.actions
set state='succeeded',settled_at=coalesce(settled_at,clock_timestamp())
where id=$1 and state<>'succeeded'
`

func (q *Queries) RecordSandboxActionSuccess(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordSandboxActionSuccess, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reserveSandbox = `-- name: ReserveSandbox :execrows
with reserved as (
    insert into dorf.sandboxes(id,job_id,name,active_resource_id)
    values($2,$3,$4,$2::text || ':initial')
    on conflict do nothing returning id,active_resource_id
)
insert into dorf.sandbox_resources(id,sandbox_id,ownership_nonce)
select active_resource_id,id,$1 from reserved
`

type ReserveSandboxParams struct {
	OwnershipNonce string
	ID             string
	JobID          string
	Name           string
}

func (q *Queries) ReserveSandbox(ctx context.Context, arg ReserveSandboxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reserveSandbox,
		arg.OwnershipNonce,
		arg.ID,
		arg.JobID,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
