// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_runs.sql

package dbsql

import (
	"context"
	"database/sql"

	"github.com/aphronio/dorf/internal/spine"
)

const bindAgentRunSessionByMessage = `-- name: BindAgentRunSessionByMessage :exec
update dorf.agent_runs
set session_id=coalesce(session_id,$1),updated_at=clock_timestamp()
where message_id=$2
  and (session_id is null or session_id=$1)
`

type BindAgentRunSessionByMessageParams struct {
	SessionID sql.NullString
	MessageID sql.NullString
}

func (q *Queries) BindAgentRunSessionByMessage(ctx context.Context, arg BindAgentRunSessionByMessageParams) error {
	_, err := q.db.ExecContext(ctx, bindAgentRunSessionByMessage, arg.SessionID, arg.MessageID)
	return err
}

const bindImplementationAgentRunSessions = `-- name: BindImplementationAgentRunSessions :exec
update dorf.agent_runs
set session_id=$1,updated_at=clock_timestamp()
where job_id=$2 and role='implement'
  and (session_id is null or session_id=$1)
`

type BindImplementationAgentRunSessionsParams struct {
	SessionID sql.NullString
	JobID     string
}

func (q *Queries) BindImplementationAgentRunSessions(ctx context.Context, arg BindImplementationAgentRunSessionsParams) error {
	_, err := q.db.ExecContext(ctx, bindImplementationAgentRunSessions, arg.SessionID, arg.JobID)
	return err
}

const bindNativeSteer = `-- name: BindNativeSteer :one
update dorf.agent_runs
set native_turn_id=coalesce(native_turn_id,$1),state='completed',
    native_outcome=coalesce(native_outcome,nullif($2::text,'')),
    attention=null,finished_at=coalesce(finished_at,clock_timestamp()),
    updated_at=clock_timestamp()
where id=$3 and (native_turn_id is null or native_turn_id=$1)
returning action_id,coalesce(native_outcome,'') as native_outcome
`

type BindNativeSteerParams struct {
	TurnID  sql.NullString
	Outcome string
	RunID   string
}

type BindNativeSteerRow struct {
	ActionID      string
	NativeOutcome string
}

func (q *Queries) BindNativeSteer(ctx context.Context, arg BindNativeSteerParams) (BindNativeSteerRow, error) {
	row := q.db.QueryRowContext(ctx, bindNativeSteer, arg.TurnID, arg.Outcome, arg.RunID)
	var i BindNativeSteerRow
	err := row.Scan(&i.ActionID, &i.NativeOutcome)
	return i, err
}

const bindNativeTurn = `-- name: BindNativeTurn :one
update dorf.agent_runs
set native_turn_id=coalesce(native_turn_id,$1),
    state=$2,native_outcome=nullif($3::text,''),
    attention=nullif($4::text,''),
    finished_at=case when $2::text in ('completed','failed','interrupted')
        then coalesce(finished_at,clock_timestamp()) else finished_at end,
    updated_at=clock_timestamp()
where id=$5 and (native_turn_id is null or native_turn_id=$1)
returning action_id
`

type BindNativeTurnParams struct {
	TurnID    sql.NullString
	State     spine.AgentRunState
	Outcome   string
	Attention string
	RunID     string
}

func (q *Queries) BindNativeTurn(ctx context.Context, arg BindNativeTurnParams) (string, error) {
	row := q.db.QueryRowContext(ctx, bindNativeTurn,
		arg.TurnID,
		arg.State,
		arg.Outcome,
		arg.Attention,
		arg.RunID,
	)
	var action_id string
	err := row.Scan(&action_id)
	return action_id, err
}

const bindReviewAgentRunSession = `-- name: BindReviewAgentRunSession :execrows
update dorf.agent_runs
set session_id=coalesce(session_id,$1),updated_at=clock_timestamp()
where id=$2 and (session_id is null or session_id=$1)
`

type BindReviewAgentRunSessionParams struct {
	SessionID sql.NullString
	RunID     string
}

func (q *Queries) BindReviewAgentRunSession(ctx context.Context, arg BindReviewAgentRunSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindReviewAgentRunSession, arg.SessionID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const blockAgentRunDelivery = `-- name: BlockAgentRunDelivery :exec
update dorf.agent_runs
set state='uncertain',attention=$1,updated_at=clock_timestamp()
where id=$2 and state not in ('completed','failed','interrupted')
`

type BlockAgentRunDeliveryParams struct {
	Reason sql.NullString
	RunID  string
}

func (q *Queries) BlockAgentRunDelivery(ctx context.Context, arg BlockAgentRunDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, blockAgentRunDelivery, arg.Reason, arg.RunID)
	return err
}

const countImplementationNativeMutations = `-- name: CountImplementationNativeMutations :one
select count(*)
from dorf.agent_runs
where job_id=$1 and role='implement'
  and state in ('submitting','active','uncertain')
`

func (q *Queries) CountImplementationNativeMutations(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImplementationNativeMutations, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failAgentRun = `-- name: FailAgentRun :one
update dorf.agent_runs
set state='failed',
    native_outcome=case when native_turn_id is null then null else 'failed' end,
    attention=$1,updated_at=clock_timestamp()
where id=$2
returning action_id
`

type FailAgentRunParams struct {
	Reason sql.NullString
	RunID  string
}

func (q *Queries) FailAgentRun(ctx context.Context, arg FailAgentRunParams) (string, error) {
	row := q.db.QueryRowContext(ctx, failAgentRun, arg.Reason, arg.RunID)
	var action_id string
	err := row.Scan(&action_id)
	return action_id, err
}

const getAgentRunBaseline = `-- name: GetAgentRunBaseline :one
select (baseline_native_turn_id is not null)::boolean as recorded,
       coalesce(baseline_native_turn_id,'') as baseline_turn_id
from dorf.agent_runs
where id=$1
`

type GetAgentRunBaselineRow struct {
	Recorded       bool
	BaselineTurnID string
}

func (q *Queries) GetAgentRunBaseline(ctx context.Context, runID string) (GetAgentRunBaselineRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentRunBaseline, runID)
	var i GetAgentRunBaselineRow
	err := row.Scan(&i.Recorded, &i.BaselineTurnID)
	return i, err
}

const getAgentRunByMessage = `-- name: GetAgentRunByMessage :one
select id,job_id,coalesce(message_id,'') as message_id,action_id,
       coalesce(session_id,'') as session_id,state,
       (baseline_native_turn_id is not null)::boolean as baseline_recorded,
       coalesce(baseline_native_turn_id,'') as baseline_native_turn_id,
       coalesce(native_turn_id,'') as native_turn_id,
       coalesce(native_outcome,'') as native_outcome,
       coalesce(attention,'') as attention,role
from dorf.agent_runs
where message_id=$1::text
`

type GetAgentRunByMessageRow struct {
	ID                   string
	JobID                string
	MessageID            string
	ActionID             string
	SessionID            string
	State                spine.AgentRunState
	BaselineRecorded     bool
	BaselineNativeTurnID string
	NativeTurnID         string
	NativeOutcome        string
	Attention            string
	Role                 string
}

func (q *Queries) GetAgentRunByMessage(ctx context.Context, messageID string) (GetAgentRunByMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentRunByMessage, messageID)
	var i GetAgentRunByMessageRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.MessageID,
		&i.ActionID,
		&i.SessionID,
		&i.State,
		&i.BaselineRecorded,
		&i.BaselineNativeTurnID,
		&i.NativeTurnID,
		&i.NativeOutcome,
		&i.Attention,
		&i.Role,
	)
	return i, err
}

const getNativeMutationDelivery = `-- name: GetNativeMutationDelivery :one
select m.id as message_id,m.job_id,m.from_kind,m.from_id,m.sequence,m.input,
       m.delivery_intent,coalesce(m.steer_target_turn_id,'') as steer_target_turn_id,
       ar.id as agent_run_id,ar.job_id as agent_run_job_id,
       coalesce(ar.message_id,'') as agent_run_message_id,ar.action_id,
       coalesce(ar.session_id,'') as session_id,ar.state,
       (ar.baseline_native_turn_id is not null)::boolean as baseline_recorded,
       coalesce(ar.baseline_native_turn_id,'') as baseline_native_turn_id,
       coalesce(ar.native_turn_id,'') as native_turn_id,
       coalesce(ar.native_outcome,'') as native_outcome,
       coalesce(ar.attention,'') as attention,ar.role
from dorf.job_messages m
join dorf.agent_runs ar on ar.message_id=m.id
where m.job_id=$1 and ar.state in ('submitting','active','uncertain')
order by m.sequence
limit 1
`

type GetNativeMutationDeliveryRow struct {
	MessageID            string
	JobID                string
	FromKind             spine.MessageFromKind
	FromID               string
	Sequence             int64
	Input                string
	DeliveryIntent       spine.MessageDeliveryIntent
	SteerTargetTurnID    string
	AgentRunID           string
	AgentRunJobID        string
	AgentRunMessageID    string
	ActionID             string
	SessionID            string
	State                spine.AgentRunState
	BaselineRecorded     bool
	BaselineNativeTurnID string
	NativeTurnID         string
	NativeOutcome        string
	Attention            string
	Role                 string
}

func (q *Queries) GetNativeMutationDelivery(ctx context.Context, jobID string) (GetNativeMutationDeliveryRow, error) {
	row := q.db.QueryRowContext(ctx, getNativeMutationDelivery, jobID)
	var i GetNativeMutationDeliveryRow
	err := row.Scan(
		&i.MessageID,
		&i.JobID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.DeliveryIntent,
		&i.SteerTargetTurnID,
		&i.AgentRunID,
		&i.AgentRunJobID,
		&i.AgentRunMessageID,
		&i.ActionID,
		&i.SessionID,
		&i.State,
		&i.BaselineRecorded,
		&i.BaselineNativeTurnID,
		&i.NativeTurnID,
		&i.NativeOutcome,
		&i.Attention,
		&i.Role,
	)
	return i, err
}

const insertAgentRun = `-- name: InsertAgentRun :exec
insert into dorf.agent_runs(id,job_id,message_id,action_id,session_id,role,state)
values(
    $1,$2,$3,$4,
    nullif($5::text,''),$6,'pending'
)
`

type InsertAgentRunParams struct {
	ID        string
	JobID     string
	MessageID sql.NullString
	ActionID  string
	SessionID string
	Role      string
}

func (q *Queries) InsertAgentRun(ctx context.Context, arg InsertAgentRunParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentRun,
		arg.ID,
		arg.JobID,
		arg.MessageID,
		arg.ActionID,
		arg.SessionID,
		arg.Role,
	)
	return err
}

const insertAgentRunFromImplementationSession = `-- name: InsertAgentRunFromImplementationSession :execrows
insert into dorf.agent_runs(id,job_id,message_id,action_id,session_id,role,state)
select $1,$2,$3,$4,
       native_session_id,'implement','pending'
from dorf.sessions
where job_id=$2
`

type InsertAgentRunFromImplementationSessionParams struct {
	ID        string
	JobID     string
	MessageID sql.NullString
	ActionID  string
}

func (q *Queries) InsertAgentRunFromImplementationSession(ctx context.Context, arg InsertAgentRunFromImplementationSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAgentRunFromImplementationSession,
		arg.ID,
		arg.JobID,
		arg.MessageID,
		arg.ActionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertAgentRunIfAbsent = `-- name: InsertAgentRunIfAbsent :exec
insert into dorf.agent_runs(id,job_id,message_id,action_id,session_id,role,state)
values(
    $1,$2,$3,$4,
    nullif($5::text,''),'implement','pending'
)
on conflict do nothing
`

type InsertAgentRunIfAbsentParams struct {
	ID        string
	JobID     string
	MessageID sql.NullString
	ActionID  string
	SessionID string
}

func (q *Queries) InsertAgentRunIfAbsent(ctx context.Context, arg InsertAgentRunIfAbsentParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentRunIfAbsent,
		arg.ID,
		arg.JobID,
		arg.MessageID,
		arg.ActionID,
		arg.SessionID,
	)
	return err
}

const insertInitialAgentRun = `-- name: InsertInitialAgentRun :exec
insert into dorf.agent_runs(id,job_id,message_id,action_id,role,state)
values($1,$2,$3,$4,'implement','pending')
on conflict do nothing
`

type InsertInitialAgentRunParams struct {
	ID        string
	JobID     string
	MessageID sql.NullString
	ActionID  string
}

func (q *Queries) InsertInitialAgentRun(ctx context.Context, arg InsertInitialAgentRunParams) error {
	_, err := q.db.ExecContext(ctx, insertInitialAgentRun,
		arg.ID,
		arg.JobID,
		arg.MessageID,
		arg.ActionID,
	)
	return err
}

const markAgentRunUncertain = `-- name: MarkAgentRunUncertain :one
update dorf.agent_runs
set state='uncertain',attention=$1,updated_at=clock_timestamp()
where id=$2
returning action_id
`

type MarkAgentRunUncertainParams struct {
	Reason sql.NullString
	RunID  string
}

func (q *Queries) MarkAgentRunUncertain(ctx context.Context, arg MarkAgentRunUncertainParams) (string, error) {
	row := q.db.QueryRowContext(ctx, markAgentRunUncertain, arg.Reason, arg.RunID)
	var action_id string
	err := row.Scan(&action_id)
	return action_id, err
}

const prepareAgentRun = `-- name: PrepareAgentRun :execrows
update dorf.agent_runs
set state='submitting',baseline_native_turn_id=$1,
    attention=null,started_at=coalesce(started_at,clock_timestamp()),
    updated_at=clock_timestamp()
where id=$2 and state='pending'
`

type PrepareAgentRunParams struct {
	BaselineTurnID sql.NullString
	RunID          string
}

func (q *Queries) PrepareAgentRun(ctx context.Context, arg PrepareAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, prepareAgentRun, arg.BaselineTurnID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const propagateNativeTurnOutcomeToSteers = `-- name: PropagateNativeTurnOutcomeToSteers :exec
update dorf.agent_runs accepted
set native_outcome=$1,updated_at=clock_timestamp()
from dorf.job_messages message,dorf.agent_runs source
where source.id=$2 and accepted.id<>source.id
  and accepted.job_id=source.job_id and accepted.session_id=source.session_id
  and accepted.message_id=message.id and message.delivery_intent='steer'
  and message.steer_target_turn_id=$3
  and accepted.native_turn_id=$3
  and accepted.state='completed' and accepted.native_outcome is null
`

type PropagateNativeTurnOutcomeToSteersParams struct {
	Outcome sql.NullString
	RunID   string
	TurnID  sql.NullString
}

func (q *Queries) PropagateNativeTurnOutcomeToSteers(ctx context.Context, arg PropagateNativeTurnOutcomeToSteersParams) error {
	_, err := q.db.ExecContext(ctx, propagateNativeTurnOutcomeToSteers, arg.Outcome, arg.RunID, arg.TurnID)
	return err
}

const setAgentRunAttention = `-- name: SetAgentRunAttention :execrows
update dorf.agent_runs
set attention=$1,updated_at=clock_timestamp()
where id=$2
`

type SetAgentRunAttentionParams struct {
	Reason sql.NullString
	RunID  string
}

func (q *Queries) SetAgentRunAttention(ctx context.Context, arg SetAgentRunAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAgentRunAttention, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
