// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_runs.sql

package dbsql

import (
	"context"
	"database/sql"

	"github.com/aphronio/dorf/internal/core"
)

const bindAgentRunIdentity = `-- name: BindAgentRunIdentity :execrows
update dorf.agent_runs
set harness=coalesce(harness,$1),
    thread_id=coalesce(thread_id,$2)
where id=$3
  and (harness is null or harness=$1)
  and (thread_id is null or thread_id=$2)
`

type BindAgentRunIdentityParams struct {
	Harness  sql.NullString
	ThreadID sql.NullString
	RunID    string
}

func (q *Queries) BindAgentRunIdentity(ctx context.Context, arg BindAgentRunIdentityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindAgentRunIdentity, arg.Harness, arg.ThreadID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindHarnessTurn = `-- name: BindHarnessTurn :execrows
update dorf.agent_runs
set turn_id=coalesce(turn_id,$1),state=$2,
    turn_outcome=nullif($3::text,''),attention=nullif($4::text,''),
    finished_at=case when $2::text in ('completed','failed','interrupted')
        then coalesce(finished_at,clock_timestamp()) else finished_at end
where id=$5 and harness=$6 and thread_id=$7
  and (turn_id is null or turn_id=$1)
`

type BindHarnessTurnParams struct {
	TurnID      sql.NullString
	State       core.AgentRunState
	TurnOutcome string
	Attention   string
	RunID       string
	Harness     sql.NullString
	ThreadID    sql.NullString
}

func (q *Queries) BindHarnessTurn(ctx context.Context, arg BindHarnessTurnParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindHarnessTurn,
		arg.TurnID,
		arg.State,
		arg.TurnOutcome,
		arg.Attention,
		arg.RunID,
		arg.Harness,
		arg.ThreadID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindPendingFollowToSessionThread = `-- name: BindPendingFollowToSessionThread :execrows
update dorf.agent_runs ar
set harness=p.harness,thread_id=j.thread_id
from dorf.sessions j
join dorf.sandbox_profile_revisions p on p.name=j.sandbox_profile and p.definition_hash=j.sandbox_profile_revision,
     dorf.session_messages m
where ar.message_id=$1 and m.id=ar.message_id
  and j.id=ar.session_id and m.delivery_intent='follow'
  and ar.state='pending' and ar.baseline_turn_id is null and ar.thread_id is null
  and j.thread_id is not null
  and (ar.harness is null or ar.harness=p.harness)
`

func (q *Queries) BindPendingFollowToSessionThread(ctx context.Context, messageID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindPendingFollowToSessionThread, messageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindSessionThread = `-- name: BindSessionThread :execrows
update dorf.sessions j
set thread_id=$1
from dorf.agent_runs ar,dorf.sandbox_profile_revisions p
where ar.id=$2 and j.id=ar.session_id
  and p.name=j.sandbox_profile and p.definition_hash=j.sandbox_profile_revision
  and p.harness=$3
  and j.workflow_name='' and j.workflow_revision=''
  and (j.thread_id is null or j.thread_id=$1)
`

type BindSessionThreadParams struct {
	ThreadID sql.NullString
	RunID    string
	Harness  string
}

func (q *Queries) BindSessionThread(ctx context.Context, arg BindSessionThreadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindSessionThread, arg.ThreadID, arg.RunID, arg.Harness)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindSteer = `-- name: BindSteer :one
update dorf.agent_runs
set turn_id=coalesce(turn_id,$1),state='completed',
    turn_outcome=coalesce(turn_outcome,nullif($2::text,'')),
    attention=null,finished_at=coalesce(finished_at,clock_timestamp())
where id=$3 and harness is not null and thread_id is not null
  and state not in ('failed','interrupted')
  and (turn_id is null or turn_id=$1)
returning coalesce(turn_outcome,'') as turn_outcome
`

type BindSteerParams struct {
	TurnID      sql.NullString
	TurnOutcome string
	RunID       string
}

func (q *Queries) BindSteer(ctx context.Context, arg BindSteerParams) (string, error) {
	row := q.db.QueryRowContext(ctx, bindSteer, arg.TurnID, arg.TurnOutcome, arg.RunID)
	var turn_outcome string
	err := row.Scan(&turn_outcome)
	return turn_outcome, err
}

const failAgentRun = `-- name: FailAgentRun :execrows
update dorf.agent_runs
set state='failed',
    turn_outcome=case when turn_id is null then null else 'failed' end,
    attention=$1,
    finished_at=case when started_at is null then null else coalesce(finished_at,clock_timestamp()) end
where id=$2 and state not in ('completed','interrupted')
`

type FailAgentRunParams struct {
	Reason sql.NullString
	RunID  string
}

func (q *Queries) FailAgentRun(ctx context.Context, arg FailAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failAgentRun, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentRunByMessage = `-- name: GetAgentRunByMessage :one
select id,session_id,message_id,state,
       coalesce(harness,'') as harness,coalesce(thread_id,'') as thread_id,
       (baseline_turn_id is not null)::boolean as baseline_recorded,
       coalesce(baseline_turn_id,'') as baseline_turn_id,
       coalesce(turn_id,'') as turn_id,coalesce(turn_outcome,'') as turn_outcome,
       coalesce(attention,'') as attention,role,coalesce(input_revision,'') as input_revision,
       coalesce(capability,'') as capability,coalesce(sandbox_id,'') as sandbox_id,
       coalesce(submission_nonce,'') as submission_nonce,started_at,finished_at,interrupt_requested
from dorf.agent_runs
where message_id=$1::text
`

type GetAgentRunByMessageRow struct {
	ID                 string
	SessionID          string
	MessageID          string
	State              core.AgentRunState
	Harness            string
	ThreadID           string
	BaselineRecorded   bool
	BaselineTurnID     string
	TurnID             string
	TurnOutcome        string
	Attention          string
	Role               string
	InputRevision      string
	Capability         string
	SandboxID          string
	SubmissionNonce    string
	StartedAt          sql.NullTime
	FinishedAt         sql.NullTime
	InterruptRequested bool
}

func (q *Queries) GetAgentRunByMessage(ctx context.Context, messageID string) (GetAgentRunByMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentRunByMessage, messageID)
	var i GetAgentRunByMessageRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.State,
		&i.Harness,
		&i.ThreadID,
		&i.BaselineRecorded,
		&i.BaselineTurnID,
		&i.TurnID,
		&i.TurnOutcome,
		&i.Attention,
		&i.Role,
		&i.InputRevision,
		&i.Capability,
		&i.SandboxID,
		&i.SubmissionNonce,
		&i.StartedAt,
		&i.FinishedAt,
		&i.InterruptRequested,
	)
	return i, err
}

const getAgentRunForBinding = `-- name: GetAgentRunForBinding :one
select session_id,sandbox_id,role,state,coalesce(harness,'') as harness,
       coalesce(thread_id,'') as thread_id,coalesce(turn_id,'') as turn_id,
       coalesce(turn_outcome,'') as turn_outcome
from dorf.agent_runs
where id=$1
for update
`

type GetAgentRunForBindingRow struct {
	SessionID   string
	SandboxID   string
	Role        string
	State       core.AgentRunState
	Harness     string
	ThreadID    string
	TurnID      string
	TurnOutcome string
}

func (q *Queries) GetAgentRunForBinding(ctx context.Context, runID string) (GetAgentRunForBindingRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentRunForBinding, runID)
	var i GetAgentRunForBindingRow
	err := row.Scan(
		&i.SessionID,
		&i.SandboxID,
		&i.Role,
		&i.State,
		&i.Harness,
		&i.ThreadID,
		&i.TurnID,
		&i.TurnOutcome,
	)
	return i, err
}

const getAgentRunPreparation = `-- name: GetAgentRunPreparation :one
select coalesce(harness,'') as harness,(baseline_turn_id is not null)::boolean as recorded,
       coalesce(baseline_turn_id,'') as baseline_turn_id
from dorf.agent_runs
where id=$1
`

type GetAgentRunPreparationRow struct {
	Harness        string
	Recorded       bool
	BaselineTurnID string
}

func (q *Queries) GetAgentRunPreparation(ctx context.Context, runID string) (GetAgentRunPreparationRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentRunPreparation, runID)
	var i GetAgentRunPreparationRow
	err := row.Scan(&i.Harness, &i.Recorded, &i.BaselineTurnID)
	return i, err
}

const getMessageInterruptTarget = `-- name: GetMessageInterruptTarget :one
select source.id,source.session_id,source.state,source.interrupt_requested
from dorf.agent_runs requested
join dorf.agent_runs source on source.session_id=requested.session_id
    and source.sandbox_id=requested.sandbox_id and source.harness=requested.harness
    and source.thread_id=requested.thread_id
    and source.turn_id=coalesce(requested.turn_id, (
        select steer_target_turn_id from dorf.session_messages where id=requested.message_id
    ))
join dorf.session_messages origin on origin.id=source.message_id and origin.delivery_intent='follow'
where requested.session_id=$1 and requested.message_id=$2
`

type GetMessageInterruptTargetParams struct {
	SessionID string
	MessageID string
}

type GetMessageInterruptTargetRow struct {
	ID                 string
	SessionID          string
	State              core.AgentRunState
	InterruptRequested bool
}

func (q *Queries) GetMessageInterruptTarget(ctx context.Context, arg GetMessageInterruptTargetParams) (GetMessageInterruptTargetRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageInterruptTarget, arg.SessionID, arg.MessageID)
	var i GetMessageInterruptTargetRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.State,
		&i.InterruptRequested,
	)
	return i, err
}

const insertAdmittedAgentRun = `-- name: InsertAdmittedAgentRun :execrows
insert into dorf.agent_runs(
    id,session_id,message_id,harness,thread_id,role,state,input_revision,capability,sandbox_id
)
select $1,j.id,$2,$3,$4,
       $5,'pending',$6,$7,$8
from dorf.sessions j
where j.id=$9
on conflict do nothing
`

type InsertAdmittedAgentRunParams struct {
	ID            string
	MessageID     string
	Harness       sql.NullString
	ThreadID      sql.NullString
	Role          string
	InputRevision sql.NullString
	Capability    sql.NullString
	SandboxID     string
	SessionID     string
}

func (q *Queries) InsertAdmittedAgentRun(ctx context.Context, arg InsertAdmittedAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAdmittedAgentRun,
		arg.ID,
		arg.MessageID,
		arg.Harness,
		arg.ThreadID,
		arg.Role,
		arg.InputRevision,
		arg.Capability,
		arg.SandboxID,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const interruptAgentRun = `-- name: InterruptAgentRun :execrows
update dorf.agent_runs
set state='interrupted',
    turn_outcome=case when turn_id is null then null else 'interrupted' end,
    attention=$1::text,
    finished_at=case when started_at is null then null else coalesce(finished_at,clock_timestamp()) end
where id=$2 and state in ('pending','submitting','active','uncertain')
`

type InterruptAgentRunParams struct {
	Reason string
	RunID  string
}

func (q *Queries) InterruptAgentRun(ctx context.Context, arg InterruptAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptAgentRun, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listUnsettledAgentMessages = `-- name: ListUnsettledAgentMessages :many
select m.id as message_id,ar.sandbox_id
from dorf.session_messages m
join dorf.agent_runs ar on ar.message_id=m.id
where m.session_id=$1
  and (ar.state in ('submitting','active','uncertain')
       or (ar.baseline_turn_id is not null and ar.state not in ('completed','failed','interrupted')))
order by m.sequence,ar.id
`

type ListUnsettledAgentMessagesRow struct {
	MessageID string
	SandboxID string
}

func (q *Queries) ListUnsettledAgentMessages(ctx context.Context, sessionID string) ([]ListUnsettledAgentMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnsettledAgentMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnsettledAgentMessagesRow
	for rows.Next() {
		var i ListUnsettledAgentMessagesRow
		if err := rows.Scan(&i.MessageID, &i.SandboxID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentRunUncertain = `-- name: MarkAgentRunUncertain :execrows
update dorf.agent_runs
set state='uncertain',attention=$1
where id=$2 and state not in ('completed','failed','interrupted')
`

type MarkAgentRunUncertainParams struct {
	Reason sql.NullString
	RunID  string
}

func (q *Queries) MarkAgentRunUncertain(ctx context.Context, arg MarkAgentRunUncertainParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAgentRunUncertain, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const prepareAgentRun = `-- name: PrepareAgentRun :execrows
update dorf.agent_runs
set state='submitting',harness=coalesce(harness,$1),
    baseline_turn_id=$2,
    attention=null,started_at=coalesce(started_at,clock_timestamp())
where id=$3 and state='pending'
  and (harness is null or harness=$1)
`

type PrepareAgentRunParams struct {
	Harness        sql.NullString
	BaselineTurnID sql.NullString
	RunID          string
}

func (q *Queries) PrepareAgentRun(ctx context.Context, arg PrepareAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, prepareAgentRun, arg.Harness, arg.BaselineTurnID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const propagateTurnOutcomeToSteers = `-- name: PropagateTurnOutcomeToSteers :exec
update dorf.agent_runs accepted
set turn_outcome=$1
from dorf.session_messages message,dorf.agent_runs source
where source.id=$2 and accepted.id<>source.id
  and accepted.session_id=source.session_id and accepted.harness=source.harness and accepted.thread_id=source.thread_id
  and accepted.message_id=message.id and message.delivery_intent='steer'
  and message.steer_target_turn_id=$3
  and accepted.turn_id=$3
  and accepted.state='completed' and accepted.turn_outcome is null
`

type PropagateTurnOutcomeToSteersParams struct {
	TurnOutcome sql.NullString
	RunID       string
	TurnID      sql.NullString
}

func (q *Queries) PropagateTurnOutcomeToSteers(ctx context.Context, arg PropagateTurnOutcomeToSteersParams) error {
	_, err := q.db.ExecContext(ctx, propagateTurnOutcomeToSteers, arg.TurnOutcome, arg.RunID, arg.TurnID)
	return err
}

const requestAgentRunInterrupt = `-- name: RequestAgentRunInterrupt :execrows
update dorf.agent_runs set interrupt_requested=true
where id=$1 and state in ('active','uncertain') and turn_id is not null
`

func (q *Queries) RequestAgentRunInterrupt(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestAgentRunInterrupt, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueAutoMessageAsFollow = `-- name: RequeueAutoMessageAsFollow :execrows
with eligible as (
    select m.id
    from dorf.session_messages m
    join dorf.agent_runs ar on ar.message_id=m.id
    where ar.id=$2
      and m.requested_intent='auto' and m.delivery_intent='steer'
      and m.steer_target_turn_id=$3
      and ar.turn_id is null and ar.state in ('pending','submitting','uncertain')
      and ($1::text = '' or m.observation)
      and (ar.baseline_turn_id is null or ar.baseline_turn_id=m.steer_target_turn_id)
    for update of m,ar
), requeued_message as (
    update dorf.session_messages m
    set delivery_intent='follow',steer_target_turn_id=null
    from eligible e
    where m.id=e.id
    returning m.id
)
update dorf.agent_runs ar
set state=case when $1::text = '' then 'pending' else 'active' end,
    baseline_turn_id=case when $1::text = '' then null else ar.baseline_turn_id end,
    turn_id=nullif($1::text,''),attention=null
from requeued_message m
where ar.id=$2 and ar.message_id=m.id
  and ar.turn_id is null and ar.state in ('pending','submitting','uncertain')
  and (ar.baseline_turn_id is null or ar.baseline_turn_id=$3)
`

type RequeueAutoMessageAsFollowParams struct {
	AcceptedTurnID string
	RunID          string
	TargetTurnID   sql.NullString
}

func (q *Queries) RequeueAutoMessageAsFollow(ctx context.Context, arg RequeueAutoMessageAsFollowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueAutoMessageAsFollow, arg.AcceptedTurnID, arg.RunID, arg.TargetTurnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAgentRunAttention = `-- name: SetAgentRunAttention :execrows
update dorf.agent_runs
set attention=$1
where id=$2
`

type SetAgentRunAttentionParams struct {
	Reason sql.NullString
	RunID  string
}

func (q *Queries) SetAgentRunAttention(ctx context.Context, arg SetAgentRunAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAgentRunAttention, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
