// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_runs.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"

	"github.com/aphronio/dorf/internal/spine"
)

const bindAgentRunIdentity = `-- name: BindAgentRunIdentity :execrows
update dorf.agent_runs
set harness=coalesce(harness,$1),
    thread_id=coalesce(thread_id,$2)
where id=$3
  and (harness is null or harness=$1)
  and (thread_id is null or thread_id=$2)
`

type BindAgentRunIdentityParams struct {
	Harness  sql.NullString
	ThreadID sql.NullString
	RunID    string
}

func (q *Queries) BindAgentRunIdentity(ctx context.Context, arg BindAgentRunIdentityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindAgentRunIdentity, arg.Harness, arg.ThreadID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindHarnessTurn = `-- name: BindHarnessTurn :execrows
update dorf.agent_runs
set turn_id=coalesce(turn_id,$1),state=$2,
    turn_outcome=nullif($3::text,''),attention=nullif($4::text,''),
    finished_at=case when $2::text in ('completed','failed','interrupted')
        then coalesce(finished_at,clock_timestamp()) else finished_at end
where id=$5 and harness=$6 and thread_id=$7
  and (turn_id is null or turn_id=$1)
`

type BindHarnessTurnParams struct {
	TurnID      sql.NullString
	State       spine.AgentRunState
	TurnOutcome string
	Attention   string
	RunID       string
	Harness     sql.NullString
	ThreadID    sql.NullString
}

func (q *Queries) BindHarnessTurn(ctx context.Context, arg BindHarnessTurnParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindHarnessTurn,
		arg.TurnID,
		arg.State,
		arg.TurnOutcome,
		arg.Attention,
		arg.RunID,
		arg.Harness,
		arg.ThreadID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindImplementationInputRevision = `-- name: BindImplementationInputRevision :execrows
update dorf.agent_runs
set input_revision=coalesce(input_revision,$1)
where id=$2 and role='implement' and state='pending'
  and (input_revision is null or input_revision=$1)
`

type BindImplementationInputRevisionParams struct {
	InputRevision sql.NullString
	RunID         string
}

func (q *Queries) BindImplementationInputRevision(ctx context.Context, arg BindImplementationInputRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindImplementationInputRevision, arg.InputRevision, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindSteer = `-- name: BindSteer :one
update dorf.agent_runs
set turn_id=coalesce(turn_id,$1),state='completed',
    turn_outcome=coalesce(turn_outcome,nullif($2::text,'')),
    attention=null,finished_at=coalesce(finished_at,clock_timestamp())
where id=$3 and harness is not null and thread_id is not null
  and state not in ('failed','interrupted')
  and (turn_id is null or turn_id=$1)
returning coalesce(turn_outcome,'') as turn_outcome
`

type BindSteerParams struct {
	TurnID      sql.NullString
	TurnOutcome string
	RunID       string
}

func (q *Queries) BindSteer(ctx context.Context, arg BindSteerParams) (string, error) {
	row := q.db.QueryRowContext(ctx, bindSteer, arg.TurnID, arg.TurnOutcome, arg.RunID)
	var turn_outcome string
	err := row.Scan(&turn_outcome)
	return turn_outcome, err
}

const failAgentRun = `-- name: FailAgentRun :execrows
update dorf.agent_runs
set state='failed',
    turn_outcome=case when turn_id is null then null else 'failed' end,
    attention=$1,
    finished_at=case when started_at is null then null else coalesce(finished_at,clock_timestamp()) end
where id=$2 and state not in ('completed','interrupted')
`

type FailAgentRunParams struct {
	Reason sql.NullString
	RunID  string
}

func (q *Queries) FailAgentRun(ctx context.Context, arg FailAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failAgentRun, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentRunByMessage = `-- name: GetAgentRunByMessage :one
select id,job_id,message_id,state,
       coalesce(harness,'') as harness,coalesce(thread_id,'') as thread_id,
       (baseline_turn_id is not null)::boolean as baseline_recorded,
       coalesce(baseline_turn_id,'') as baseline_turn_id,
       coalesce(turn_id,'') as turn_id,coalesce(turn_outcome,'') as turn_outcome,
       coalesce(attention,'') as attention,role,coalesce(input_revision,'') as input_revision,
       coalesce(sandbox_id,'') as sandbox_id
from dorf.agent_runs
where message_id=$1::text
`

type GetAgentRunByMessageRow struct {
	ID               string
	JobID            string
	MessageID        string
	State            spine.AgentRunState
	Harness          string
	ThreadID         string
	BaselineRecorded bool
	BaselineTurnID   string
	TurnID           string
	TurnOutcome      string
	Attention        string
	Role             string
	InputRevision    string
	SandboxID        string
}

func (q *Queries) GetAgentRunByMessage(ctx context.Context, messageID string) (GetAgentRunByMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentRunByMessage, messageID)
	var i GetAgentRunByMessageRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.MessageID,
		&i.State,
		&i.Harness,
		&i.ThreadID,
		&i.BaselineRecorded,
		&i.BaselineTurnID,
		&i.TurnID,
		&i.TurnOutcome,
		&i.Attention,
		&i.Role,
		&i.InputRevision,
		&i.SandboxID,
	)
	return i, err
}

const getAgentRunForBinding = `-- name: GetAgentRunForBinding :one
select job_id,role,state,coalesce(harness,'') as harness,
       coalesce(thread_id,'') as thread_id,coalesce(turn_id,'') as turn_id,
       coalesce(turn_outcome,'') as turn_outcome
from dorf.agent_runs
where id=$1
for update
`

type GetAgentRunForBindingRow struct {
	JobID       string
	Role        string
	State       spine.AgentRunState
	Harness     string
	ThreadID    string
	TurnID      string
	TurnOutcome string
}

func (q *Queries) GetAgentRunForBinding(ctx context.Context, runID string) (GetAgentRunForBindingRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentRunForBinding, runID)
	var i GetAgentRunForBindingRow
	err := row.Scan(
		&i.JobID,
		&i.Role,
		&i.State,
		&i.Harness,
		&i.ThreadID,
		&i.TurnID,
		&i.TurnOutcome,
	)
	return i, err
}

const getAgentRunPreparation = `-- name: GetAgentRunPreparation :one
select coalesce(harness,'') as harness,(baseline_turn_id is not null)::boolean as recorded,
       coalesce(baseline_turn_id,'') as baseline_turn_id
from dorf.agent_runs
where id=$1
`

type GetAgentRunPreparationRow struct {
	Harness        string
	Recorded       bool
	BaselineTurnID string
}

func (q *Queries) GetAgentRunPreparation(ctx context.Context, runID string) (GetAgentRunPreparationRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentRunPreparation, runID)
	var i GetAgentRunPreparationRow
	err := row.Scan(&i.Harness, &i.Recorded, &i.BaselineTurnID)
	return i, err
}

const getHarnessMutationDelivery = `-- name: GetHarnessMutationDelivery :one
select m.id as message_id,m.job_id,m.from_kind,m.from_id,m.sequence,m.input,m.admitted_at,
       m.delivery_intent,coalesce(m.steer_target_turn_id,'') as steer_target_turn_id,
       ar.id as agent_run_id,ar.job_id as agent_run_job_id,
       ar.message_id as agent_run_message_id,ar.state,
       coalesce(ar.harness,'') as harness,coalesce(ar.thread_id,'') as thread_id,
       (ar.baseline_turn_id is not null)::boolean as baseline_recorded,
       coalesce(ar.baseline_turn_id,'') as baseline_turn_id,
       coalesce(ar.turn_id,'') as turn_id,coalesce(ar.turn_outcome,'') as turn_outcome,
       coalesce(ar.attention,'') as attention,ar.role,
       coalesce(ar.input_revision,'') as input_revision
from dorf.job_messages m
join dorf.agent_runs ar on ar.message_id=m.id
where m.job_id=$1 and ar.state in ('submitting','active','uncertain')
  and ar.role in ('implement','investigate')
order by m.sequence
limit 1
`

type GetHarnessMutationDeliveryRow struct {
	MessageID         string
	JobID             string
	FromKind          spine.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	AdmittedAt        time.Time
	DeliveryIntent    spine.MessageDeliveryIntent
	SteerTargetTurnID string
	AgentRunID        string
	AgentRunJobID     string
	AgentRunMessageID string
	State             spine.AgentRunState
	Harness           string
	ThreadID          string
	BaselineRecorded  bool
	BaselineTurnID    string
	TurnID            string
	TurnOutcome       string
	Attention         string
	Role              string
	InputRevision     string
}

func (q *Queries) GetHarnessMutationDelivery(ctx context.Context, jobID string) (GetHarnessMutationDeliveryRow, error) {
	row := q.db.QueryRowContext(ctx, getHarnessMutationDelivery, jobID)
	var i GetHarnessMutationDeliveryRow
	err := row.Scan(
		&i.MessageID,
		&i.JobID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.AdmittedAt,
		&i.DeliveryIntent,
		&i.SteerTargetTurnID,
		&i.AgentRunID,
		&i.AgentRunJobID,
		&i.AgentRunMessageID,
		&i.State,
		&i.Harness,
		&i.ThreadID,
		&i.BaselineRecorded,
		&i.BaselineTurnID,
		&i.TurnID,
		&i.TurnOutcome,
		&i.Attention,
		&i.Role,
		&i.InputRevision,
	)
	return i, err
}

const implementationThreadExists = `-- name: ImplementationThreadExists :one
select exists(
    select 1 from dorf.agent_runs
    where role='implement' and harness=$1 and thread_id=$2
)
`

type ImplementationThreadExistsParams struct {
	Harness  sql.NullString
	ThreadID sql.NullString
}

func (q *Queries) ImplementationThreadExists(ctx context.Context, arg ImplementationThreadExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, implementationThreadExists, arg.Harness, arg.ThreadID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertImplementationAgentRun = `-- name: InsertImplementationAgentRun :execrows
insert into dorf.agent_runs(id,job_id,message_id,harness,thread_id,role,state,sandbox_id)
select $1,j.id,$2,prior.harness,prior.thread_id,'implement','pending',$3
from dorf.jobs j
left join lateral (
    select ar.harness,ar.thread_id
    from dorf.agent_runs ar
    left join dorf.job_messages m on m.id=ar.message_id
    where ar.job_id=j.id and ar.role='implement' and ar.thread_id is not null
    order by m.sequence desc nulls last,ar.started_at desc nulls last,ar.id desc
    limit 1
) prior on true
where j.id=$4
on conflict do nothing
`

type InsertImplementationAgentRunParams struct {
	ID        string
	MessageID string
	SandboxID string
	JobID     string
}

func (q *Queries) InsertImplementationAgentRun(ctx context.Context, arg InsertImplementationAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertImplementationAgentRun,
		arg.ID,
		arg.MessageID,
		arg.SandboxID,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertInvestigationAgentRun = `-- name: InsertInvestigationAgentRun :execrows
insert into dorf.agent_runs(
    id,job_id,message_id,role,state,input_revision,capability,sandbox_id
)
select $1,j.id,$2,'investigate','pending',
       $3,'repository-read-report',$4
from dorf.jobs j
where j.id=$5
  and j.workflow_name='codebase-investigation'
  and j.workflow_revision='1'
on conflict do nothing
`

type InsertInvestigationAgentRunParams struct {
	ID            string
	MessageID     string
	InputRevision sql.NullString
	SandboxID     string
	JobID         string
}

func (q *Queries) InsertInvestigationAgentRun(ctx context.Context, arg InsertInvestigationAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertInvestigationAgentRun,
		arg.ID,
		arg.MessageID,
		arg.InputRevision,
		arg.SandboxID,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const interruptAgentRun = `-- name: InterruptAgentRun :execrows
update dorf.agent_runs
set state='interrupted',
    turn_outcome=case when turn_id is null then null else 'interrupted' end,
    attention=$1::text,
    finished_at=case when started_at is null then null else coalesce(finished_at,clock_timestamp()) end
where id=$2 and state in ('pending','submitting','active','uncertain')
`

type InterruptAgentRunParams struct {
	Reason string
	RunID  string
}

func (q *Queries) InterruptAgentRun(ctx context.Context, arg InterruptAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptAgentRun, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listImplementationThreadBindings = `-- name: ListImplementationThreadBindings :many
select harness,thread_id
from dorf.agent_runs
where job_id=$1 and role='implement' and thread_id is not null
order by id
`

type ListImplementationThreadBindingsRow struct {
	Harness  sql.NullString
	ThreadID sql.NullString
}

func (q *Queries) ListImplementationThreadBindings(ctx context.Context, jobID string) ([]ListImplementationThreadBindingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listImplementationThreadBindings, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImplementationThreadBindingsRow
	for rows.Next() {
		var i ListImplementationThreadBindingsRow
		if err := rows.Scan(&i.Harness, &i.ThreadID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentRunUncertain = `-- name: MarkAgentRunUncertain :execrows
update dorf.agent_runs
set state='uncertain',attention=$1
where id=$2 and state not in ('completed','failed','interrupted')
`

type MarkAgentRunUncertainParams struct {
	Reason sql.NullString
	RunID  string
}

func (q *Queries) MarkAgentRunUncertain(ctx context.Context, arg MarkAgentRunUncertainParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAgentRunUncertain, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const prepareAgentRun = `-- name: PrepareAgentRun :execrows
update dorf.agent_runs
set state='submitting',harness=coalesce(harness,$1),
    baseline_turn_id=$2,
    attention=null,started_at=coalesce(started_at,clock_timestamp())
where id=$3 and state='pending'
  and (harness is null or harness=$1)
`

type PrepareAgentRunParams struct {
	Harness        sql.NullString
	BaselineTurnID sql.NullString
	RunID          string
}

func (q *Queries) PrepareAgentRun(ctx context.Context, arg PrepareAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, prepareAgentRun, arg.Harness, arg.BaselineTurnID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const propagateTurnOutcomeToSteers = `-- name: PropagateTurnOutcomeToSteers :exec
update dorf.agent_runs accepted
set turn_outcome=$1
from dorf.job_messages message,dorf.agent_runs source
where source.id=$2 and accepted.id<>source.id
  and accepted.job_id=source.job_id and accepted.harness=source.harness and accepted.thread_id=source.thread_id
  and accepted.message_id=message.id and message.delivery_intent='steer'
  and message.steer_target_turn_id=$3
  and accepted.turn_id=$3
  and accepted.state='completed' and accepted.turn_outcome is null
`

type PropagateTurnOutcomeToSteersParams struct {
	TurnOutcome sql.NullString
	RunID       string
	TurnID      sql.NullString
}

func (q *Queries) PropagateTurnOutcomeToSteers(ctx context.Context, arg PropagateTurnOutcomeToSteersParams) error {
	_, err := q.db.ExecContext(ctx, propagateTurnOutcomeToSteers, arg.TurnOutcome, arg.RunID, arg.TurnID)
	return err
}

const setAgentRunAttention = `-- name: SetAgentRunAttention :execrows
update dorf.agent_runs
set attention=$1
where id=$2
`

type SetAgentRunAttentionParams struct {
	Reason sql.NullString
	RunID  string
}

func (q *Queries) SetAgentRunAttention(ctx context.Context, arg SetAgentRunAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAgentRunAttention, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
