// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package dbsql

import (
	"context"
	"time"
)

const getArtifact = `-- name: GetArtifact :one
select id,job_id,name,digest,byte_size,media_type,producer,agent_run_id,created_at
from dorf.artifacts
where id=$1
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (DorfArtifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i DorfArtifact
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Digest,
		&i.ByteSize,
		&i.MediaType,
		&i.Producer,
		&i.AgentRunID,
		&i.CreatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :exec
insert into dorf.artifacts(
    id,job_id,name,digest,byte_size,media_type,producer,agent_run_id,created_at
) values(
    $1,$2,$3,$4,
    $5,$6,$7,
    $8,$9
)
on conflict(id) do nothing
`

type InsertArtifactParams struct {
	ID         string
	JobID      string
	Name       string
	Digest     string
	ByteSize   int64
	MediaType  string
	Producer   string
	AgentRunID string
	CreatedAt  time.Time
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertArtifact,
		arg.ID,
		arg.JobID,
		arg.Name,
		arg.Digest,
		arg.ByteSize,
		arg.MediaType,
		arg.Producer,
		arg.AgentRunID,
		arg.CreatedAt,
	)
	return err
}

const listArtifacts = `-- name: ListArtifacts :many
select id,job_id,name,digest,byte_size,media_type,producer,agent_run_id,created_at
from dorf.artifacts
where job_id=$1
order by name,id
`

func (q *Queries) ListArtifacts(ctx context.Context, jobID string) ([]DorfArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifacts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DorfArtifact
	for rows.Next() {
		var i DorfArtifact
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Digest,
			&i.ByteSize,
			&i.MediaType,
			&i.Producer,
			&i.AgentRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
