// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"
)

const bindCheckpointBranchThread = `-- name: BindCheckpointBranchThread :execrows
update dorf.sessions set thread_id=$1,native_revision=$2
where id=$3 and thread_id is null and native_revision=0
  and native_pending_input_id is null and native_pending_turn_id is null
`

type BindCheckpointBranchThreadParams struct {
	ThreadID       sql.NullString
	NativeRevision int64
	SessionID      string
}

func (q *Queries) BindCheckpointBranchThread(ctx context.Context, arg BindCheckpointBranchThreadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindCheckpointBranchThread, arg.ThreadID, arg.NativeRevision, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const checkpointBranchFilePreparationAllowed = `-- name: CheckpointBranchFilePreparationAllowed :one
select exists(
    select 1 from dorf.sandbox_branches b
    join dorf.sessions s on s.id=b.destination_session_id
    join dorf.sandbox_delivery_holds h on h.id=b.id
    where b.destination_sandbox_id=$1
      and b.restored_at is not null and b.release_requested_at is null
      and b.ready_at is null and h.released_at is null
      and s.admission_open and s.cleanup_state='pending'
)::boolean
`

func (q *Queries) CheckpointBranchFilePreparationAllowed(ctx context.Context, sandboxID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkpointBranchFilePreparationAllowed, sandboxID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const finishCheckpointBranch = `-- name: FinishCheckpointBranch :execrows
with ready as (
    update dorf.sandbox_branches b
    set ready_at=coalesce(ready_at,clock_timestamp())
    where b.id=$1 and b.restored_at is not null and b.release_requested_at is not null
    returning b.id,b.destination_sandbox_id
)
update dorf.sandbox_delivery_holds h
set released_at=coalesce(released_at,clock_timestamp())
from ready
where h.id=ready.id and h.sandbox_id=ready.destination_sandbox_id
  and h.reason='checkpoint_branch'
`

func (q *Queries) FinishCheckpointBranch(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishCheckpointBranch, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCheckpointBranchByID = `-- name: GetCheckpointBranchByID :one
select b.id, b.source_session_id, b.destination_session_id, b.destination_sandbox_id, b.checkpoint_repository, b.checkpoint_snapshot_id, b.thread_id, b.requested_at, b.restored_at, b.release_requested_at, b.ready_at,h.released_at
from dorf.sandbox_branches b
join dorf.sandbox_delivery_holds h on h.id=b.id
where b.id=$1
`

type GetCheckpointBranchByIDRow struct {
	ID                   string
	SourceSessionID      string
	DestinationSessionID string
	DestinationSandboxID string
	CheckpointRepository string
	CheckpointSnapshotID string
	ThreadID             string
	RequestedAt          time.Time
	RestoredAt           sql.NullTime
	ReleaseRequestedAt   sql.NullTime
	ReadyAt              sql.NullTime
	ReleasedAt           sql.NullTime
}

func (q *Queries) GetCheckpointBranchByID(ctx context.Context, id string) (GetCheckpointBranchByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCheckpointBranchByID, id)
	var i GetCheckpointBranchByIDRow
	err := row.Scan(
		&i.ID,
		&i.SourceSessionID,
		&i.DestinationSessionID,
		&i.DestinationSandboxID,
		&i.CheckpointRepository,
		&i.CheckpointSnapshotID,
		&i.ThreadID,
		&i.RequestedAt,
		&i.RestoredAt,
		&i.ReleaseRequestedAt,
		&i.ReadyAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getCheckpointBranchBySession = `-- name: GetCheckpointBranchBySession :one
select b.id, b.source_session_id, b.destination_session_id, b.destination_sandbox_id, b.checkpoint_repository, b.checkpoint_snapshot_id, b.thread_id, b.requested_at, b.restored_at, b.release_requested_at, b.ready_at,h.released_at
from dorf.sandbox_branches b
join dorf.sandbox_delivery_holds h on h.id=b.id
where b.destination_session_id=$1
`

type GetCheckpointBranchBySessionRow struct {
	ID                   string
	SourceSessionID      string
	DestinationSessionID string
	DestinationSandboxID string
	CheckpointRepository string
	CheckpointSnapshotID string
	ThreadID             string
	RequestedAt          time.Time
	RestoredAt           sql.NullTime
	ReleaseRequestedAt   sql.NullTime
	ReadyAt              sql.NullTime
	ReleasedAt           sql.NullTime
}

func (q *Queries) GetCheckpointBranchBySession(ctx context.Context, destinationSessionID string) (GetCheckpointBranchBySessionRow, error) {
	row := q.db.QueryRowContext(ctx, getCheckpointBranchBySession, destinationSessionID)
	var i GetCheckpointBranchBySessionRow
	err := row.Scan(
		&i.ID,
		&i.SourceSessionID,
		&i.DestinationSessionID,
		&i.DestinationSandboxID,
		&i.CheckpointRepository,
		&i.CheckpointSnapshotID,
		&i.ThreadID,
		&i.RequestedAt,
		&i.RestoredAt,
		&i.ReleaseRequestedAt,
		&i.ReadyAt,
		&i.ReleasedAt,
	)
	return i, err
}

const insertCheckpointBranch = `-- name: InsertCheckpointBranch :exec
insert into dorf.sandbox_branches(
    id,source_session_id,destination_session_id,destination_sandbox_id,
    checkpoint_repository,checkpoint_snapshot_id,thread_id
) values (
    $1,$2,$3,
    $4,$5,
    $6,$7
)
`

type InsertCheckpointBranchParams struct {
	ID                   string
	SourceSessionID      string
	DestinationSessionID string
	DestinationSandboxID string
	CheckpointRepository string
	CheckpointSnapshotID string
	ThreadID             string
}

func (q *Queries) InsertCheckpointBranch(ctx context.Context, arg InsertCheckpointBranchParams) error {
	_, err := q.db.ExecContext(ctx, insertCheckpointBranch,
		arg.ID,
		arg.SourceSessionID,
		arg.DestinationSessionID,
		arg.DestinationSandboxID,
		arg.CheckpointRepository,
		arg.CheckpointSnapshotID,
		arg.ThreadID,
	)
	return err
}

const insertCheckpointBranchHold = `-- name: InsertCheckpointBranchHold :exec
insert into dorf.sandbox_delivery_holds(id,sandbox_id,reason)
values($1,$2,'checkpoint_branch')
`

type InsertCheckpointBranchHoldParams struct {
	ID                   string
	DestinationSandboxID string
}

func (q *Queries) InsertCheckpointBranchHold(ctx context.Context, arg InsertCheckpointBranchHoldParams) error {
	_, err := q.db.ExecContext(ctx, insertCheckpointBranchHold, arg.ID, arg.DestinationSandboxID)
	return err
}

const recordCheckpointBranchRestored = `-- name: RecordCheckpointBranchRestored :execrows
update dorf.sandbox_branches
set restored_at=coalesce(restored_at,clock_timestamp())
where id=$1 and ready_at is null
`

func (q *Queries) RecordCheckpointBranchRestored(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordCheckpointBranchRestored, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestCheckpointBranchRelease = `-- name: RequestCheckpointBranchRelease :execrows
update dorf.sandbox_branches
set release_requested_at=coalesce(release_requested_at,clock_timestamp())
where id=$1 and restored_at is not null
`

func (q *Queries) RequestCheckpointBranchRelease(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestCheckpointBranchRelease, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
