// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks_evidence.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"
)

const getEvidenceIdentity = `-- name: GetEvidenceIdentity :one
select job_id,digest,byte_size,media_type,producer,kind,
       coalesce(action_id,'') as action_id,coalesce(agent_run_id,'') as agent_run_id,
       coalesce(revision,'') as revision,started_at,finished_at
from dorf.evidence
where id=$1
`

type GetEvidenceIdentityRow struct {
	JobID      string
	Digest     string
	ByteSize   int64
	MediaType  string
	Producer   string
	Kind       string
	ActionID   string
	AgentRunID string
	Revision   string
	StartedAt  time.Time
	FinishedAt time.Time
}

func (q *Queries) GetEvidenceIdentity(ctx context.Context, id string) (GetEvidenceIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getEvidenceIdentity, id)
	var i GetEvidenceIdentityRow
	err := row.Scan(
		&i.JobID,
		&i.Digest,
		&i.ByteSize,
		&i.MediaType,
		&i.Producer,
		&i.Kind,
		&i.ActionID,
		&i.AgentRunID,
		&i.Revision,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertEvidence = `-- name: InsertEvidence :exec
insert into dorf.evidence(
    id,job_id,digest,byte_size,media_type,producer,kind,
    action_id,agent_run_id,revision,started_at,finished_at
)
values(
    $1,$2,$3,$4,
    $5,$6,$7,
    nullif($8::text,''),nullif($9::text,''),
    nullif($10::text,''),$11,$12
)
on conflict(id) do nothing
`

type InsertEvidenceParams struct {
	ID         string
	JobID      string
	Digest     string
	ByteSize   int64
	MediaType  string
	Producer   string
	Kind       string
	ActionID   string
	AgentRunID string
	Revision   string
	StartedAt  sql.NullTime
	FinishedAt sql.NullTime
}

func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, insertEvidence,
		arg.ID,
		arg.JobID,
		arg.Digest,
		arg.ByteSize,
		arg.MediaType,
		arg.Producer,
		arg.Kind,
		arg.ActionID,
		arg.AgentRunID,
		arg.Revision,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const listEvidence = `-- name: ListEvidence :many
select id,digest,byte_size,media_type,producer,kind,
       coalesce(action_id,'') as action_id,coalesce(agent_run_id,'') as agent_run_id,
       coalesce(revision,'') as revision,started_at,finished_at
from dorf.evidence
where job_id=$1
order by created_at,id
`

type ListEvidenceRow struct {
	ID         string
	Digest     string
	ByteSize   int64
	MediaType  string
	Producer   string
	Kind       string
	ActionID   string
	AgentRunID string
	Revision   string
	StartedAt  time.Time
	FinishedAt time.Time
}

func (q *Queries) ListEvidence(ctx context.Context, jobID string) ([]ListEvidenceRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvidence, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEvidenceRow
	for rows.Next() {
		var i ListEvidenceRow
		if err := rows.Scan(
			&i.ID,
			&i.Digest,
			&i.ByteSize,
			&i.MediaType,
			&i.Producer,
			&i.Kind,
			&i.ActionID,
			&i.AgentRunID,
			&i.Revision,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
