// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoints.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"
)

const getCheckpointBoundary = `-- name: GetCheckpointBoundary :one
select
    j.id as session_id,
    s.id as sandbox_id,
    s.active_resource_id as resource_id,
    j.sandbox_profile as profile_name,
    j.sandbox_profile_revision as profile_revision,
    coalesce((
        select u.id
        from dorf.sandbox_upgrades u
        where u.sandbox_id=s.id and u.finished_at is not null and u.rollback_at is null
        order by u.finished_at desc,u.id desc
        limit 1
    ),'')::text as effective_upgrade_id,
    coalesce(j.sandbox_last_active_at,j.admitted_at) as last_activity_at,
    coalesce((
        select max(m.sequence)
        from dorf.agent_runs ar
        join dorf.session_messages m on m.id=ar.message_id
        where ar.sandbox_id=s.id
    ),0)::bigint as message_sequence,
    coalesce((
        select max(m.sequence)
        from dorf.agent_runs ar
        join dorf.session_messages m on m.id=ar.message_id
        where ar.sandbox_id=s.id and ar.state='completed'
          and ar.turn_id is not null and ar.turn_outcome='completed'
    ),0)::bigint as completed_turn_sequence,
    (select count(*) from dorf.sandbox_delivery_holds h where h.sandbox_id=s.id)::bigint
        as delivery_hold_count,
    (
        (j.sandbox_last_active_at is not null or $1::boolean)
        and r.provider_id is not null
        and r.deleted_at is null
        and not exists (
            select 1 from dorf.agent_runs ar
            where ar.sandbox_id=s.id and ar.state not in ('completed','failed','interrupted')
        )
        and not exists (
            select 1 from dorf.sandbox_delivery_holds h
            where h.sandbox_id=s.id and h.released_at is null
        )
        and (
            (not $1::boolean and j.admission_open and j.cleanup_state='pending')
            or
            ($1::boolean and not j.admission_open and j.cleanup_state in ('requested','scheduled'))
        )
    )::boolean as eligible
from dorf.sandboxes s
join dorf.sessions j on j.id=s.session_id
join dorf.sandbox_resources r on r.sandbox_id=s.id and r.id=s.active_resource_id
where s.id=$2
`

type GetCheckpointBoundaryParams struct {
	Cleanup   bool
	SandboxID string
}

type GetCheckpointBoundaryRow struct {
	SessionID             string
	SandboxID             string
	ResourceID            string
	ProfileName           string
	ProfileRevision       string
	EffectiveUpgradeID    string
	LastActivityAt        time.Time
	MessageSequence       int64
	CompletedTurnSequence int64
	DeliveryHoldCount     int64
	Eligible              bool
}

func (q *Queries) GetCheckpointBoundary(ctx context.Context, arg GetCheckpointBoundaryParams) (GetCheckpointBoundaryRow, error) {
	row := q.db.QueryRowContext(ctx, getCheckpointBoundary, arg.Cleanup, arg.SandboxID)
	var i GetCheckpointBoundaryRow
	err := row.Scan(
		&i.SessionID,
		&i.SandboxID,
		&i.ResourceID,
		&i.ProfileName,
		&i.ProfileRevision,
		&i.EffectiveUpgradeID,
		&i.LastActivityAt,
		&i.MessageSequence,
		&i.CompletedTurnSequence,
		&i.DeliveryHoldCount,
		&i.Eligible,
	)
	return i, err
}

const getLastSandboxCheckpoint = `-- name: GetLastSandboxCheckpoint :one
select c.repository, c.snapshot_id, c.sandbox_id, c.resource_id, c.profile_name, c.profile_revision, c.effective_upgrade_id, c.last_activity_at, c.message_sequence, c.completed_turn_sequence, c.delivery_hold_count, c.cleanup, c.published_at, c.publication_sequence,s.session_id
from dorf.sandbox_checkpoints c
join dorf.sandboxes s on s.id=c.sandbox_id
where c.sandbox_id=$1
order by c.publication_sequence desc
limit 1
`

type GetLastSandboxCheckpointRow struct {
	Repository            string
	SnapshotID            string
	SandboxID             string
	ResourceID            string
	ProfileName           string
	ProfileRevision       string
	EffectiveUpgradeID    sql.NullString
	LastActivityAt        time.Time
	MessageSequence       int64
	CompletedTurnSequence int64
	DeliveryHoldCount     int64
	Cleanup               bool
	PublishedAt           time.Time
	PublicationSequence   sql.NullInt64
	SessionID             string
}

func (q *Queries) GetLastSandboxCheckpoint(ctx context.Context, sandboxID string) (GetLastSandboxCheckpointRow, error) {
	row := q.db.QueryRowContext(ctx, getLastSandboxCheckpoint, sandboxID)
	var i GetLastSandboxCheckpointRow
	err := row.Scan(
		&i.Repository,
		&i.SnapshotID,
		&i.SandboxID,
		&i.ResourceID,
		&i.ProfileName,
		&i.ProfileRevision,
		&i.EffectiveUpgradeID,
		&i.LastActivityAt,
		&i.MessageSequence,
		&i.CompletedTurnSequence,
		&i.DeliveryHoldCount,
		&i.Cleanup,
		&i.PublishedAt,
		&i.PublicationSequence,
		&i.SessionID,
	)
	return i, err
}

const getSandboxCheckpointByReference = `-- name: GetSandboxCheckpointByReference :one
select c.repository, c.snapshot_id, c.sandbox_id, c.resource_id, c.profile_name, c.profile_revision, c.effective_upgrade_id, c.last_activity_at, c.message_sequence, c.completed_turn_sequence, c.delivery_hold_count, c.cleanup, c.published_at, c.publication_sequence,s.session_id
from dorf.sandbox_checkpoints c
join dorf.sandboxes s on s.id=c.sandbox_id
where c.repository=$1 and c.snapshot_id=$2
`

type GetSandboxCheckpointByReferenceParams struct {
	Repository string
	SnapshotID string
}

type GetSandboxCheckpointByReferenceRow struct {
	Repository            string
	SnapshotID            string
	SandboxID             string
	ResourceID            string
	ProfileName           string
	ProfileRevision       string
	EffectiveUpgradeID    sql.NullString
	LastActivityAt        time.Time
	MessageSequence       int64
	CompletedTurnSequence int64
	DeliveryHoldCount     int64
	Cleanup               bool
	PublishedAt           time.Time
	PublicationSequence   sql.NullInt64
	SessionID             string
}

func (q *Queries) GetSandboxCheckpointByReference(ctx context.Context, arg GetSandboxCheckpointByReferenceParams) (GetSandboxCheckpointByReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, getSandboxCheckpointByReference, arg.Repository, arg.SnapshotID)
	var i GetSandboxCheckpointByReferenceRow
	err := row.Scan(
		&i.Repository,
		&i.SnapshotID,
		&i.SandboxID,
		&i.ResourceID,
		&i.ProfileName,
		&i.ProfileRevision,
		&i.EffectiveUpgradeID,
		&i.LastActivityAt,
		&i.MessageSequence,
		&i.CompletedTurnSequence,
		&i.DeliveryHoldCount,
		&i.Cleanup,
		&i.PublishedAt,
		&i.PublicationSequence,
		&i.SessionID,
	)
	return i, err
}

const insertSandboxCheckpoint = `-- name: InsertSandboxCheckpoint :execrows
insert into dorf.sandbox_checkpoints(
    repository,snapshot_id,sandbox_id,resource_id,profile_name,profile_revision,
    effective_upgrade_id,last_activity_at,message_sequence,completed_turn_sequence,
    delivery_hold_count,cleanup
)
values(
    $1,$2,$3,$4,
    $5,$6,nullif($7::text,''),
    $8,$9,$10,
    $11,$12
)
on conflict do nothing
`

type InsertSandboxCheckpointParams struct {
	Repository            string
	SnapshotID            string
	SandboxID             string
	ResourceID            string
	ProfileName           string
	ProfileRevision       string
	EffectiveUpgradeID    string
	LastActivityAt        time.Time
	MessageSequence       int64
	CompletedTurnSequence int64
	DeliveryHoldCount     int64
	Cleanup               bool
}

func (q *Queries) InsertSandboxCheckpoint(ctx context.Context, arg InsertSandboxCheckpointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSandboxCheckpoint,
		arg.Repository,
		arg.SnapshotID,
		arg.SandboxID,
		arg.ResourceID,
		arg.ProfileName,
		arg.ProfileRevision,
		arg.EffectiveUpgradeID,
		arg.LastActivityAt,
		arg.MessageSequence,
		arg.CompletedTurnSequence,
		arg.DeliveryHoldCount,
		arg.Cleanup,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listIdleCheckpointSandboxIDs = `-- name: ListIdleCheckpointSandboxIDs :many
select s.id
from dorf.sandboxes s
join dorf.sessions j on j.id=s.session_id
join dorf.sandbox_resources r on r.sandbox_id=s.id and r.id=s.active_resource_id
where j.admission_open and j.cleanup_state='pending'
  and j.sandbox_last_active_at is not null
  and j.sandbox_last_active_at <= clock_timestamp()-make_interval(secs => $1::double precision)
  and r.provider_id is not null and r.deleted_at is null
  and exists (
      select 1 from dorf.agent_runs ar
      where ar.sandbox_id=s.id and ar.state='completed'
        and ar.turn_id is not null and ar.turn_outcome='completed'
  )
  and not exists (
      select 1 from dorf.agent_runs ar
      where ar.sandbox_id=s.id and ar.state not in ('completed','failed','interrupted')
  )
  and not exists (
      select 1 from dorf.sandbox_delivery_holds h
      where h.sandbox_id=s.id and h.released_at is null
  )
  and not coalesce((
      select
          c.resource_id=s.active_resource_id
          and c.profile_name=j.sandbox_profile
          and c.profile_revision=j.sandbox_profile_revision
          and c.effective_upgrade_id is not distinct from (
              select u.id
              from dorf.sandbox_upgrades u
              where u.sandbox_id=s.id and u.finished_at is not null and u.rollback_at is null
              order by u.finished_at desc,u.id desc
              limit 1
          )
          and c.last_activity_at=j.sandbox_last_active_at
          and c.message_sequence=coalesce((
              select max(m.sequence)
              from dorf.agent_runs ar
              join dorf.session_messages m on m.id=ar.message_id
              where ar.sandbox_id=s.id
          ),0)
          and c.completed_turn_sequence=coalesce((
              select max(m.sequence)
              from dorf.agent_runs ar
              join dorf.session_messages m on m.id=ar.message_id
              where ar.sandbox_id=s.id and ar.state='completed'
                and ar.turn_id is not null and ar.turn_outcome='completed'
          ),0)
          and c.delivery_hold_count=(
              select count(*) from dorf.sandbox_delivery_holds h where h.sandbox_id=s.id
          )
          and not c.cleanup
      from dorf.sandbox_checkpoints c
      where c.sandbox_id=s.id
      order by c.publication_sequence desc
      limit 1
  ),false)
order by j.sandbox_last_active_at,s.id
limit 100
`

func (q *Queries) ListIdleCheckpointSandboxIDs(ctx context.Context, seconds float64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listIdleCheckpointSandboxIDs, seconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxCheckpoints = `-- name: ListSandboxCheckpoints :many
select c.repository, c.snapshot_id, c.sandbox_id, c.resource_id, c.profile_name, c.profile_revision, c.effective_upgrade_id, c.last_activity_at, c.message_sequence, c.completed_turn_sequence, c.delivery_hold_count, c.cleanup, c.published_at, c.publication_sequence,s.session_id
from dorf.sandbox_checkpoints c
join dorf.sandboxes s on s.id=c.sandbox_id
where c.sandbox_id=$1
order by c.publication_sequence desc
`

type ListSandboxCheckpointsRow struct {
	Repository            string
	SnapshotID            string
	SandboxID             string
	ResourceID            string
	ProfileName           string
	ProfileRevision       string
	EffectiveUpgradeID    sql.NullString
	LastActivityAt        time.Time
	MessageSequence       int64
	CompletedTurnSequence int64
	DeliveryHoldCount     int64
	Cleanup               bool
	PublishedAt           time.Time
	PublicationSequence   sql.NullInt64
	SessionID             string
}

func (q *Queries) ListSandboxCheckpoints(ctx context.Context, sandboxID string) ([]ListSandboxCheckpointsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSandboxCheckpoints, sandboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSandboxCheckpointsRow
	for rows.Next() {
		var i ListSandboxCheckpointsRow
		if err := rows.Scan(
			&i.Repository,
			&i.SnapshotID,
			&i.SandboxID,
			&i.ResourceID,
			&i.ProfileName,
			&i.ProfileRevision,
			&i.EffectiveUpgradeID,
			&i.LastActivityAt,
			&i.MessageSequence,
			&i.CompletedTurnSequence,
			&i.DeliveryHoldCount,
			&i.Cleanup,
			&i.PublishedAt,
			&i.PublicationSequence,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
