// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup.sql

package dbsql

import (
	"context"

	"github.com/aphronio/dorf/internal/spine"
)

const completeCleanup = `-- name: CompleteCleanup :execrows
update dorf.jobs
set cleanup_state='complete',cleanup_attention=null,workflow_attention=null,
    cleaned_at=coalesce(cleaned_at,clock_timestamp())
where id=$1 and cleanup_state='scheduled'
`

func (q *Queries) CompleteCleanup(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeCleanup, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUnsettledJobResources = `-- name: CountUnsettledJobResources :one
select count(*)
from dorf.sandboxes s
left join dorf.routes r on r.sandbox_id=s.id
where s.job_id=$1
  and (s.state<>'deleted' or (r.id is not null and r.state<>'revoked'))
`

func (q *Queries) CountUnsettledJobResources(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnsettledJobResources, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCleanupJobForUpdate = `-- name: GetCleanupJobForUpdate :one
select admission_open,cleanup_state,coalesce(cleanup_task_id,'') as cleanup_task_id,
       coalesce(workflow_attention,'') as workflow_attention
from dorf.jobs
where id=$1
for update
`

type GetCleanupJobForUpdateRow struct {
	AdmissionOpen     bool
	CleanupState      spine.CleanupState
	CleanupTaskID     string
	WorkflowAttention string
}

func (q *Queries) GetCleanupJobForUpdate(ctx context.Context, jobID string) (GetCleanupJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getCleanupJobForUpdate, jobID)
	var i GetCleanupJobForUpdateRow
	err := row.Scan(
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.CleanupTaskID,
		&i.WorkflowAttention,
	)
	return i, err
}

const getResourceStates = `-- name: GetResourceStates :one
select s.state as sandbox_state,coalesce(r.state,'') as route_state
from dorf.sandboxes s
left join dorf.routes r on r.sandbox_id=s.id
where s.id=$1 and s.job_id=$2
`

type GetResourceStatesParams struct {
	SandboxID string
	JobID     string
}

type GetResourceStatesRow struct {
	SandboxState string
	RouteState   string
}

func (q *Queries) GetResourceStates(ctx context.Context, arg GetResourceStatesParams) (GetResourceStatesRow, error) {
	row := q.db.QueryRowContext(ctx, getResourceStates, arg.SandboxID, arg.JobID)
	var i GetResourceStatesRow
	err := row.Scan(&i.SandboxState, &i.RouteState)
	return i, err
}
