// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup.sql

package dbsql

import (
	"context"

	"github.com/aphronio/dorf/internal/core"
)

const completeCleanup = `-- name: CompleteCleanup :execrows
update dorf.jobs
set cleanup_state='complete',cleanup_attention=null,
    workflow_attention=null,workflow_attention_source=null,workflow_attention_at=null,
    cleaned_at=coalesce(cleaned_at,clock_timestamp())
where id=$1 and cleanup_state='scheduled'
`

func (q *Queries) CompleteCleanup(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeCleanup, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUnsettledSandboxCleanupActions = `-- name: CountUnsettledSandboxCleanupActions :one
select count(*)
from dorf.sandboxes s
where s.job_id=$1
  and (
    not exists(select 1 from dorf.actions a where a.job_id=s.job_id and a.kind='provider-route-revoke' and a.scope_key=s.id and a.state='succeeded')
    or not exists(select 1 from dorf.actions a where a.job_id=s.job_id and a.kind='sandbox-delete' and a.scope_key=s.id and a.state='succeeded')
  )
`

func (q *Queries) CountUnsettledSandboxCleanupActions(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnsettledSandboxCleanupActions, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCleanupJobForUpdate = `-- name: GetCleanupJobForUpdate :one
select admission_open,cleanup_state,
       coalesce((select task_id from dorf.job_tasks where job_id=dorf.jobs.id order by sequence desc limit 1),'') as current_task_id,
       coalesce(cleanup_attention,'') as cleanup_attention
from dorf.jobs
where id=$1
for update
`

type GetCleanupJobForUpdateRow struct {
	AdmissionOpen    bool
	CleanupState     core.CleanupState
	CurrentTaskID    interface{}
	CleanupAttention string
}

func (q *Queries) GetCleanupJobForUpdate(ctx context.Context, jobID string) (GetCleanupJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getCleanupJobForUpdate, jobID)
	var i GetCleanupJobForUpdateRow
	err := row.Scan(
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.CurrentTaskID,
		&i.CleanupAttention,
	)
	return i, err
}

const listCleanupRequests = `-- name: ListCleanupRequests :many
select id from dorf.jobs where not admission_open and cleanup_state='requested' order by id
`

func (q *Queries) ListCleanupRequests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCleanupRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestCleanup = `-- name: RequestCleanup :execrows
update dorf.jobs
set admission_open=false,
    cleanup_state=case when cleanup_state='pending' then 'requested' else cleanup_state end
where id=$1 and cleanup_state in ('pending','requested')
`

func (q *Queries) RequestCleanup(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestCleanup, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
