// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control_auth.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"
)

const authenticateControlClient = `-- name: AuthenticateControlClient :one
select id,name,credential_expires_at
from dorf.control_clients
where credential_digest=$1
  and revoked_at is null
  and credential_expires_at>clock_timestamp()
`

type AuthenticateControlClientRow struct {
	ID                  string
	Name                string
	CredentialExpiresAt time.Time
}

func (q *Queries) AuthenticateControlClient(ctx context.Context, credentialDigest []byte) (AuthenticateControlClientRow, error) {
	row := q.db.QueryRowContext(ctx, authenticateControlClient, credentialDigest)
	var i AuthenticateControlClientRow
	err := row.Scan(&i.ID, &i.Name, &i.CredentialExpiresAt)
	return i, err
}

const bindControlEnrollment = `-- name: BindControlEnrollment :exec
update dorf.control_enrollments
set consumed_at=clock_timestamp(),client_id=$1
where id=$2 and consumed_at is null
`

type BindControlEnrollmentParams struct {
	ClientID sql.NullString
	ID       string
}

func (q *Queries) BindControlEnrollment(ctx context.Context, arg BindControlEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, bindControlEnrollment, arg.ClientID, arg.ID)
	return err
}

const getControlClient = `-- name: GetControlClient :one
with db_time as (select clock_timestamp() as now)
select id,name,
       case
           when revoked_at is not null then 'revoked'
           when credential_expires_at<=db_time.now then 'expired'
           else 'active'
       end as state,
       created_at,credential_expires_at as expires_at,revoked_at
from dorf.control_clients cross join db_time
where id=$1
`

type GetControlClientRow struct {
	ID        string
	Name      string
	State     string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) GetControlClient(ctx context.Context, id string) (GetControlClientRow, error) {
	row := q.db.QueryRowContext(ctx, getControlClient, id)
	var i GetControlClientRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getControlEnrollmentForUpdate = `-- name: GetControlEnrollmentForUpdate :one
select secret_digest,expires_at>clock_timestamp() as active,consumed_at,client_id
from dorf.control_enrollments
where id=$1
for update
`

type GetControlEnrollmentForUpdateRow struct {
	SecretDigest []byte
	Active       bool
	ConsumedAt   sql.NullTime
	ClientID     sql.NullString
}

func (q *Queries) GetControlEnrollmentForUpdate(ctx context.Context, id string) (GetControlEnrollmentForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getControlEnrollmentForUpdate, id)
	var i GetControlEnrollmentForUpdateRow
	err := row.Scan(
		&i.SecretDigest,
		&i.Active,
		&i.ConsumedAt,
		&i.ClientID,
	)
	return i, err
}

const insertControlClient = `-- name: InsertControlClient :one
with db_time as (select clock_timestamp() as now)
insert into dorf.control_clients(id,name,credential_digest,credential_expires_at,created_at)
select $1,$2,$3,now + $4::bigint * interval '1 microsecond',now
from db_time
returning id,name,credential_expires_at
`

type InsertControlClientParams struct {
	ID                   string
	Name                 string
	CredentialDigest     []byte
	LifetimeMicroseconds int64
}

type InsertControlClientRow struct {
	ID                  string
	Name                string
	CredentialExpiresAt time.Time
}

func (q *Queries) InsertControlClient(ctx context.Context, arg InsertControlClientParams) (InsertControlClientRow, error) {
	row := q.db.QueryRowContext(ctx, insertControlClient,
		arg.ID,
		arg.Name,
		arg.CredentialDigest,
		arg.LifetimeMicroseconds,
	)
	var i InsertControlClientRow
	err := row.Scan(&i.ID, &i.Name, &i.CredentialExpiresAt)
	return i, err
}

const insertControlEnrollment = `-- name: InsertControlEnrollment :one
with db_time as (select clock_timestamp() as now)
insert into dorf.control_enrollments(id,secret_digest,expires_at,created_at)
select $1,$2,now + $3::bigint * interval '1 microsecond',now
from db_time
returning expires_at
`

type InsertControlEnrollmentParams struct {
	ID                   string
	SecretDigest         []byte
	LifetimeMicroseconds int64
}

func (q *Queries) InsertControlEnrollment(ctx context.Context, arg InsertControlEnrollmentParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, insertControlEnrollment, arg.ID, arg.SecretDigest, arg.LifetimeMicroseconds)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const listControlClients = `-- name: ListControlClients :many
with db_time as (select clock_timestamp() as now)
select id,name,
       case
           when revoked_at is not null then 'revoked'
           when credential_expires_at<=db_time.now then 'expired'
           else 'active'
       end as state,
       created_at,credential_expires_at as expires_at,revoked_at
from dorf.control_clients cross join db_time
order by created_at desc,id desc
`

type ListControlClientsRow struct {
	ID        string
	Name      string
	State     string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) ListControlClients(ctx context.Context) ([]ListControlClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listControlClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlClientsRow
	for rows.Next() {
		var i ListControlClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeControlClient = `-- name: RevokeControlClient :one
update dorf.control_clients
set revoked_at=coalesce(revoked_at,clock_timestamp())
where id=$1
returning id,name,'revoked'::text as state,created_at,
          credential_expires_at as expires_at,revoked_at
`

type RevokeControlClientRow struct {
	ID        string
	Name      string
	State     string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) RevokeControlClient(ctx context.Context, id string) (RevokeControlClientRow, error) {
	row := q.db.QueryRowContext(ctx, revokeControlClient, id)
	var i RevokeControlClientRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
