// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package dbsql

import (
	"context"

	"github.com/aphronio/dorf/internal/spine"
)

const nextDeliveryCandidate = `-- name: NextDeliveryCandidate :one
with current_turn_start as (
    select m.id as message_id,ar.turn_id,ar.state
    from dorf.job_messages m join dorf.agent_runs ar on ar.message_id=m.id
    where m.job_id=$1 and ar.turn_id is not null
      and ar.role='implement'
      and (m.delivery_intent='follow' or ar.turn_id<>m.steer_target_turn_id)
      and ar.state in ('active','uncertain')
    order by m.sequence limit 1
), candidate as (
    select steer.id as message_id,0 as priority,steer.sequence
    from current_turn_start active
    join dorf.job_messages steer on steer.job_id=$1 and steer.delivery_intent='steer'
      and steer.steer_target_turn_id=active.turn_id
    join dorf.agent_runs steer_run on steer_run.message_id=steer.id
    where active.state='active' and steer_run.role='implement'
      and steer_run.state='pending' and steer_run.turn_id is null
    union all
    select message_id,1,0 from current_turn_start
    union all
    select m.id,2,m.sequence
    from dorf.job_messages m join dorf.agent_runs ar on ar.message_id=m.id
    where m.job_id=$1 and ar.role='implement'
      and ar.state='pending' and ar.turn_id is null
      and not exists(select 1 from current_turn_start)
)
select m.id,m.job_id,m.from_kind,m.from_id,m.sequence,m.input,m.delivery_intent,
       coalesce(m.steer_target_turn_id,'') as steer_target_turn_id
from candidate c join dorf.job_messages m on m.id=c.message_id
order by c.priority,c.sequence limit 1
`

type NextDeliveryCandidateRow struct {
	ID                string
	JobID             string
	FromKind          spine.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	DeliveryIntent    spine.MessageDeliveryIntent
	SteerTargetTurnID string
}

func (q *Queries) NextDeliveryCandidate(ctx context.Context, jobID string) (NextDeliveryCandidateRow, error) {
	row := q.db.QueryRowContext(ctx, nextDeliveryCandidate, jobID)
	var i NextDeliveryCandidateRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.DeliveryIntent,
		&i.SteerTargetTurnID,
	)
	return i, err
}
