// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package dbsql

import (
	"context"
	"time"

	"github.com/aphronio/dorf/internal/core"
)

const nextAgentMessage = `-- name: NextAgentMessage :one
with current_turn_start as (
    select m.id as message_id,ar.turn_id,ar.state
    from dorf.job_messages m join dorf.agent_runs ar on ar.message_id=m.id
    where m.job_id=$1 and ar.turn_id is not null
      and m.delivery_intent='follow'
      and ar.state in ('active','uncertain')
    order by m.sequence limit 1
), current_unbound_mutation as (
    select m.id as message_id,m.sequence
    from dorf.job_messages m join dorf.agent_runs ar on ar.message_id=m.id
    where m.job_id=$1 and m.delivery_intent='follow'
      and ar.turn_id is null and ar.state in ('submitting','uncertain')
    order by m.sequence limit 1
), unsettled_steer as (
    select m.id as message_id,m.sequence
    from dorf.job_messages m join dorf.agent_runs ar on ar.message_id=m.id
    where m.job_id=$1 and m.delivery_intent='steer'
      and ar.state in ('pending','submitting','uncertain') and ar.turn_id is null
    order by m.sequence limit 1
), candidate as (
    select message_id,0 as priority,sequence from unsettled_steer
    union all
    select message_id,1,0 from current_turn_start
    where not exists(select 1 from unsettled_steer)
    union all
    select message_id,1,sequence from current_unbound_mutation
    where not exists(select 1 from unsettled_steer)
      and not exists(select 1 from current_turn_start)
    union all
    select m.id,2,m.sequence
    from dorf.job_messages m join dorf.agent_runs ar on ar.message_id=m.id
    where m.job_id=$1 and m.delivery_intent='follow'
      and ar.state in ('pending','submitting')
      and ar.turn_id is null
      and not exists(select 1 from unsettled_steer)
      and not exists(select 1 from current_turn_start)
      and not exists(select 1 from current_unbound_mutation)
)
select m.id,m.job_id,m.from_kind,m.from_id,m.sequence,m.input,m.delivery_intent,
       coalesce(m.steer_target_turn_id,'') as steer_target_turn_id,m.admitted_at
from candidate c join dorf.job_messages m on m.id=c.message_id
order by c.priority,c.sequence limit 1
`

type NextAgentMessageRow struct {
	ID                string
	JobID             string
	FromKind          core.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	DeliveryIntent    core.MessageDeliveryIntent
	SteerTargetTurnID string
	AdmittedAt        time.Time
}

func (q *Queries) NextAgentMessage(ctx context.Context, jobID string) (NextAgentMessageRow, error) {
	row := q.db.QueryRowContext(ctx, nextAgentMessage, jobID)
	var i NextAgentMessageRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.DeliveryIntent,
		&i.SteerTargetTurnID,
		&i.AdmittedAt,
	)
	return i, err
}
