// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holds.sql

package dbsql

import (
	"context"
)

const getSandboxDeliveryHold = `-- name: GetSandboxDeliveryHold :one
select id,sandbox_id,reason,requested_at,released_at
from dorf.sandbox_delivery_holds where id=$1
`

func (q *Queries) GetSandboxDeliveryHold(ctx context.Context, id string) (DorfSandboxDeliveryHold, error) {
	row := q.db.QueryRowContext(ctx, getSandboxDeliveryHold, id)
	var i DorfSandboxDeliveryHold
	err := row.Scan(
		&i.ID,
		&i.SandboxID,
		&i.Reason,
		&i.RequestedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const insertSandboxDeliveryHold = `-- name: InsertSandboxDeliveryHold :exec
insert into dorf.sandbox_delivery_holds(id,sandbox_id,reason)
values($1,$2,'workspace_upgrade')
`

type InsertSandboxDeliveryHoldParams struct {
	ID        string
	SandboxID string
}

func (q *Queries) InsertSandboxDeliveryHold(ctx context.Context, arg InsertSandboxDeliveryHoldParams) error {
	_, err := q.db.ExecContext(ctx, insertSandboxDeliveryHold, arg.ID, arg.SandboxID)
	return err
}

const listSessionDeliveryHolds = `-- name: ListSessionDeliveryHolds :many
select h.id,h.sandbox_id,h.reason,h.requested_at,h.released_at
from dorf.sandbox_delivery_holds h join dorf.sandboxes s on s.id=h.sandbox_id
where s.session_id=$1 and h.released_at is null
order by h.requested_at,h.id
`

func (q *Queries) ListSessionDeliveryHolds(ctx context.Context, sessionID string) ([]DorfSandboxDeliveryHold, error) {
	rows, err := q.db.QueryContext(ctx, listSessionDeliveryHolds, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DorfSandboxDeliveryHold
	for rows.Next() {
		var i DorfSandboxDeliveryHold
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.Reason,
			&i.RequestedAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSandboxDeliveryHold = `-- name: ReleaseSandboxDeliveryHold :execrows
update dorf.sandbox_delivery_holds set released_at=coalesce(released_at,clock_timestamp())
where id=$1 and sandbox_id=$2
`

type ReleaseSandboxDeliveryHoldParams struct {
	ID        string
	SandboxID string
}

func (q *Queries) ReleaseSandboxDeliveryHold(ctx context.Context, arg ReleaseSandboxDeliveryHoldParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseSandboxDeliveryHold, arg.ID, arg.SandboxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sandboxDeliveryHeld = `-- name: SandboxDeliveryHeld :one
select exists(select 1 from dorf.sandbox_delivery_holds
where sandbox_id=$1 and released_at is null)::boolean
`

func (q *Queries) SandboxDeliveryHeld(ctx context.Context, sandboxID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, sandboxDeliveryHeld, sandboxID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
