// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idle.sql

package dbsql

import (
	"context"
)

const beginSandboxActivity = `-- name: BeginSandboxActivity :execrows
update dorf.sessions set sandbox_last_active_at=null where id=$1
`

func (q *Queries) BeginSandboxActivity(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, beginSandboxActivity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishSandboxActivity = `-- name: FinishSandboxActivity :execrows
update dorf.sessions set sandbox_last_active_at=clock_timestamp() where id=$1
`

func (q *Queries) FinishSandboxActivity(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishSandboxActivity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sandboxIdleFor = `-- name: SandboxIdleFor :one
update dorf.sessions j
set sandbox_last_active_at=coalesce(j.sandbox_last_active_at,clock_timestamp())
where j.id=$1
returning coalesce(j.sandbox_last_active_at <= clock_timestamp() - make_interval(secs => $2::double precision) and j.native_pending_input_id is null and j.native_pending_turn_id is null and not exists (
    select 1 from dorf.sandbox_delivery_holds h join dorf.sandboxes s on s.id=h.sandbox_id
    where s.session_id=j.id and h.released_at is null
),false)::boolean as idle
`

type SandboxIdleForParams struct {
	SessionID string
	Seconds   float64
}

func (q *Queries) SandboxIdleFor(ctx context.Context, arg SandboxIdleForParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, sandboxIdleFor, arg.SessionID, arg.Seconds)
	var idle bool
	err := row.Scan(&idle)
	return idle, err
}
