// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idle.sql

package dbsql

import (
	"context"
)

const beginSandboxActivity = `-- name: BeginSandboxActivity :execrows
update dorf.jobs set sandbox_last_active_at=null where id=$1
`

func (q *Queries) BeginSandboxActivity(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, beginSandboxActivity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishSandboxActivity = `-- name: FinishSandboxActivity :execrows
update dorf.jobs set sandbox_last_active_at=clock_timestamp() where id=$1
`

func (q *Queries) FinishSandboxActivity(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishSandboxActivity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sandboxIdleFor = `-- name: SandboxIdleFor :one
update dorf.jobs j
set sandbox_last_active_at=coalesce(j.sandbox_last_active_at,clock_timestamp())
where j.id=$1
returning coalesce(j.sandbox_last_active_at <= clock_timestamp() - make_interval(secs => $2::double precision) and not exists (
    select 1 from dorf.agent_runs ar
    where ar.job_id=$1 and ar.state not in ('completed','failed','interrupted')
),false)::boolean as idle
`

type SandboxIdleForParams struct {
	JobID   string
	Seconds float64
}

func (q *Queries) SandboxIdleFor(ctx context.Context, arg SandboxIdleForParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, sandboxIdleFor, arg.JobID, arg.Seconds)
	var idle bool
	err := row.Scan(&idle)
	return idle, err
}
