// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investigation.sql

package dbsql

import (
	"context"
)

const getCodebaseInvestigationSource = `-- name: GetCodebaseInvestigationSource :one
select s.job_id,s.repository,s.revision
from dorf.codebase_investigation_sources s
where s.job_id=$1
`

type GetCodebaseInvestigationSourceRow struct {
	JobID      string
	Repository string
	Revision   string
}

func (q *Queries) GetCodebaseInvestigationSource(ctx context.Context, jobID string) (GetCodebaseInvestigationSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getCodebaseInvestigationSource, jobID)
	var i GetCodebaseInvestigationSourceRow
	err := row.Scan(&i.JobID, &i.Repository, &i.Revision)
	return i, err
}

const insertCodebaseInvestigationSource = `-- name: InsertCodebaseInvestigationSource :execrows
insert into dorf.codebase_investigation_sources(
    job_id,workflow_name,repository,revision
) values(
    $1,'codebase-investigation',$2,$3
)
on conflict(job_id) do nothing
`

type InsertCodebaseInvestigationSourceParams struct {
	JobID      string
	Repository string
	Revision   string
}

func (q *Queries) InsertCodebaseInvestigationSource(ctx context.Context, arg InsertCodebaseInvestigationSourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCodebaseInvestigationSource, arg.JobID, arg.Repository, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
