// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investigation.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"

	"github.com/aphronio/dorf/internal/spine"
)

const getCodebaseInvestigationRunForUpdate = `-- name: GetCodebaseInvestigationRunForUpdate :one
select j.workflow_name,j.workflow_revision,j.revision,j.admission_open,j.cleanup_state,
       ar.id as agent_run_id,ar.role,ar.state,coalesce(ar.turn_id,'') as turn_id,
       coalesce(ar.turn_outcome,'') as turn_outcome,coalesce(ar.input_revision,'') as input_revision,
       ar.started_at,ar.finished_at
from dorf.jobs j
join dorf.agent_runs ar on ar.job_id=j.id
where j.id=$1 and ar.id=$2
for update of j,ar
`

type GetCodebaseInvestigationRunForUpdateParams struct {
	JobID      string
	AgentRunID string
}

type GetCodebaseInvestigationRunForUpdateRow struct {
	WorkflowName     spine.WorkflowName
	WorkflowRevision string
	Revision         string
	AdmissionOpen    bool
	CleanupState     spine.CleanupState
	AgentRunID       string
	Role             string
	State            spine.AgentRunState
	TurnID           string
	TurnOutcome      string
	InputRevision    string
	StartedAt        sql.NullTime
	FinishedAt       sql.NullTime
}

func (q *Queries) GetCodebaseInvestigationRunForUpdate(ctx context.Context, arg GetCodebaseInvestigationRunForUpdateParams) (GetCodebaseInvestigationRunForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getCodebaseInvestigationRunForUpdate, arg.JobID, arg.AgentRunID)
	var i GetCodebaseInvestigationRunForUpdateRow
	err := row.Scan(
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.Revision,
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.AgentRunID,
		&i.Role,
		&i.State,
		&i.TurnID,
		&i.TurnOutcome,
		&i.InputRevision,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getCodebaseInvestigationSource = `-- name: GetCodebaseInvestigationSource :one
select s.job_id,s.kind,j.repository,j.revision,
       coalesce(s.bundle_digest,'') as bundle_digest,coalesce(s.bundle_byte_size,0) as bundle_byte_size
from dorf.codebase_investigation_sources s
join dorf.jobs j on j.id=s.job_id
where s.job_id=$1
`

type GetCodebaseInvestigationSourceRow struct {
	JobID          string
	Kind           string
	Repository     string
	Revision       string
	BundleDigest   string
	BundleByteSize int64
}

func (q *Queries) GetCodebaseInvestigationSource(ctx context.Context, jobID string) (GetCodebaseInvestigationSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getCodebaseInvestigationSource, jobID)
	var i GetCodebaseInvestigationSourceRow
	err := row.Scan(
		&i.JobID,
		&i.Kind,
		&i.Repository,
		&i.Revision,
		&i.BundleDigest,
		&i.BundleByteSize,
	)
	return i, err
}

const getLatestInvestigationRunAndDraft = `-- name: GetLatestInvestigationRunAndDraft :one
select ar.id as agent_run_id,coalesce(ar.harness,'') as harness,
       coalesce(ar.thread_id,'') as thread_id,ar.state,
       coalesce(d.artifact_id,'') as artifact_id
from dorf.agent_runs ar
join dorf.job_messages m on m.id=ar.message_id
left join dorf.codebase_investigation_drafts d
  on d.job_id=ar.job_id and d.agent_run_id=ar.id
where ar.job_id=$1 and ar.role='investigate'
order by m.sequence desc
limit 1
`

type GetLatestInvestigationRunAndDraftRow struct {
	AgentRunID string
	Harness    string
	ThreadID   string
	State      spine.AgentRunState
	ArtifactID string
}

func (q *Queries) GetLatestInvestigationRunAndDraft(ctx context.Context, jobID string) (GetLatestInvestigationRunAndDraftRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestInvestigationRunAndDraft, jobID)
	var i GetLatestInvestigationRunAndDraftRow
	err := row.Scan(
		&i.AgentRunID,
		&i.Harness,
		&i.ThreadID,
		&i.State,
		&i.ArtifactID,
	)
	return i, err
}

const insertCodebaseInvestigationDraft = `-- name: InsertCodebaseInvestigationDraft :execrows
insert into dorf.codebase_investigation_drafts(
    job_id,agent_run_id,artifact_id
) values(
    $1,$2,$3
)
on conflict(job_id,agent_run_id) do nothing
`

type InsertCodebaseInvestigationDraftParams struct {
	JobID      string
	AgentRunID string
	ArtifactID string
}

func (q *Queries) InsertCodebaseInvestigationDraft(ctx context.Context, arg InsertCodebaseInvestigationDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCodebaseInvestigationDraft, arg.JobID, arg.AgentRunID, arg.ArtifactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertCodebaseInvestigationSource = `-- name: InsertCodebaseInvestigationSource :execrows
insert into dorf.codebase_investigation_sources(
    job_id,kind,bundle_digest,bundle_byte_size
) values(
    $1,$2,$3,$4
)
on conflict(job_id) do nothing
`

type InsertCodebaseInvestigationSourceParams struct {
	JobID          string
	Kind           string
	BundleDigest   sql.NullString
	BundleByteSize sql.NullInt64
}

func (q *Queries) InsertCodebaseInvestigationSource(ctx context.Context, arg InsertCodebaseInvestigationSourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCodebaseInvestigationSource,
		arg.JobID,
		arg.Kind,
		arg.BundleDigest,
		arg.BundleByteSize,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listCodebaseInvestigationDrafts = `-- name: ListCodebaseInvestigationDrafts :many
select d.job_id,d.agent_run_id,d.artifact_id,a.created_at
from dorf.codebase_investigation_drafts d
join dorf.artifacts a on a.job_id=d.job_id and a.id=d.artifact_id
join dorf.agent_runs ar on ar.job_id=d.job_id and ar.id=d.agent_run_id
join dorf.job_messages m on m.id=ar.message_id
where d.job_id=$1
order by m.sequence,d.artifact_id
`

type ListCodebaseInvestigationDraftsRow struct {
	JobID      string
	AgentRunID string
	ArtifactID string
	CreatedAt  time.Time
}

func (q *Queries) ListCodebaseInvestigationDrafts(ctx context.Context, jobID string) ([]ListCodebaseInvestigationDraftsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCodebaseInvestigationDrafts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCodebaseInvestigationDraftsRow
	for rows.Next() {
		var i ListCodebaseInvestigationDraftsRow
		if err := rows.Scan(
			&i.JobID,
			&i.AgentRunID,
			&i.ArtifactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
