// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investigation.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"

	"github.com/aphronio/dorf/internal/spine"
)

const closeAdmissionForCodebaseInvestigation = `-- name: CloseAdmissionForCodebaseInvestigation :execrows
update dorf.jobs
set admission_open=false
where id=$1 and admission_open and cleanup_state='pending'
  and workflow_name='codebase-investigation' and workflow_revision='1'
`

func (q *Queries) CloseAdmissionForCodebaseInvestigation(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeAdmissionForCodebaseInvestigation, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCodebaseInvestigationReport = `-- name: GetCodebaseInvestigationReport :one
select job_id,agent_run_id,report_evidence_id,observed_at
from dorf.codebase_investigation_reports
where job_id=$1
`

func (q *Queries) GetCodebaseInvestigationReport(ctx context.Context, jobID string) (DorfCodebaseInvestigationReport, error) {
	row := q.db.QueryRowContext(ctx, getCodebaseInvestigationReport, jobID)
	var i DorfCodebaseInvestigationReport
	err := row.Scan(
		&i.JobID,
		&i.AgentRunID,
		&i.ReportEvidenceID,
		&i.ObservedAt,
	)
	return i, err
}

const getCodebaseInvestigationRunForUpdate = `-- name: GetCodebaseInvestigationRunForUpdate :one
select j.workflow_name,j.workflow_revision,j.revision,j.admission_open,j.cleanup_state,
       ar.id as agent_run_id,ar.role,ar.state,coalesce(ar.turn_id,'') as turn_id,
       coalesce(ar.turn_outcome,'') as turn_outcome,coalesce(ar.input_revision,'') as input_revision,
       ar.started_at,ar.finished_at
from dorf.jobs j
join dorf.agent_runs ar on ar.job_id=j.id
where j.id=$1 and ar.id=$2
for update of j,ar
`

type GetCodebaseInvestigationRunForUpdateParams struct {
	JobID      string
	AgentRunID string
}

type GetCodebaseInvestigationRunForUpdateRow struct {
	WorkflowName     spine.WorkflowName
	WorkflowRevision string
	Revision         string
	AdmissionOpen    bool
	CleanupState     spine.CleanupState
	AgentRunID       string
	Role             string
	State            spine.AgentRunState
	TurnID           string
	TurnOutcome      string
	InputRevision    string
	StartedAt        sql.NullTime
	FinishedAt       sql.NullTime
}

func (q *Queries) GetCodebaseInvestigationRunForUpdate(ctx context.Context, arg GetCodebaseInvestigationRunForUpdateParams) (GetCodebaseInvestigationRunForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getCodebaseInvestigationRunForUpdate, arg.JobID, arg.AgentRunID)
	var i GetCodebaseInvestigationRunForUpdateRow
	err := row.Scan(
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.Revision,
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.AgentRunID,
		&i.Role,
		&i.State,
		&i.TurnID,
		&i.TurnOutcome,
		&i.InputRevision,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertCodebaseInvestigationReport = `-- name: InsertCodebaseInvestigationReport :one
insert into dorf.codebase_investigation_reports(
    job_id,agent_run_id,report_evidence_id,observed_at
) values(
    $1,$2,
    $3,$4
)
returning job_id,agent_run_id,report_evidence_id,observed_at
`

type InsertCodebaseInvestigationReportParams struct {
	JobID            string
	AgentRunID       string
	ReportEvidenceID string
	ObservedAt       time.Time
}

func (q *Queries) InsertCodebaseInvestigationReport(ctx context.Context, arg InsertCodebaseInvestigationReportParams) (DorfCodebaseInvestigationReport, error) {
	row := q.db.QueryRowContext(ctx, insertCodebaseInvestigationReport,
		arg.JobID,
		arg.AgentRunID,
		arg.ReportEvidenceID,
		arg.ObservedAt,
	)
	var i DorfCodebaseInvestigationReport
	err := row.Scan(
		&i.JobID,
		&i.AgentRunID,
		&i.ReportEvidenceID,
		&i.ObservedAt,
	)
	return i, err
}
