// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"

	"github.com/aphronio/dorf/internal/core"
)

const advanceJobRevision = `-- name: AdvanceJobRevision :execrows
update dorf.coding_to_proposal_inputs
set revision=$1
where job_id=$2 and revision=$3
`

type AdvanceJobRevisionParams struct {
	Revision          string
	JobID             string
	ComparisonBaseOID string
}

func (q *Queries) AdvanceJobRevision(ctx context.Context, arg AdvanceJobRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceJobRevision, arg.Revision, arg.JobID, arg.ComparisonBaseOID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearWorkflowAttention = `-- name: ClearWorkflowAttention :execrows
update dorf.jobs
set workflow_attention=null,workflow_attention_source=null,workflow_attention_at=null
where id=$1 and workflow_attention_source=$2
`

type ClearWorkflowAttentionParams struct {
	JobID  string
	Source sql.NullString
}

func (q *Queries) ClearWorkflowAttention(ctx context.Context, arg ClearWorkflowAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearWorkflowAttention, arg.JobID, arg.Source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAdmittedJobForUpdate = `-- name: GetAdmittedJobForUpdate :one
select id,admission_key,workflow_name,workflow_revision,goal,sandbox_profile,provider_connection,
       model,reasoning_effort
from dorf.jobs
where admission_key=$1
for update
`

type GetAdmittedJobForUpdateRow struct {
	ID                 string
	AdmissionKey       string
	WorkflowName       core.WorkflowName
	WorkflowRevision   string
	Goal               string
	SandboxProfile     string
	ProviderConnection string
	Model              string
	ReasoningEffort    string
}

func (q *Queries) GetAdmittedJobForUpdate(ctx context.Context, admissionKey string) (GetAdmittedJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getAdmittedJobForUpdate, admissionKey)
	var i GetAdmittedJobForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.AdmissionKey,
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.Goal,
		&i.SandboxProfile,
		&i.ProviderConnection,
		&i.Model,
		&i.ReasoningEffort,
	)
	return i, err
}

const getCodingJob = `-- name: GetCodingJob :one
select j.id,j.admission_key,j.workflow_name,j.workflow_revision,j.goal,
       c.repository,c.starting_revision,c.revision,c.branch,
       c.github_repository,c.github_installation_id,c.base_branch,
       j.sandbox_profile,j.provider_connection,j.model,j.reasoning_effort,j.admission_open,
       j.cleanup_state,coalesce(current_task.task_id,'') as current_task_id,
       coalesce(j.workflow_attention,'') as workflow_attention,
       coalesce(j.workflow_attention_source,'') as workflow_attention_source,
       j.workflow_attention_at,coalesce(j.cleanup_attention,'') as cleanup_attention,
       j.admitted_at,j.cleaned_at
from dorf.jobs j
join dorf.coding_to_proposal_inputs c on c.job_id=j.id
left join lateral (
    select task_id from dorf.job_tasks where job_id=j.id order by sequence desc limit 1
) current_task on true
where j.id=$1
`

type GetCodingJobRow struct {
	ID                      string
	AdmissionKey            string
	WorkflowName            core.WorkflowName
	WorkflowRevision        string
	Goal                    string
	Repository              string
	StartingRevision        string
	Revision                string
	Branch                  string
	GithubRepository        string
	GithubInstallationID    string
	BaseBranch              string
	SandboxProfile          string
	ProviderConnection      string
	Model                   string
	ReasoningEffort         string
	AdmissionOpen           bool
	CleanupState            core.CleanupState
	CurrentTaskID           string
	WorkflowAttention       string
	WorkflowAttentionSource string
	WorkflowAttentionAt     sql.NullTime
	CleanupAttention        string
	AdmittedAt              time.Time
	CleanedAt               sql.NullTime
}

func (q *Queries) GetCodingJob(ctx context.Context, jobID string) (GetCodingJobRow, error) {
	row := q.db.QueryRowContext(ctx, getCodingJob, jobID)
	var i GetCodingJobRow
	err := row.Scan(
		&i.ID,
		&i.AdmissionKey,
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.Goal,
		&i.Repository,
		&i.StartingRevision,
		&i.Revision,
		&i.Branch,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.BaseBranch,
		&i.SandboxProfile,
		&i.ProviderConnection,
		&i.Model,
		&i.ReasoningEffort,
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.CurrentTaskID,
		&i.WorkflowAttention,
		&i.WorkflowAttentionSource,
		&i.WorkflowAttentionAt,
		&i.CleanupAttention,
		&i.AdmittedAt,
		&i.CleanedAt,
	)
	return i, err
}

const getCodingToProposalInput = `-- name: GetCodingToProposalInput :one
select job_id,repository,starting_revision,revision,branch,
       github_repository,github_installation_id,base_branch
from dorf.coding_to_proposal_inputs
where job_id=$1
`

type GetCodingToProposalInputRow struct {
	JobID                string
	Repository           string
	StartingRevision     string
	Revision             string
	Branch               string
	GithubRepository     string
	GithubInstallationID string
	BaseBranch           string
}

func (q *Queries) GetCodingToProposalInput(ctx context.Context, jobID string) (GetCodingToProposalInputRow, error) {
	row := q.db.QueryRowContext(ctx, getCodingToProposalInput, jobID)
	var i GetCodingToProposalInputRow
	err := row.Scan(
		&i.JobID,
		&i.Repository,
		&i.StartingRevision,
		&i.Revision,
		&i.Branch,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.BaseBranch,
	)
	return i, err
}

const getCurrentJobTaskForUpdate = `-- name: GetCurrentJobTaskForUpdate :one
select coalesce(current_task.task_id,'') as task_id,
       coalesce(current_task.task_name,'') as task_name,
       coalesce(current_task.sequence,0)::bigint as sequence,
       j.admission_open,j.cleanup_state
from dorf.jobs j
left join lateral (
    select task_id,task_name,sequence
    from dorf.job_tasks where job_id=j.id order by sequence desc limit 1
) current_task on true
where j.id=$1
for update of j
`

type GetCurrentJobTaskForUpdateRow struct {
	TaskID        string
	TaskName      string
	Sequence      int64
	AdmissionOpen bool
	CleanupState  core.CleanupState
}

func (q *Queries) GetCurrentJobTaskForUpdate(ctx context.Context, jobID string) (GetCurrentJobTaskForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentJobTaskForUpdate, jobID)
	var i GetCurrentJobTaskForUpdateRow
	err := row.Scan(
		&i.TaskID,
		&i.TaskName,
		&i.Sequence,
		&i.AdmissionOpen,
		&i.CleanupState,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
select j.id,j.admission_key,j.workflow_name,j.workflow_revision,j.goal,
       j.sandbox_profile,j.provider_connection,j.model,j.reasoning_effort,j.admission_open,
       j.cleanup_state,coalesce(current_task.task_id,'') as current_task_id,
       coalesce(j.workflow_attention,'') as workflow_attention,
       coalesce(j.workflow_attention_source,'') as workflow_attention_source,
       j.workflow_attention_at,coalesce(j.cleanup_attention,'') as cleanup_attention,
       j.admitted_at,j.cleaned_at
from dorf.jobs j
left join lateral (
    select task_id from dorf.job_tasks where job_id=j.id order by sequence desc limit 1
) current_task on true
where j.id=$1
`

type GetJobRow struct {
	ID                      string
	AdmissionKey            string
	WorkflowName            core.WorkflowName
	WorkflowRevision        string
	Goal                    string
	SandboxProfile          string
	ProviderConnection      string
	Model                   string
	ReasoningEffort         string
	AdmissionOpen           bool
	CleanupState            core.CleanupState
	CurrentTaskID           string
	WorkflowAttention       string
	WorkflowAttentionSource string
	WorkflowAttentionAt     sql.NullTime
	CleanupAttention        string
	AdmittedAt              time.Time
	CleanedAt               sql.NullTime
}

func (q *Queries) GetJob(ctx context.Context, jobID string) (GetJobRow, error) {
	row := q.db.QueryRowContext(ctx, getJob, jobID)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.AdmissionKey,
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.Goal,
		&i.SandboxProfile,
		&i.ProviderConnection,
		&i.Model,
		&i.ReasoningEffort,
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.CurrentTaskID,
		&i.WorkflowAttention,
		&i.WorkflowAttentionSource,
		&i.WorkflowAttentionAt,
		&i.CleanupAttention,
		&i.AdmittedAt,
		&i.CleanedAt,
	)
	return i, err
}

const getJobAdmissionForUpdate = `-- name: GetJobAdmissionForUpdate :one
select workflow_name,workflow_revision,admission_open,cleanup_state,
       exists(select 1 from dorf.job_outcomes where job_id=dorf.jobs.id) as outcome_exists
from dorf.jobs
where id=$1
for update
`

type GetJobAdmissionForUpdateRow struct {
	WorkflowName     core.WorkflowName
	WorkflowRevision string
	AdmissionOpen    bool
	CleanupState     core.CleanupState
	OutcomeExists    bool
}

func (q *Queries) GetJobAdmissionForUpdate(ctx context.Context, jobID string) (GetJobAdmissionForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getJobAdmissionForUpdate, jobID)
	var i GetJobAdmissionForUpdateRow
	err := row.Scan(
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.OutcomeExists,
	)
	return i, err
}

const getJobForSandboxActionAuthorization = `-- name: GetJobForSandboxActionAuthorization :one
select j.id,j.admission_key,j.workflow_name,j.workflow_revision,j.goal,
       j.sandbox_profile,j.provider_connection,j.model,j.reasoning_effort,j.admission_open,
       j.cleanup_state,coalesce(current_task.task_id,'') as current_task_id,
       coalesce(current_task.task_name,'') as current_task_name,
       coalesce(j.workflow_attention,'') as workflow_attention,
       coalesce(j.workflow_attention_source,'') as workflow_attention_source,
       j.workflow_attention_at,coalesce(j.cleanup_attention,'') as cleanup_attention,
       j.admitted_at,j.cleaned_at
from dorf.jobs j
left join lateral (
    select task_id,task_name from dorf.job_tasks where job_id=j.id order by sequence desc limit 1
) current_task on true
where j.id=$1
for update of j
`

type GetJobForSandboxActionAuthorizationRow struct {
	ID                      string
	AdmissionKey            string
	WorkflowName            core.WorkflowName
	WorkflowRevision        string
	Goal                    string
	SandboxProfile          string
	ProviderConnection      string
	Model                   string
	ReasoningEffort         string
	AdmissionOpen           bool
	CleanupState            core.CleanupState
	CurrentTaskID           string
	CurrentTaskName         string
	WorkflowAttention       string
	WorkflowAttentionSource string
	WorkflowAttentionAt     sql.NullTime
	CleanupAttention        string
	AdmittedAt              time.Time
	CleanedAt               sql.NullTime
}

func (q *Queries) GetJobForSandboxActionAuthorization(ctx context.Context, jobID string) (GetJobForSandboxActionAuthorizationRow, error) {
	row := q.db.QueryRowContext(ctx, getJobForSandboxActionAuthorization, jobID)
	var i GetJobForSandboxActionAuthorizationRow
	err := row.Scan(
		&i.ID,
		&i.AdmissionKey,
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.Goal,
		&i.SandboxProfile,
		&i.ProviderConnection,
		&i.Model,
		&i.ReasoningEffort,
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.CurrentTaskID,
		&i.CurrentTaskName,
		&i.WorkflowAttention,
		&i.WorkflowAttentionSource,
		&i.WorkflowAttentionAt,
		&i.CleanupAttention,
		&i.AdmittedAt,
		&i.CleanedAt,
	)
	return i, err
}

const getJobForSandboxEnsure = `-- name: GetJobForSandboxEnsure :one
select admission_open,cleanup_state
from dorf.jobs
where id=$1
for update
`

type GetJobForSandboxEnsureRow struct {
	AdmissionOpen bool
	CleanupState  core.CleanupState
}

func (q *Queries) GetJobForSandboxEnsure(ctx context.Context, jobID string) (GetJobForSandboxEnsureRow, error) {
	row := q.db.QueryRowContext(ctx, getJobForSandboxEnsure, jobID)
	var i GetJobForSandboxEnsureRow
	err := row.Scan(&i.AdmissionOpen, &i.CleanupState)
	return i, err
}

const getJobSandboxProfileForUpdate = `-- name: GetJobSandboxProfileForUpdate :one
select sandbox_profile
from dorf.jobs
where id=$1
for update
`

func (q *Queries) GetJobSandboxProfileForUpdate(ctx context.Context, jobID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getJobSandboxProfileForUpdate, jobID)
	var sandbox_profile string
	err := row.Scan(&sandbox_profile)
	return sandbox_profile, err
}

const getRevisionJobForUpdate = `-- name: GetRevisionJobForUpdate :one
select c.revision,c.branch,j.admission_open,
       exists(select 1 from dorf.job_outcomes where job_id=j.id) as outcome_exists
from dorf.jobs j
join dorf.coding_to_proposal_inputs c on c.job_id=j.id
where j.id=$1
for update of j,c
`

type GetRevisionJobForUpdateRow struct {
	Revision      string
	Branch        string
	AdmissionOpen bool
	OutcomeExists bool
}

func (q *Queries) GetRevisionJobForUpdate(ctx context.Context, jobID string) (GetRevisionJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getRevisionJobForUpdate, jobID)
	var i GetRevisionJobForUpdateRow
	err := row.Scan(
		&i.Revision,
		&i.Branch,
		&i.AdmissionOpen,
		&i.OutcomeExists,
	)
	return i, err
}

const insertAdmittedJob = `-- name: InsertAdmittedJob :execrows
insert into dorf.jobs(
    id,admission_key,workflow_name,workflow_revision,goal,
    sandbox_profile,provider_connection,model,reasoning_effort
)
values(
    $1,$2,$3,$4,
    $5,
    $6,$7,$8,
    $9
)
on conflict(admission_key) do nothing
`

type InsertAdmittedJobParams struct {
	ID                 string
	AdmissionKey       string
	WorkflowName       core.WorkflowName
	WorkflowRevision   string
	Goal               string
	SandboxProfile     string
	ProviderConnection string
	Model              string
	ReasoningEffort    string
}

func (q *Queries) InsertAdmittedJob(ctx context.Context, arg InsertAdmittedJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAdmittedJob,
		arg.ID,
		arg.AdmissionKey,
		arg.WorkflowName,
		arg.WorkflowRevision,
		arg.Goal,
		arg.SandboxProfile,
		arg.ProviderConnection,
		arg.Model,
		arg.ReasoningEffort,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertCodingToProposalInput = `-- name: InsertCodingToProposalInput :execrows
insert into dorf.coding_to_proposal_inputs(
    job_id,workflow_name,repository,starting_revision,revision,branch,
    github_repository,github_installation_id,base_branch
) values(
    $1,'coding-to-proposal',$2,$3,$4,
    $5,$6,$7,$8
)
on conflict(job_id) do nothing
`

type InsertCodingToProposalInputParams struct {
	JobID                string
	Repository           string
	StartingRevision     string
	Revision             string
	Branch               string
	GithubRepository     string
	GithubInstallationID string
	BaseBranch           string
}

func (q *Queries) InsertCodingToProposalInput(ctx context.Context, arg InsertCodingToProposalInputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCodingToProposalInput,
		arg.JobID,
		arg.Repository,
		arg.StartingRevision,
		arg.Revision,
		arg.Branch,
		arg.GithubRepository,
		arg.GithubInstallationID,
		arg.BaseBranch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertInitialRevision = `-- name: InsertInitialRevision :exec
insert into dorf.revisions(job_id,oid,branch,generation)
values($1,$2,$3,0)
on conflict do nothing
`

type InsertInitialRevisionParams struct {
	JobID  string
	OID    string
	Branch string
}

func (q *Queries) InsertInitialRevision(ctx context.Context, arg InsertInitialRevisionParams) error {
	_, err := q.db.ExecContext(ctx, insertInitialRevision, arg.JobID, arg.OID, arg.Branch)
	return err
}

const insertJobTask = `-- name: InsertJobTask :execrows
insert into dorf.job_tasks(job_id,sequence,task_id,task_name)
values($1,$2,$3,$4)
on conflict(task_id) do nothing
`

type InsertJobTaskParams struct {
	JobID    string
	Sequence int64
	TaskID   string
	TaskName string
}

func (q *Queries) InsertJobTask(ctx context.Context, arg InsertJobTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertJobTask,
		arg.JobID,
		arg.Sequence,
		arg.TaskID,
		arg.TaskName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertRevision = `-- name: InsertRevision :exec
insert into dorf.revisions(job_id,oid,comparison_base_oid,tree_oid,branch,generation,evidence_id)
values($1,$2,$3::text,$4::text,
       $5,$6,$7::text)
`

type InsertRevisionParams struct {
	JobID             string
	OID               string
	ComparisonBaseOID string
	TreeOID           string
	Branch            string
	Generation        int32
	EvidenceID        string
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) error {
	_, err := q.db.ExecContext(ctx, insertRevision,
		arg.JobID,
		arg.OID,
		arg.ComparisonBaseOID,
		arg.TreeOID,
		arg.Branch,
		arg.Generation,
		arg.EvidenceID,
	)
	return err
}

const listJobTasks = `-- name: ListJobTasks :many
select job_id,sequence,task_id,task_name,attached_at
from dorf.job_tasks
where job_id=$1
order by sequence
`

func (q *Queries) ListJobTasks(ctx context.Context, jobID string) ([]DorfJobTask, error) {
	rows, err := q.db.QueryContext(ctx, listJobTasks, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DorfJobTask
	for rows.Next() {
		var i DorfJobTask
		if err := rows.Scan(
			&i.JobID,
			&i.Sequence,
			&i.TaskID,
			&i.TaskName,
			&i.AttachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
select job_id,oid,coalesce(comparison_base_oid,'') as comparison_base_oid,
       coalesce(tree_oid,'') as tree_oid,branch,generation,
       coalesce(evidence_id,'') as evidence_id,observed_at
from dorf.revisions
where job_id=$1
order by generation
`

type ListRevisionsRow struct {
	JobID             string
	OID               string
	ComparisonBaseOID string
	TreeOID           string
	Branch            string
	Generation        int32
	EvidenceID        string
	ObservedAt        time.Time
}

func (q *Queries) ListRevisions(ctx context.Context, jobID string) ([]ListRevisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRevisions, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionsRow
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.JobID,
			&i.OID,
			&i.ComparisonBaseOID,
			&i.TreeOID,
			&i.Branch,
			&i.Generation,
			&i.EvidenceID,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportedJobs = `-- name: ListSupportedJobs :many
select j.id,j.workflow_name,j.workflow_revision,j.admitted_at
from dorf.jobs j
where (
        (j.workflow_name='' and j.workflow_revision='') or
        (j.workflow_name=$1::text and j.workflow_revision=$2::text) or
        (j.workflow_name=$3::text and j.workflow_revision=$4::text and
         exists(
             select 1 from dorf.codebase_investigation_sources source
             where source.job_id=j.id and source.kind=$5::text
         ))
      )
  and (
        not $6::boolean or
        j.admitted_at < $7::timestamptz or
        (j.admitted_at=$7::timestamptz and j.id < $8::text)
      )
order by j.admitted_at desc,j.id desc
limit $9
`

type ListSupportedJobsParams struct {
	CodingWorkflow          string
	CodingRevision          string
	InvestigationWorkflow   string
	InvestigationRevision   string
	InvestigationSourceKind string
	HasCursor               bool
	CursorAdmittedAt        time.Time
	CursorID                string
	PageSize                int32
}

type ListSupportedJobsRow struct {
	ID               string
	WorkflowName     core.WorkflowName
	WorkflowRevision string
	AdmittedAt       time.Time
}

func (q *Queries) ListSupportedJobs(ctx context.Context, arg ListSupportedJobsParams) ([]ListSupportedJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupportedJobs,
		arg.CodingWorkflow,
		arg.CodingRevision,
		arg.InvestigationWorkflow,
		arg.InvestigationRevision,
		arg.InvestigationSourceKind,
		arg.HasCursor,
		arg.CursorAdmittedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupportedJobsRow
	for rows.Next() {
		var i ListSupportedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowName,
			&i.WorkflowRevision,
			&i.AdmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCleanupScheduled = `-- name: MarkCleanupScheduled :execrows
update dorf.jobs
set cleanup_state='scheduled'
where id=$1 and not admission_open and cleanup_state='requested'
`

func (q *Queries) MarkCleanupScheduled(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCleanupScheduled, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const nextRevisionGeneration = `-- name: NextRevisionGeneration :one
select (coalesce(max(generation),0)+1)::integer
from dorf.revisions
where job_id=$1
`

func (q *Queries) NextRevisionGeneration(ctx context.Context, jobID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, nextRevisionGeneration, jobID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setCleanupAttention = `-- name: SetCleanupAttention :execrows
update dorf.jobs
set cleanup_attention=nullif($1::text,'')
where id=$2 and cleanup_state<>'complete'
`

type SetCleanupAttentionParams struct {
	Detail string
	JobID  string
}

func (q *Queries) SetCleanupAttention(ctx context.Context, arg SetCleanupAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCleanupAttention, arg.Detail, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setWorkflowAttention = `-- name: SetWorkflowAttention :execrows
update dorf.jobs
set workflow_attention=$1,
    workflow_attention_source=$2,
    workflow_attention_at=clock_timestamp()
where id=$3
  and (workflow_attention_source is null or workflow_attention_source=$2)
`

type SetWorkflowAttentionParams struct {
	Detail sql.NullString
	Source sql.NullString
	JobID  string
}

func (q *Queries) SetWorkflowAttention(ctx context.Context, arg SetWorkflowAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setWorkflowAttention, arg.Detail, arg.Source, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
