// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"

	"github.com/aphronio/dorf/internal/core"
)

const clearWorkflowAttention = `-- name: ClearWorkflowAttention :execrows
update dorf.jobs
set workflow_attention=null,workflow_attention_source=null,workflow_attention_at=null
where id=$1 and workflow_attention_source=$2
`

type ClearWorkflowAttentionParams struct {
	JobID  string
	Source sql.NullString
}

func (q *Queries) ClearWorkflowAttention(ctx context.Context, arg ClearWorkflowAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearWorkflowAttention, arg.JobID, arg.Source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAdmittedJobForUpdate = `-- name: GetAdmittedJobForUpdate :one
select id,admission_key,workflow_name,workflow_revision,agents_md,sandbox_profile,provider_connection,
       model,reasoning_effort,client_reference,keep_running
from dorf.jobs
where admission_key=$1
for update
`

type GetAdmittedJobForUpdateRow struct {
	ID                 string
	AdmissionKey       string
	WorkflowName       core.WorkflowName
	WorkflowRevision   string
	AgentsMd           string
	SandboxProfile     string
	ProviderConnection string
	Model              string
	ReasoningEffort    string
	ClientReference    string
	KeepRunning        bool
}

func (q *Queries) GetAdmittedJobForUpdate(ctx context.Context, admissionKey string) (GetAdmittedJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getAdmittedJobForUpdate, admissionKey)
	var i GetAdmittedJobForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.AdmissionKey,
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.AgentsMd,
		&i.SandboxProfile,
		&i.ProviderConnection,
		&i.Model,
		&i.ReasoningEffort,
		&i.ClientReference,
		&i.KeepRunning,
	)
	return i, err
}

const getCurrentJobTaskForUpdate = `-- name: GetCurrentJobTaskForUpdate :one
select coalesce(current_task.task_id,'') as task_id,
       coalesce(current_task.task_name,'') as task_name,
       coalesce(current_task.sequence,0)::bigint as sequence,
       j.admission_open,j.cleanup_state
from dorf.jobs j
left join lateral (
    select task_id,task_name,sequence
    from dorf.job_tasks where job_id=j.id order by sequence desc limit 1
) current_task on true
where j.id=$1
for update of j
`

type GetCurrentJobTaskForUpdateRow struct {
	TaskID        string
	TaskName      string
	Sequence      int64
	AdmissionOpen bool
	CleanupState  core.CleanupState
}

func (q *Queries) GetCurrentJobTaskForUpdate(ctx context.Context, jobID string) (GetCurrentJobTaskForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentJobTaskForUpdate, jobID)
	var i GetCurrentJobTaskForUpdateRow
	err := row.Scan(
		&i.TaskID,
		&i.TaskName,
		&i.Sequence,
		&i.AdmissionOpen,
		&i.CleanupState,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
select coalesce(j.created_by_client_id,'') as created_by_client_id, coalesce(creator.name,'') as created_by_client_name,j.client_reference,
       coalesce(j.thread_harness,'') as thread_harness,coalesce(j.thread_id,'') as thread_id,
       j.id,j.admission_key,j.workflow_name,j.workflow_revision,j.agents_md,
       j.sandbox_profile,j.sandbox_profile_revision,j.provider_connection,j.model,j.reasoning_effort,j.keep_running,j.admission_open,
       j.cleanup_state,coalesce(current_task.task_id,'') as current_task_id,
       coalesce(j.workflow_attention,'') as workflow_attention,
       coalesce(j.workflow_attention_source,'') as workflow_attention_source,
       j.workflow_attention_at,coalesce(j.cleanup_attention,'') as cleanup_attention,
       j.admitted_at,j.cleaned_at
from dorf.jobs j
left join dorf.control_clients creator on creator.id=j.created_by_client_id
left join lateral (
    select task_id from dorf.job_tasks where job_id=j.id order by sequence desc limit 1
) current_task on true
where j.id=$1
`

type GetJobRow struct {
	CreatedByClientID       string
	CreatedByClientName     string
	ClientReference         string
	ThreadHarness           string
	ThreadID                string
	ID                      string
	AdmissionKey            string
	WorkflowName            core.WorkflowName
	WorkflowRevision        string
	AgentsMd                string
	SandboxProfile          string
	SandboxProfileRevision  string
	ProviderConnection      string
	Model                   string
	ReasoningEffort         string
	KeepRunning             bool
	AdmissionOpen           bool
	CleanupState            core.CleanupState
	CurrentTaskID           string
	WorkflowAttention       string
	WorkflowAttentionSource string
	WorkflowAttentionAt     sql.NullTime
	CleanupAttention        string
	AdmittedAt              time.Time
	CleanedAt               sql.NullTime
}

func (q *Queries) GetJob(ctx context.Context, jobID string) (GetJobRow, error) {
	row := q.db.QueryRowContext(ctx, getJob, jobID)
	var i GetJobRow
	err := row.Scan(
		&i.CreatedByClientID,
		&i.CreatedByClientName,
		&i.ClientReference,
		&i.ThreadHarness,
		&i.ThreadID,
		&i.ID,
		&i.AdmissionKey,
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.AgentsMd,
		&i.SandboxProfile,
		&i.SandboxProfileRevision,
		&i.ProviderConnection,
		&i.Model,
		&i.ReasoningEffort,
		&i.KeepRunning,
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.CurrentTaskID,
		&i.WorkflowAttention,
		&i.WorkflowAttentionSource,
		&i.WorkflowAttentionAt,
		&i.CleanupAttention,
		&i.AdmittedAt,
		&i.CleanedAt,
	)
	return i, err
}

const getJobAdmissionForUpdate = `-- name: GetJobAdmissionForUpdate :one
select workflow_name,workflow_revision,admission_open,cleanup_state,
       coalesce(thread_harness,'') as thread_harness,coalesce(thread_id,'') as thread_id
from dorf.jobs
where id=$1
for update
`

type GetJobAdmissionForUpdateRow struct {
	WorkflowName     core.WorkflowName
	WorkflowRevision string
	AdmissionOpen    bool
	CleanupState     core.CleanupState
	ThreadHarness    string
	ThreadID         string
}

func (q *Queries) GetJobAdmissionForUpdate(ctx context.Context, jobID string) (GetJobAdmissionForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getJobAdmissionForUpdate, jobID)
	var i GetJobAdmissionForUpdateRow
	err := row.Scan(
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.ThreadHarness,
		&i.ThreadID,
	)
	return i, err
}

const getJobForSandboxActionAuthorization = `-- name: GetJobForSandboxActionAuthorization :one
select coalesce(j.created_by_client_id,'') as created_by_client_id, coalesce(creator.name,'') as created_by_client_name,j.client_reference,
       coalesce(j.thread_harness,'') as thread_harness,coalesce(j.thread_id,'') as thread_id,
       j.id,j.admission_key,j.workflow_name,j.workflow_revision,j.agents_md,
       j.sandbox_profile,j.sandbox_profile_revision,j.provider_connection,j.model,j.reasoning_effort,j.keep_running,j.admission_open,
       j.cleanup_state,coalesce(current_task.task_id,'') as current_task_id,
       coalesce(current_task.task_name,'') as current_task_name,
       coalesce(j.workflow_attention,'') as workflow_attention,
       coalesce(j.workflow_attention_source,'') as workflow_attention_source,
       j.workflow_attention_at,coalesce(j.cleanup_attention,'') as cleanup_attention,
       j.admitted_at,j.cleaned_at
from dorf.jobs j
left join dorf.control_clients creator on creator.id=j.created_by_client_id
left join lateral (
    select task_id,task_name from dorf.job_tasks where job_id=j.id order by sequence desc limit 1
) current_task on true
where j.id=$1
for update of j
`

type GetJobForSandboxActionAuthorizationRow struct {
	CreatedByClientID       string
	CreatedByClientName     string
	ClientReference         string
	ThreadHarness           string
	ThreadID                string
	ID                      string
	AdmissionKey            string
	WorkflowName            core.WorkflowName
	WorkflowRevision        string
	AgentsMd                string
	SandboxProfile          string
	SandboxProfileRevision  string
	ProviderConnection      string
	Model                   string
	ReasoningEffort         string
	KeepRunning             bool
	AdmissionOpen           bool
	CleanupState            core.CleanupState
	CurrentTaskID           string
	CurrentTaskName         string
	WorkflowAttention       string
	WorkflowAttentionSource string
	WorkflowAttentionAt     sql.NullTime
	CleanupAttention        string
	AdmittedAt              time.Time
	CleanedAt               sql.NullTime
}

func (q *Queries) GetJobForSandboxActionAuthorization(ctx context.Context, jobID string) (GetJobForSandboxActionAuthorizationRow, error) {
	row := q.db.QueryRowContext(ctx, getJobForSandboxActionAuthorization, jobID)
	var i GetJobForSandboxActionAuthorizationRow
	err := row.Scan(
		&i.CreatedByClientID,
		&i.CreatedByClientName,
		&i.ClientReference,
		&i.ThreadHarness,
		&i.ThreadID,
		&i.ID,
		&i.AdmissionKey,
		&i.WorkflowName,
		&i.WorkflowRevision,
		&i.AgentsMd,
		&i.SandboxProfile,
		&i.SandboxProfileRevision,
		&i.ProviderConnection,
		&i.Model,
		&i.ReasoningEffort,
		&i.KeepRunning,
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.CurrentTaskID,
		&i.CurrentTaskName,
		&i.WorkflowAttention,
		&i.WorkflowAttentionSource,
		&i.WorkflowAttentionAt,
		&i.CleanupAttention,
		&i.AdmittedAt,
		&i.CleanedAt,
	)
	return i, err
}

const getJobForSandboxEnsure = `-- name: GetJobForSandboxEnsure :one
select admission_open,cleanup_state
from dorf.jobs
where id=$1
for update
`

type GetJobForSandboxEnsureRow struct {
	AdmissionOpen bool
	CleanupState  core.CleanupState
}

func (q *Queries) GetJobForSandboxEnsure(ctx context.Context, jobID string) (GetJobForSandboxEnsureRow, error) {
	row := q.db.QueryRowContext(ctx, getJobForSandboxEnsure, jobID)
	var i GetJobForSandboxEnsureRow
	err := row.Scan(&i.AdmissionOpen, &i.CleanupState)
	return i, err
}

const getJobSandboxProfileForUpdate = `-- name: GetJobSandboxProfileForUpdate :one
select sandbox_profile
from dorf.jobs
where id=$1
for update
`

func (q *Queries) GetJobSandboxProfileForUpdate(ctx context.Context, jobID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getJobSandboxProfileForUpdate, jobID)
	var sandbox_profile string
	err := row.Scan(&sandbox_profile)
	return sandbox_profile, err
}

const insertAdmittedJob = `-- name: InsertAdmittedJob :execrows
insert into dorf.jobs(
    id,admission_key,workflow_name,workflow_revision,agents_md,created_by_client_id,client_reference,
    sandbox_profile,sandbox_profile_revision,provider_connection,model,reasoning_effort,keep_running
)
values(
    $1,$2,$3,$4,
    $5,nullif($6::text,''),$7,
    $8,$9,$10,$11,
    $12,$13
)
on conflict do nothing
`

type InsertAdmittedJobParams struct {
	ID                     string
	AdmissionKey           string
	WorkflowName           core.WorkflowName
	WorkflowRevision       string
	AgentsMd               string
	CreatedByClientID      string
	ClientReference        string
	SandboxProfile         string
	SandboxProfileRevision string
	ProviderConnection     string
	Model                  string
	ReasoningEffort        string
	KeepRunning            bool
}

func (q *Queries) InsertAdmittedJob(ctx context.Context, arg InsertAdmittedJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAdmittedJob,
		arg.ID,
		arg.AdmissionKey,
		arg.WorkflowName,
		arg.WorkflowRevision,
		arg.AgentsMd,
		arg.CreatedByClientID,
		arg.ClientReference,
		arg.SandboxProfile,
		arg.SandboxProfileRevision,
		arg.ProviderConnection,
		arg.Model,
		arg.ReasoningEffort,
		arg.KeepRunning,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertJobTask = `-- name: InsertJobTask :execrows
insert into dorf.job_tasks(job_id,sequence,task_id,task_name)
values($1,$2,$3,$4)
on conflict(task_id) do nothing
`

type InsertJobTaskParams struct {
	JobID    string
	Sequence int64
	TaskID   string
	TaskName string
}

func (q *Queries) InsertJobTask(ctx context.Context, arg InsertJobTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertJobTask,
		arg.JobID,
		arg.Sequence,
		arg.TaskID,
		arg.TaskName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listJobTasks = `-- name: ListJobTasks :many
select job_id,sequence,task_id,task_name,attached_at
from dorf.job_tasks
where job_id=$1
order by sequence
`

func (q *Queries) ListJobTasks(ctx context.Context, jobID string) ([]DorfJobTask, error) {
	rows, err := q.db.QueryContext(ctx, listJobTasks, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DorfJobTask
	for rows.Next() {
		var i DorfJobTask
		if err := rows.Scan(
			&i.JobID,
			&i.Sequence,
			&i.TaskID,
			&i.TaskName,
			&i.AttachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportedJobs = `-- name: ListSupportedJobs :many
select j.id,j.workflow_name,j.workflow_revision,j.admitted_at,
       coalesce(j.created_by_client_id,'') as created_by_client_id,coalesce(creator.name,'') as created_by_client_name,j.client_reference
from dorf.jobs j
left join dorf.control_clients creator on creator.id=j.created_by_client_id
where j.workflow_name='' and j.workflow_revision=''
  and (
        not $1::boolean or
        j.admitted_at < $2::timestamptz or
        (j.admitted_at=$2::timestamptz and j.id < $3::text)
      )
order by j.admitted_at desc,j.id desc
limit $4
`

type ListSupportedJobsParams struct {
	HasCursor        bool
	CursorAdmittedAt time.Time
	CursorID         string
	PageSize         int32
}

type ListSupportedJobsRow struct {
	ID                  string
	WorkflowName        core.WorkflowName
	WorkflowRevision    string
	AdmittedAt          time.Time
	CreatedByClientID   string
	CreatedByClientName string
	ClientReference     string
}

func (q *Queries) ListSupportedJobs(ctx context.Context, arg ListSupportedJobsParams) ([]ListSupportedJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupportedJobs,
		arg.HasCursor,
		arg.CursorAdmittedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupportedJobsRow
	for rows.Next() {
		var i ListSupportedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowName,
			&i.WorkflowRevision,
			&i.AdmittedAt,
			&i.CreatedByClientID,
			&i.CreatedByClientName,
			&i.ClientReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCleanupScheduled = `-- name: MarkCleanupScheduled :execrows
update dorf.jobs
set cleanup_state='scheduled'
where id=$1 and not admission_open and cleanup_state='requested'
`

func (q *Queries) MarkCleanupScheduled(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCleanupScheduled, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCleanupAttention = `-- name: SetCleanupAttention :execrows
update dorf.jobs
set cleanup_attention=nullif($1::text,'')
where id=$2 and cleanup_state<>'complete'
`

type SetCleanupAttentionParams struct {
	Detail string
	JobID  string
}

func (q *Queries) SetCleanupAttention(ctx context.Context, arg SetCleanupAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCleanupAttention, arg.Detail, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setWorkflowAttention = `-- name: SetWorkflowAttention :execrows
update dorf.jobs
set workflow_attention=$1,
    workflow_attention_source=$2,
    workflow_attention_at=clock_timestamp()
where id=$3
  and (workflow_attention_source is null or workflow_attention_source=$2)
`

type SetWorkflowAttentionParams struct {
	Detail sql.NullString
	Source sql.NullString
	JobID  string
}

func (q *Queries) SetWorkflowAttention(ctx context.Context, arg SetWorkflowAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setWorkflowAttention, arg.Detail, arg.Source, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
