// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbsql

import (
	"context"
	"database/sql"

	"github.com/aphronio/dorf/internal/spine"
)

const advanceJobRevision = `-- name: AdvanceJobRevision :execrows
update dorf.jobs
set revision=$1,workflow_phase='checking',workflow_attention=null
where id=$2 and revision=$3
`

type AdvanceJobRevisionParams struct {
	Revision          string
	JobID             string
	ComparisonBaseOID string
}

func (q *Queries) AdvanceJobRevision(ctx context.Context, arg AdvanceJobRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceJobRevision, arg.Revision, arg.JobID, arg.ComparisonBaseOID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const attachMessageTask = `-- name: AttachMessageTask :execrows
update dorf.jobs
set task_id=coalesce(task_id,$1)
where id=$2 and admission_open
  and (task_id is null or task_id=$1)
`

type AttachMessageTaskParams struct {
	TaskID sql.NullString
	JobID  string
}

func (q *Queries) AttachMessageTask(ctx context.Context, arg AttachMessageTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, attachMessageTask, arg.TaskID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const blockDelivery = `-- name: BlockDelivery :exec
update dorf.jobs
set workflow_phase='blocked',workflow_attention=$1
where id=$2
`

type BlockDeliveryParams struct {
	Reason sql.NullString
	JobID  string
}

func (q *Queries) BlockDelivery(ctx context.Context, arg BlockDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, blockDelivery, arg.Reason, arg.JobID)
	return err
}

const blockWorkflow = `-- name: BlockWorkflow :execrows
update dorf.jobs
set workflow_phase='blocked',workflow_attention=$1
where id=$2
`

type BlockWorkflowParams struct {
	Reason sql.NullString
	JobID  string
}

func (q *Queries) BlockWorkflow(ctx context.Context, arg BlockWorkflowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, blockWorkflow, arg.Reason, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeAdmission = `-- name: CloseAdmission :execrows
update dorf.jobs
set admission_open=false,workflow_attention=null
where id=$1
`

func (q *Queries) CloseAdmission(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeAdmission, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeUnchangedRun = `-- name: CompleteUnchangedRun :execrows
update dorf.jobs
set workflow_phase=case when exists (
      select 1 from dorf.github_proposals p
      where p.job_id=dorf.jobs.id and p.proposed_revision=dorf.jobs.revision
        and p.observed_remote_head=dorf.jobs.revision
    ) then 'published' else 'blocked' end,
    workflow_attention=case when exists (
      select 1 from dorf.github_proposals p
      where p.job_id=dorf.jobs.id and p.proposed_revision=dorf.jobs.revision
        and p.observed_remote_head=dorf.jobs.revision
    ) then null else $1 end
where id=$2 and revision=$3
  and workflow_phase='implementing'
`

type CompleteUnchangedRunParams struct {
	Reason   sql.NullString
	JobID    string
	Revision string
}

func (q *Queries) CompleteUnchangedRun(ctx context.Context, arg CompleteUnchangedRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeUnchangedRun, arg.Reason, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAdmittedJobForUpdate = `-- name: GetAdmittedJobForUpdate :one
select id,admission_key,goal,repository,revision,branch,provider_connection,
       model,reasoning_effort,coalesce(github_repository,'') as github_repository,
       coalesce(github_installation_id,'') as github_installation_id,
       coalesce(base_branch,'') as base_branch
from dorf.jobs
where admission_key=$1
for update
`

type GetAdmittedJobForUpdateRow struct {
	ID                   string
	AdmissionKey         string
	Goal                 string
	Repository           string
	Revision             string
	Branch               string
	ProviderConnection   string
	Model                string
	ReasoningEffort      string
	GithubRepository     string
	GithubInstallationID string
	BaseBranch           string
}

func (q *Queries) GetAdmittedJobForUpdate(ctx context.Context, admissionKey string) (GetAdmittedJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getAdmittedJobForUpdate, admissionKey)
	var i GetAdmittedJobForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.AdmissionKey,
		&i.Goal,
		&i.Repository,
		&i.Revision,
		&i.Branch,
		&i.ProviderConnection,
		&i.Model,
		&i.ReasoningEffort,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.BaseBranch,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
select j.id,j.admission_key,j.goal,j.repository,j.revision,coalesce(rv.generation,0)::integer as revision_generation,j.starting_revision,j.branch,
       coalesce(j.github_repository,'') as github_repository,coalesce(j.github_installation_id,'') as github_installation_id,
       coalesce(j.base_branch,'') as base_branch,
       j.provider_connection,j.model,j.reasoning_effort,j.admission_open,
       j.cleanup_state,coalesce(j.task_id,'') as task_id,coalesce(j.cleanup_task_id,'') as cleanup_task_id,
       j.workflow_phase,coalesce(j.workflow_attention,'') as workflow_attention,coalesce(j.cleanup_attention,'') as cleanup_attention
from dorf.jobs j
left join dorf.revisions rv on rv.job_id=j.id and rv.oid=j.revision
where j.id=$1
`

type GetJobRow struct {
	ID                   string
	AdmissionKey         string
	Goal                 string
	Repository           string
	Revision             string
	RevisionGeneration   int32
	StartingRevision     string
	Branch               string
	GithubRepository     string
	GithubInstallationID string
	BaseBranch           string
	ProviderConnection   string
	Model                string
	ReasoningEffort      string
	AdmissionOpen        bool
	CleanupState         spine.CleanupState
	TaskID               string
	CleanupTaskID        string
	WorkflowPhase        string
	WorkflowAttention    string
	CleanupAttention     string
}

func (q *Queries) GetJob(ctx context.Context, jobID string) (GetJobRow, error) {
	row := q.db.QueryRowContext(ctx, getJob, jobID)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.AdmissionKey,
		&i.Goal,
		&i.Repository,
		&i.Revision,
		&i.RevisionGeneration,
		&i.StartingRevision,
		&i.Branch,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.BaseBranch,
		&i.ProviderConnection,
		&i.Model,
		&i.ReasoningEffort,
		&i.AdmissionOpen,
		&i.CleanupState,
		&i.TaskID,
		&i.CleanupTaskID,
		&i.WorkflowPhase,
		&i.WorkflowAttention,
		&i.CleanupAttention,
	)
	return i, err
}

const getJobAdmissionForUpdate = `-- name: GetJobAdmissionForUpdate :one
select admission_open,workflow_phase
from dorf.jobs
where id=$1
for update
`

type GetJobAdmissionForUpdateRow struct {
	AdmissionOpen bool
	WorkflowPhase string
}

func (q *Queries) GetJobAdmissionForUpdate(ctx context.Context, jobID string) (GetJobAdmissionForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getJobAdmissionForUpdate, jobID)
	var i GetJobAdmissionForUpdateRow
	err := row.Scan(&i.AdmissionOpen, &i.WorkflowPhase)
	return i, err
}

const getRevisionJobForUpdate = `-- name: GetRevisionJobForUpdate :one
select revision,branch,workflow_phase
from dorf.jobs
where id=$1
for update
`

type GetRevisionJobForUpdateRow struct {
	Revision      string
	Branch        string
	WorkflowPhase string
}

func (q *Queries) GetRevisionJobForUpdate(ctx context.Context, jobID string) (GetRevisionJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getRevisionJobForUpdate, jobID)
	var i GetRevisionJobForUpdateRow
	err := row.Scan(&i.Revision, &i.Branch, &i.WorkflowPhase)
	return i, err
}

const getRevisionPhaseForUpdate = `-- name: GetRevisionPhaseForUpdate :one
select revision,workflow_phase
from dorf.jobs
where id=$1
for update
`

type GetRevisionPhaseForUpdateRow struct {
	Revision      string
	WorkflowPhase string
}

func (q *Queries) GetRevisionPhaseForUpdate(ctx context.Context, jobID string) (GetRevisionPhaseForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getRevisionPhaseForUpdate, jobID)
	var i GetRevisionPhaseForUpdateRow
	err := row.Scan(&i.Revision, &i.WorkflowPhase)
	return i, err
}

const getSetupActionIDForUpdate = `-- name: GetSetupActionIDForUpdate :one
select coalesce(setup_action_id,'') as setup_action_id
from dorf.jobs
where id=$1
for update
`

func (q *Queries) GetSetupActionIDForUpdate(ctx context.Context, jobID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetupActionIDForUpdate, jobID)
	var setup_action_id string
	err := row.Scan(&setup_action_id)
	return setup_action_id, err
}

const getSetupRetryJobForUpdate = `-- name: GetSetupRetryJobForUpdate :one
select workflow_phase,coalesce(setup_action_id,'') as setup_action_id,admission_open
from dorf.jobs
where id=$1
for update
`

type GetSetupRetryJobForUpdateRow struct {
	WorkflowPhase string
	SetupActionID string
	AdmissionOpen bool
}

func (q *Queries) GetSetupRetryJobForUpdate(ctx context.Context, jobID string) (GetSetupRetryJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getSetupRetryJobForUpdate, jobID)
	var i GetSetupRetryJobForUpdateRow
	err := row.Scan(&i.WorkflowPhase, &i.SetupActionID, &i.AdmissionOpen)
	return i, err
}

const getWorkflowPhaseForUpdate = `-- name: GetWorkflowPhaseForUpdate :one
select workflow_phase
from dorf.jobs
where id=$1
for update
`

func (q *Queries) GetWorkflowPhaseForUpdate(ctx context.Context, jobID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowPhaseForUpdate, jobID)
	var workflow_phase string
	err := row.Scan(&workflow_phase)
	return workflow_phase, err
}

const insertAdmittedJob = `-- name: InsertAdmittedJob :execrows
insert into dorf.jobs(
    id,admission_key,goal,repository,revision,starting_revision,branch,
    provider_connection,model,reasoning_effort,
    github_repository,github_installation_id,base_branch
)
values(
    $1,$2,$3,$4,
    $5,$5,$6,
    $7,$8,
    $9,$10,
    $11,$12
)
on conflict(admission_key) do nothing
`

type InsertAdmittedJobParams struct {
	ID                   string
	AdmissionKey         string
	Goal                 string
	Repository           string
	Revision             string
	Branch               string
	ProviderConnection   string
	Model                string
	ReasoningEffort      string
	GithubRepository     sql.NullString
	GithubInstallationID sql.NullString
	BaseBranch           sql.NullString
}

func (q *Queries) InsertAdmittedJob(ctx context.Context, arg InsertAdmittedJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAdmittedJob,
		arg.ID,
		arg.AdmissionKey,
		arg.Goal,
		arg.Repository,
		arg.Revision,
		arg.Branch,
		arg.ProviderConnection,
		arg.Model,
		arg.ReasoningEffort,
		arg.GithubRepository,
		arg.GithubInstallationID,
		arg.BaseBranch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertInitialRevision = `-- name: InsertInitialRevision :exec
insert into dorf.revisions(job_id,oid,branch,generation)
values($1,$2,$3,0)
on conflict do nothing
`

type InsertInitialRevisionParams struct {
	JobID  string
	OID    string
	Branch string
}

func (q *Queries) InsertInitialRevision(ctx context.Context, arg InsertInitialRevisionParams) error {
	_, err := q.db.ExecContext(ctx, insertInitialRevision, arg.JobID, arg.OID, arg.Branch)
	return err
}

const insertRevision = `-- name: InsertRevision :exec
insert into dorf.revisions(job_id,oid,comparison_base_oid,tree_oid,branch,generation,evidence_id)
values($1,$2,$3::text,$4::text,
       $5,$6,$7::text)
`

type InsertRevisionParams struct {
	JobID             string
	OID               string
	ComparisonBaseOID string
	TreeOID           string
	Branch            string
	Generation        int32
	EvidenceID        string
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) error {
	_, err := q.db.ExecContext(ctx, insertRevision,
		arg.JobID,
		arg.OID,
		arg.ComparisonBaseOID,
		arg.TreeOID,
		arg.Branch,
		arg.Generation,
		arg.EvidenceID,
	)
	return err
}

const markReady = `-- name: MarkReady :execrows
update dorf.jobs
set workflow_phase='ready',workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='checking'
`

type MarkReadyParams struct {
	JobID    string
	Revision string
}

func (q *Queries) MarkReady(ctx context.Context, arg MarkReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markReady, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const nextRevisionGeneration = `-- name: NextRevisionGeneration :one
select (coalesce(max(generation),0)+1)::integer
from dorf.revisions
where job_id=$1
`

func (q *Queries) NextRevisionGeneration(ctx context.Context, jobID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, nextRevisionGeneration, jobID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const returnFailedCheckToImplementation = `-- name: ReturnFailedCheckToImplementation :execrows
update dorf.jobs
set workflow_phase='implementing',workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='checking'
`

type ReturnFailedCheckToImplementationParams struct {
	JobID    string
	Revision string
}

func (q *Queries) ReturnFailedCheckToImplementation(ctx context.Context, arg ReturnFailedCheckToImplementationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, returnFailedCheckToImplementation, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectInitialSetupAction = `-- name: SelectInitialSetupAction :execrows
update dorf.jobs
set setup_action_id=$1
where id=$2 and setup_action_id is null
`

type SelectInitialSetupActionParams struct {
	ActionID sql.NullString
	JobID    string
}

func (q *Queries) SelectInitialSetupAction(ctx context.Context, arg SelectInitialSetupActionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, selectInitialSetupAction, arg.ActionID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectSetupRetry = `-- name: SelectSetupRetry :execrows
update dorf.jobs
set setup_action_id=$1,workflow_phase='setup',workflow_attention=null
where id=$2 and setup_action_id=$3
  and workflow_phase='blocked'
`

type SelectSetupRetryParams struct {
	ActionID         sql.NullString
	JobID            string
	PreviousActionID sql.NullString
}

func (q *Queries) SelectSetupRetry(ctx context.Context, arg SelectSetupRetryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, selectSetupRetry, arg.ActionID, arg.JobID, arg.PreviousActionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCleanupAttention = `-- name: SetCleanupAttention :execrows
update dorf.jobs
set cleanup_attention=nullif($1::text,'')
where id=$2 and cleanup_state<>'complete'
`

type SetCleanupAttentionParams struct {
	Detail string
	JobID  string
}

func (q *Queries) SetCleanupAttention(ctx context.Context, arg SetCleanupAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCleanupAttention, arg.Detail, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCleanupTaskID = `-- name: SetCleanupTaskID :execrows
update dorf.jobs
set cleanup_task_id=coalesce(cleanup_task_id,$1),
    cleanup_state=case when cleanup_state='complete' or cleaned_at is not null then 'complete' else 'scheduled' end
where id=$2
  and (cleanup_task_id is null or cleanup_task_id=$1)
`

type SetCleanupTaskIDParams struct {
	CleanupTaskID sql.NullString
	JobID         string
}

func (q *Queries) SetCleanupTaskID(ctx context.Context, arg SetCleanupTaskIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCleanupTaskID, arg.CleanupTaskID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setWorkflowPhaseAfterSetup = `-- name: SetWorkflowPhaseAfterSetup :execrows
update dorf.jobs
set workflow_phase=$1,
    workflow_attention=nullif($2::text,'')
where id=$3 and workflow_phase in ('setup','blocked')
`

type SetWorkflowPhaseAfterSetupParams struct {
	WorkflowPhase     string
	WorkflowAttention string
	JobID             string
}

func (q *Queries) SetWorkflowPhaseAfterSetup(ctx context.Context, arg SetWorkflowPhaseAfterSetupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setWorkflowPhaseAfterSetup, arg.WorkflowPhase, arg.WorkflowAttention, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
