// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package dbsql

import (
	"context"

	"github.com/aphronio/dorf/internal/spine"
)

const countUnsettledInputs = `-- name: CountUnsettledInputs :one
select count(*)
from dorf.job_messages m
left join dorf.agent_runs ar on ar.message_id=m.id
where m.job_id=$1
  and ar.role='implement' and ar.state not in ('completed','failed','interrupted')
`

func (q *Queries) CountUnsettledInputs(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnsettledInputs, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveImplementationTurn = `-- name: GetActiveImplementationTurn :one
select coalesce(turn_id,'') as turn_id,coalesce(harness,'') as harness,
       coalesce(thread_id,'') as thread_id,role
from dorf.agent_runs
where job_id=$1 and state='active' and turn_id is not null
  and role='implement'
order by started_at,id
limit 1
`

type GetActiveImplementationTurnRow struct {
	TurnID   string
	Harness  string
	ThreadID string
	Role     string
}

func (q *Queries) GetActiveImplementationTurn(ctx context.Context, jobID string) (GetActiveImplementationTurnRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveImplementationTurn, jobID)
	var i GetActiveImplementationTurnRow
	err := row.Scan(
		&i.TurnID,
		&i.Harness,
		&i.ThreadID,
		&i.Role,
	)
	return i, err
}

const getCheckMessage = `-- name: GetCheckMessage :one
select id,job_id,from_kind,from_id,sequence,input,delivery_intent,
       coalesce(steer_target_turn_id,'') as steer_target_turn_id
from dorf.job_messages
where job_id=$1 and from_kind='workflow' and from_id=$2
`

type GetCheckMessageParams struct {
	JobID  string
	FromID string
}

type GetCheckMessageRow struct {
	ID                string
	JobID             string
	FromKind          spine.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	DeliveryIntent    spine.MessageDeliveryIntent
	SteerTargetTurnID string
}

func (q *Queries) GetCheckMessage(ctx context.Context, arg GetCheckMessageParams) (GetCheckMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getCheckMessage, arg.JobID, arg.FromID)
	var i GetCheckMessageRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.DeliveryIntent,
		&i.SteerTargetTurnID,
	)
	return i, err
}

const getFirstUnsettledInput = `-- name: GetFirstUnsettledInput :one
select m.sequence,coalesce(ar.state,'') as state,coalesce(ar.attention,'') as attention
from dorf.job_messages m
left join dorf.agent_runs ar on ar.message_id=m.id
where m.job_id=$1
  and ar.role='implement' and ar.state not in ('completed','failed','interrupted')
order by m.sequence
limit 1
`

type GetFirstUnsettledInputRow struct {
	Sequence  int64
	State     spine.AgentRunState
	Attention string
}

func (q *Queries) GetFirstUnsettledInput(ctx context.Context, jobID string) (GetFirstUnsettledInputRow, error) {
	row := q.db.QueryRowContext(ctx, getFirstUnsettledInput, jobID)
	var i GetFirstUnsettledInputRow
	err := row.Scan(&i.Sequence, &i.State, &i.Attention)
	return i, err
}

const getInitialMessage = `-- name: GetInitialMessage :one
select id,sequence,input
from dorf.job_messages
where job_id=$1 and from_kind='human' and from_id=$2
`

type GetInitialMessageParams struct {
	JobID  string
	FromID string
}

type GetInitialMessageRow struct {
	ID       string
	Sequence int64
	Input    string
}

func (q *Queries) GetInitialMessage(ctx context.Context, arg GetInitialMessageParams) (GetInitialMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getInitialMessage, arg.JobID, arg.FromID)
	var i GetInitialMessageRow
	err := row.Scan(&i.ID, &i.Sequence, &i.Input)
	return i, err
}

const getLatestFollowRun = `-- name: GetLatestFollowRun :one
select ar.id,ar.job_id,ar.state,ar.role
from dorf.job_messages m
join dorf.agent_runs ar on ar.message_id=m.id
where m.job_id=$1 and m.delivery_intent='follow' and ar.role='implement'
order by m.sequence desc
limit 1
`

type GetLatestFollowRunRow struct {
	ID    string
	JobID string
	State spine.AgentRunState
	Role  string
}

func (q *Queries) GetLatestFollowRun(ctx context.Context, jobID string) (GetLatestFollowRunRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestFollowRun, jobID)
	var i GetLatestFollowRunRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.State,
		&i.Role,
	)
	return i, err
}

const getMessageBySender = `-- name: GetMessageBySender :one
select id,job_id,from_kind,from_id,sequence,input,delivery_intent,
       coalesce(steer_target_turn_id,'') as steer_target_turn_id
from dorf.job_messages
where job_id=$1 and from_kind=$2
  and from_id=$3
`

type GetMessageBySenderParams struct {
	JobID    string
	FromKind spine.MessageFromKind
	FromID   string
}

type GetMessageBySenderRow struct {
	ID                string
	JobID             string
	FromKind          spine.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	DeliveryIntent    spine.MessageDeliveryIntent
	SteerTargetTurnID string
}

func (q *Queries) GetMessageBySender(ctx context.Context, arg GetMessageBySenderParams) (GetMessageBySenderRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageBySender, arg.JobID, arg.FromKind, arg.FromID)
	var i GetMessageBySenderRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.DeliveryIntent,
		&i.SteerTargetTurnID,
	)
	return i, err
}

const insertInitialMessage = `-- name: InsertInitialMessage :exec
insert into dorf.job_messages(id,job_id,from_kind,from_id,sequence,input)
values($1,$2,'human',$3,1,$4)
on conflict(job_id,from_kind,from_id) do nothing
`

type InsertInitialMessageParams struct {
	ID     string
	JobID  string
	FromID string
	Input  string
}

func (q *Queries) InsertInitialMessage(ctx context.Context, arg InsertInitialMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertInitialMessage,
		arg.ID,
		arg.JobID,
		arg.FromID,
		arg.Input,
	)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
insert into dorf.job_messages(
    id,job_id,from_kind,from_id,sequence,input,delivery_intent,steer_target_turn_id
)
values(
    $1,$2,$3,$4,
    $5,$6,$7,
    nullif($8::text,'')
)
`

type InsertMessageParams struct {
	ID                string
	JobID             string
	FromKind          spine.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	DeliveryIntent    spine.MessageDeliveryIntent
	SteerTargetTurnID string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.JobID,
		arg.FromKind,
		arg.FromID,
		arg.Sequence,
		arg.Input,
		arg.DeliveryIntent,
		arg.SteerTargetTurnID,
	)
	return err
}

const listMessages = `-- name: ListMessages :many
select m.id,m.job_id,m.from_kind,m.from_id,m.sequence,m.input,m.delivery_intent,
       coalesce(m.steer_target_turn_id,'') as steer_target_turn_id,
       coalesce(ar.id,'') as agent_run_id,coalesce(ar.state,'') as state,
       coalesce(ar.role,'') as role,
       coalesce(ar.harness,'') as harness,coalesce(ar.thread_id,'') as thread_id,
       coalesce(ar.turn_id,'') as turn_id,
       coalesce(ar.turn_outcome,'') as turn_outcome,
       coalesce(ar.attention,'') as attention,
       (ar.turn_id is not null)::boolean as delivered
from dorf.job_messages m
left join dorf.agent_runs ar on ar.message_id=m.id
where m.job_id=$1
order by m.sequence
`

type ListMessagesRow struct {
	ID                string
	JobID             string
	FromKind          spine.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	DeliveryIntent    spine.MessageDeliveryIntent
	SteerTargetTurnID string
	AgentRunID        string
	State             spine.AgentRunState
	Role              string
	Harness           string
	ThreadID          string
	TurnID            string
	TurnOutcome       string
	Attention         string
	Delivered         bool
}

func (q *Queries) ListMessages(ctx context.Context, jobID string) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.FromKind,
			&i.FromID,
			&i.Sequence,
			&i.Input,
			&i.DeliveryIntent,
			&i.SteerTargetTurnID,
			&i.AgentRunID,
			&i.State,
			&i.Role,
			&i.Harness,
			&i.ThreadID,
			&i.TurnID,
			&i.TurnOutcome,
			&i.Attention,
			&i.Delivered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMessageSequence = `-- name: NextMessageSequence :one
select (coalesce(max(sequence),0)+1)::bigint
from dorf.job_messages
where job_id=$1
`

func (q *Queries) NextMessageSequence(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextMessageSequence, jobID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextWakeSequence = `-- name: NextWakeSequence :one
select coalesce(
    (
        select m.sequence
        from dorf.jobs j
        join dorf.actions a on a.id=j.setup_action_id
        join dorf.job_messages m
          on m.job_id=j.id and m.from_kind='workflow' and m.from_id=a.scope_key
        where j.id=$1 and j.workflow_phase='setup'
          and a.kind='repository-setup' and a.scope_key<>''
          and a.state in ('pending','uncertain')
    ),
    (
        select min(m.sequence)
        from dorf.job_messages m
        join dorf.agent_runs ar on ar.message_id=m.id
        where m.job_id=$1 and m.sequence>1 and ar.role='implement'
          and ar.state='pending' and ar.turn_id is null
          and not exists (
              select 1
              from dorf.job_messages earlier
              join dorf.agent_runs earlier_run on earlier_run.message_id=earlier.id
              where earlier.job_id=m.job_id and earlier.sequence<m.sequence
                and earlier_run.role='implement'
                and earlier_run.state not in ('completed','failed','interrupted')
          )
    ),
    (select coalesce(max(sequence),0)+1 from dorf.job_messages where job_id=$1)
)::bigint
`

func (q *Queries) NextWakeSequence(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextWakeSequence, jobID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const reopenPublishedForFollow = `-- name: ReopenPublishedForFollow :execrows
update dorf.jobs
set workflow_phase='implementing',workflow_attention=null
where id=$1 and workflow_phase='published'
  and not exists (select 1 from dorf.job_outcomes where job_id=dorf.jobs.id)
`

func (q *Queries) ReopenPublishedForFollow(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, reopenPublishedForFollow, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
