// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package dbsql

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/aphronio/dorf/internal/core"
)

const agentMessageNeedsSkillRefresh = `-- name: AgentMessageNeedsSkillRefresh :one
with current_message as (
    select m.id,m.job_id,m.sequence,m.delivery_intent,ar.sandbox_id,ar.role
    from dorf.job_messages m join dorf.agent_runs ar on ar.message_id=m.id
    where m.id=$1
), previous_turn as (
    select m.sequence,ar.turn_id
    from current_message current
    join dorf.job_messages m on m.job_id=current.job_id and m.sequence<current.sequence
    join dorf.agent_runs ar on ar.message_id=m.id
    where m.delivery_intent='follow' and ar.turn_id is not null
      and ar.sandbox_id=current.sandbox_id and ar.role=current.role
    order by m.sequence desc limit 1
)
select exists (
    select 1
    from current_message current
    join dorf.job_messages requested on requested.job_id=current.job_id
    join dorf.agent_runs request_run on request_run.message_id=requested.id
    where current.delivery_intent='follow' and requested.refresh_skills
      and request_run.sandbox_id=current.sandbox_id and request_run.role=current.role
      and (
        (requested.delivery_intent='follow' and requested.sequence<=current.sequence
          and requested.sequence>coalesce((select sequence from previous_turn),0))
        or (requested.delivery_intent='steer'
          and requested.steer_target_turn_id=(select turn_id from previous_turn))
      )
) as refresh_skills
`

func (q *Queries) AgentMessageNeedsSkillRefresh(ctx context.Context, messageID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, agentMessageNeedsSkillRefresh, messageID)
	var refresh_skills bool
	err := row.Scan(&refresh_skills)
	return refresh_skills, err
}

const countUnsettledInputs = `-- name: CountUnsettledInputs :one
select count(*)
from dorf.job_messages m
left join dorf.agent_runs ar on ar.message_id=m.id
where m.job_id=$1
  and ar.state not in ('completed','failed','interrupted')
`

func (q *Queries) CountUnsettledInputs(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnsettledInputs, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveAgentTurn = `-- name: GetActiveAgentTurn :one
select coalesce(turn_id,'') as turn_id,coalesce(harness,'') as harness,
       coalesce(thread_id,'') as thread_id
from dorf.agent_runs ar
where ar.job_id=$1 and ar.state='active' and ar.turn_id is not null
  and not ar.interrupt_requested
  and ar.role=$2 and ar.sandbox_id=$3
  and (
    select count(*) from dorf.agent_runs active
    where active.job_id=$1 and active.state='active' and active.turn_id is not null
      and active.role=$2 and active.sandbox_id=$3
  )=1
`

type GetActiveAgentTurnParams struct {
	JobID     string
	Role      string
	SandboxID string
}

type GetActiveAgentTurnRow struct {
	TurnID   string
	Harness  string
	ThreadID string
}

func (q *Queries) GetActiveAgentTurn(ctx context.Context, arg GetActiveAgentTurnParams) (GetActiveAgentTurnRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveAgentTurn, arg.JobID, arg.Role, arg.SandboxID)
	var i GetActiveAgentTurnRow
	err := row.Scan(&i.TurnID, &i.Harness, &i.ThreadID)
	return i, err
}

const getFirstUnsettledInput = `-- name: GetFirstUnsettledInput :one
select m.sequence,coalesce(ar.state,'') as state,coalesce(ar.attention,'') as attention
from dorf.job_messages m
left join dorf.agent_runs ar on ar.message_id=m.id
where m.job_id=$1
  and ar.state not in ('completed','failed','interrupted')
order by m.sequence
limit 1
`

type GetFirstUnsettledInputRow struct {
	Sequence  int64
	State     core.AgentRunState
	Attention string
}

func (q *Queries) GetFirstUnsettledInput(ctx context.Context, jobID string) (GetFirstUnsettledInputRow, error) {
	row := q.db.QueryRowContext(ctx, getFirstUnsettledInput, jobID)
	var i GetFirstUnsettledInputRow
	err := row.Scan(&i.Sequence, &i.State, &i.Attention)
	return i, err
}

const getLatestAgentRun = `-- name: GetLatestAgentRun :one
select state,coalesce(turn_outcome,'') as turn_outcome,
       coalesce(harness,'') as harness,coalesce(thread_id,'') as thread_id
from dorf.agent_runs ar
join dorf.job_messages m on m.id=ar.message_id
where ar.job_id=$1 and ar.role=$2
order by m.sequence desc
limit 1
`

type GetLatestAgentRunParams struct {
	JobID string
	Role  string
}

type GetLatestAgentRunRow struct {
	State       core.AgentRunState
	TurnOutcome string
	Harness     string
	ThreadID    string
}

func (q *Queries) GetLatestAgentRun(ctx context.Context, arg GetLatestAgentRunParams) (GetLatestAgentRunRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentRun, arg.JobID, arg.Role)
	var i GetLatestAgentRunRow
	err := row.Scan(
		&i.State,
		&i.TurnOutcome,
		&i.Harness,
		&i.ThreadID,
	)
	return i, err
}

const getLatestTurnStartRun = `-- name: GetLatestTurnStartRun :one
select ar.id,ar.job_id,ar.state,ar.role,coalesce(ar.input_revision,'') as input_revision,
       exists (
           select 1 from dorf.evidence e
           where e.agent_run_id=ar.id and e.kind='git-revision'
       ) as observed
from dorf.job_messages m
join dorf.agent_runs ar on ar.message_id=m.id
where m.job_id=$1 and ar.role='implement'
  and m.delivery_intent='follow'
order by m.sequence desc
limit 1
`

type GetLatestTurnStartRunRow struct {
	ID            string
	JobID         string
	State         core.AgentRunState
	Role          string
	InputRevision string
	Observed      bool
}

func (q *Queries) GetLatestTurnStartRun(ctx context.Context, jobID string) (GetLatestTurnStartRunRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestTurnStartRun, jobID)
	var i GetLatestTurnStartRunRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.State,
		&i.Role,
		&i.InputRevision,
		&i.Observed,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
select id,job_id,from_kind,from_id,sequence,input,attachments,delivery_intent,
       coalesce(steer_target_turn_id,'') as steer_target_turn_id,admitted_at,refresh_skills
from dorf.job_messages
where id=$1
`

type GetMessageRow struct {
	ID                string
	JobID             string
	FromKind          core.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	Attachments       json.RawMessage
	DeliveryIntent    core.MessageDeliveryIntent
	SteerTargetTurnID string
	AdmittedAt        time.Time
	RefreshSkills     bool
}

func (q *Queries) GetMessage(ctx context.Context, messageID string) (GetMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getMessage, messageID)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.Attachments,
		&i.DeliveryIntent,
		&i.SteerTargetTurnID,
		&i.AdmittedAt,
		&i.RefreshSkills,
	)
	return i, err
}

const getMessageBySender = `-- name: GetMessageBySender :one
select id,job_id,from_kind,from_id,sequence,input,attachments,delivery_intent,requested_intent,
       coalesce(steer_target_turn_id,'') as steer_target_turn_id,admitted_at,refresh_skills
from dorf.job_messages
where job_id=$1 and from_kind=$2
  and from_id=$3
`

type GetMessageBySenderParams struct {
	JobID    string
	FromKind core.MessageFromKind
	FromID   string
}

type GetMessageBySenderRow struct {
	ID                string
	JobID             string
	FromKind          core.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	Attachments       json.RawMessage
	DeliveryIntent    core.MessageDeliveryIntent
	RequestedIntent   string
	SteerTargetTurnID string
	AdmittedAt        time.Time
	RefreshSkills     bool
}

func (q *Queries) GetMessageBySender(ctx context.Context, arg GetMessageBySenderParams) (GetMessageBySenderRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageBySender, arg.JobID, arg.FromKind, arg.FromID)
	var i GetMessageBySenderRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.Attachments,
		&i.DeliveryIntent,
		&i.RequestedIntent,
		&i.SteerTargetTurnID,
		&i.AdmittedAt,
		&i.RefreshSkills,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
insert into dorf.job_messages(
    id,job_id,from_kind,from_id,sequence,input,attachments,delivery_intent,steer_target_turn_id,requested_intent,refresh_skills
)
values(
    $1,$2,$3,$4,
    $5,$6,$7::jsonb,$8,
    nullif($9::text,''),$10,$11
)
`

type InsertMessageParams struct {
	ID                string
	JobID             string
	FromKind          core.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	Attachments       json.RawMessage
	DeliveryIntent    core.MessageDeliveryIntent
	SteerTargetTurnID string
	RequestedIntent   string
	RefreshSkills     bool
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.JobID,
		arg.FromKind,
		arg.FromID,
		arg.Sequence,
		arg.Input,
		arg.Attachments,
		arg.DeliveryIntent,
		arg.SteerTargetTurnID,
		arg.RequestedIntent,
		arg.RefreshSkills,
	)
	return err
}

const listDeliveries = `-- name: ListDeliveries :many
select m.id as message_id,m.job_id as message_job_id,m.from_kind,m.from_id,m.sequence,m.input,m.attachments,m.delivery_intent,
       coalesce(m.steer_target_turn_id,'') as steer_target_turn_id,m.refresh_skills,
       m.admitted_at,
       (ar.id is not null)::boolean as agent_run_present,
       coalesce(ar.id,'') as agent_run_id,coalesce(ar.job_id,'') as agent_run_job_id,
       coalesce(ar.message_id,'') as agent_run_message_id,coalesce(ar.state,'') as state,
       coalesce(ar.harness,'') as harness,coalesce(ar.thread_id,'') as thread_id,
       (ar.baseline_turn_id is not null)::boolean as baseline_recorded,
       coalesce(ar.baseline_turn_id,'') as baseline_turn_id,coalesce(ar.turn_id,'') as turn_id,
       coalesce(ar.turn_outcome,'') as turn_outcome,
       coalesce(ar.attention,'') as attention,coalesce(ar.role,'') as role,coalesce(ar.input_revision,'') as input_revision,
       coalesce(ar.capability,'') as capability,coalesce(ar.sandbox_id,'') as sandbox_id,
       coalesce(ar.submission_nonce,'') as submission_nonce,ar.started_at,ar.finished_at,
       exists (
           select 1 from dorf.agent_runs source
           where source.job_id=ar.job_id and source.sandbox_id=ar.sandbox_id
             and source.harness=ar.harness and source.thread_id=ar.thread_id
             and source.turn_id=coalesce(ar.turn_id,m.steer_target_turn_id)
             and source.interrupt_requested
       ) as interrupt_requested
from dorf.job_messages m
left join dorf.agent_runs ar on ar.message_id=m.id
where m.job_id=$1
order by m.sequence
`

type ListDeliveriesRow struct {
	MessageID          string
	MessageJobID       string
	FromKind           core.MessageFromKind
	FromID             string
	Sequence           int64
	Input              string
	Attachments        json.RawMessage
	DeliveryIntent     core.MessageDeliveryIntent
	SteerTargetTurnID  string
	RefreshSkills      bool
	AdmittedAt         time.Time
	AgentRunPresent    bool
	AgentRunID         string
	AgentRunJobID      string
	AgentRunMessageID  string
	State              core.AgentRunState
	Harness            string
	ThreadID           string
	BaselineRecorded   bool
	BaselineTurnID     string
	TurnID             string
	TurnOutcome        string
	Attention          string
	Role               string
	InputRevision      string
	Capability         string
	SandboxID          string
	SubmissionNonce    string
	StartedAt          sql.NullTime
	FinishedAt         sql.NullTime
	InterruptRequested bool
}

func (q *Queries) ListDeliveries(ctx context.Context, jobID string) ([]ListDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveries, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliveriesRow
	for rows.Next() {
		var i ListDeliveriesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.MessageJobID,
			&i.FromKind,
			&i.FromID,
			&i.Sequence,
			&i.Input,
			&i.Attachments,
			&i.DeliveryIntent,
			&i.SteerTargetTurnID,
			&i.RefreshSkills,
			&i.AdmittedAt,
			&i.AgentRunPresent,
			&i.AgentRunID,
			&i.AgentRunJobID,
			&i.AgentRunMessageID,
			&i.State,
			&i.Harness,
			&i.ThreadID,
			&i.BaselineRecorded,
			&i.BaselineTurnID,
			&i.TurnID,
			&i.TurnOutcome,
			&i.Attention,
			&i.Role,
			&i.InputRevision,
			&i.Capability,
			&i.SandboxID,
			&i.SubmissionNonce,
			&i.StartedAt,
			&i.FinishedAt,
			&i.InterruptRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMessageSequence = `-- name: NextMessageSequence :one
select (coalesce(max(sequence),0)+1)::bigint
from dorf.job_messages
where job_id=$1
`

func (q *Queries) NextMessageSequence(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextMessageSequence, jobID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextWakeSequence = `-- name: NextWakeSequence :one
select coalesce(
    (
        select min(m.sequence)
        from dorf.job_messages m
        join dorf.agent_runs ar on ar.message_id=m.id
        where m.job_id=$1
          and ar.state='pending' and ar.turn_id is null
          and not exists (
              select 1
              from dorf.job_messages earlier
              join dorf.agent_runs earlier_run on earlier_run.message_id=earlier.id
              where earlier.job_id=m.job_id and earlier.sequence<m.sequence
                and earlier_run.state not in ('completed','failed','interrupted')
          )
    ),
    (select coalesce(max(sequence),0)+1 from dorf.job_messages where job_id=$1)
)::bigint
`

func (q *Queries) NextWakeSequence(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextWakeSequence, jobID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
