// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package dbsql

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/aphronio/dorf/internal/core"
)

const agentMessageNeedsSkillRefresh = `-- name: AgentMessageNeedsSkillRefresh :one
with current_message as (
    select m.id,m.session_id,m.sequence,m.delivery_intent,ar.sandbox_id
    from dorf.session_messages m join dorf.agent_runs ar on ar.message_id=m.id
    where m.id=$1
), previous_turn as (
    select m.sequence,ar.turn_id
    from current_message current
    join dorf.session_messages m on m.session_id=current.session_id and m.sequence<current.sequence
    join dorf.agent_runs ar on ar.message_id=m.id
    where m.delivery_intent='follow' and ar.turn_id is not null
      and ar.sandbox_id=current.sandbox_id
    order by m.sequence desc limit 1
)
select exists (
    select 1
    from current_message current
    join dorf.session_messages requested on requested.session_id=current.session_id
    join dorf.agent_runs request_run on request_run.message_id=requested.id
    where current.delivery_intent='follow' and requested.refresh_skills
      and request_run.sandbox_id=current.sandbox_id
      and (
        (requested.delivery_intent='follow' and requested.sequence<=current.sequence
          and requested.sequence>coalesce((select sequence from previous_turn),0))
        or (requested.delivery_intent='steer'
          and requested.steer_target_turn_id=(select turn_id from previous_turn))
      )
) as refresh_skills
`

func (q *Queries) AgentMessageNeedsSkillRefresh(ctx context.Context, messageID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, agentMessageNeedsSkillRefresh, messageID)
	var refresh_skills bool
	err := row.Scan(&refresh_skills)
	return refresh_skills, err
}

const getActiveAgentTurn = `-- name: GetActiveAgentTurn :one
select coalesce(turn_id,'') as turn_id,coalesce(harness,'') as harness,
       coalesce(thread_id,'') as thread_id
from dorf.agent_runs ar
where ar.session_id=$1 and ar.state='active' and ar.turn_id is not null
  and not ar.interrupt_requested
  and ar.sandbox_id=$2
  and (
    select count(*) from dorf.agent_runs active
    where active.session_id=$1 and active.state='active' and active.turn_id is not null
      and active.sandbox_id=$2
  )=1
`

type GetActiveAgentTurnParams struct {
	SessionID string
	SandboxID string
}

type GetActiveAgentTurnRow struct {
	TurnID   string
	Harness  string
	ThreadID string
}

func (q *Queries) GetActiveAgentTurn(ctx context.Context, arg GetActiveAgentTurnParams) (GetActiveAgentTurnRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveAgentTurn, arg.SessionID, arg.SandboxID)
	var i GetActiveAgentTurnRow
	err := row.Scan(&i.TurnID, &i.Harness, &i.ThreadID)
	return i, err
}

const getMessage = `-- name: GetMessage :one
select id,session_id,from_kind,from_id,sequence,input,attachments,delivery_intent,
       requested_intent,coalesce(steer_target_turn_id,'') as steer_target_turn_id,admitted_at,refresh_skills,developer_instructions,observation
from dorf.session_messages
where id=$1
`

type GetMessageRow struct {
	ID                    string
	SessionID             string
	FromKind              core.MessageFromKind
	FromID                string
	Sequence              int64
	Input                 string
	Attachments           json.RawMessage
	DeliveryIntent        core.MessageDeliveryIntent
	RequestedIntent       string
	SteerTargetTurnID     string
	AdmittedAt            time.Time
	RefreshSkills         bool
	DeveloperInstructions sql.NullString
	Observation           bool
}

func (q *Queries) GetMessage(ctx context.Context, messageID string) (GetMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getMessage, messageID)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.Attachments,
		&i.DeliveryIntent,
		&i.RequestedIntent,
		&i.SteerTargetTurnID,
		&i.AdmittedAt,
		&i.RefreshSkills,
		&i.DeveloperInstructions,
		&i.Observation,
	)
	return i, err
}

const getMessageBySender = `-- name: GetMessageBySender :one
select id,session_id,from_kind,from_id,sequence,input,attachments,delivery_intent,requested_intent,
       coalesce(steer_target_turn_id,'') as steer_target_turn_id,admitted_at,refresh_skills,developer_instructions,observation
from dorf.session_messages
where session_id=$1 and from_kind=$2
  and from_id=$3
`

type GetMessageBySenderParams struct {
	SessionID string
	FromKind  core.MessageFromKind
	FromID    string
}

type GetMessageBySenderRow struct {
	ID                    string
	SessionID             string
	FromKind              core.MessageFromKind
	FromID                string
	Sequence              int64
	Input                 string
	Attachments           json.RawMessage
	DeliveryIntent        core.MessageDeliveryIntent
	RequestedIntent       string
	SteerTargetTurnID     string
	AdmittedAt            time.Time
	RefreshSkills         bool
	DeveloperInstructions sql.NullString
	Observation           bool
}

func (q *Queries) GetMessageBySender(ctx context.Context, arg GetMessageBySenderParams) (GetMessageBySenderRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageBySender, arg.SessionID, arg.FromKind, arg.FromID)
	var i GetMessageBySenderRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.Attachments,
		&i.DeliveryIntent,
		&i.RequestedIntent,
		&i.SteerTargetTurnID,
		&i.AdmittedAt,
		&i.RefreshSkills,
		&i.DeveloperInstructions,
		&i.Observation,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
insert into dorf.session_messages(
    id,session_id,from_kind,from_id,sequence,input,attachments,delivery_intent,steer_target_turn_id,requested_intent,refresh_skills,developer_instructions,observation
)
values(
    $1,$2,$3,$4,
    $5,$6,$7::jsonb,$8,
    nullif($9::text,''),$10,$11,$12,$13
)
`

type InsertMessageParams struct {
	ID                    string
	SessionID             string
	FromKind              core.MessageFromKind
	FromID                string
	Sequence              int64
	Input                 string
	Attachments           json.RawMessage
	DeliveryIntent        core.MessageDeliveryIntent
	SteerTargetTurnID     string
	RequestedIntent       string
	RefreshSkills         bool
	DeveloperInstructions sql.NullString
	Observation           bool
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.SessionID,
		arg.FromKind,
		arg.FromID,
		arg.Sequence,
		arg.Input,
		arg.Attachments,
		arg.DeliveryIntent,
		arg.SteerTargetTurnID,
		arg.RequestedIntent,
		arg.RefreshSkills,
		arg.DeveloperInstructions,
		arg.Observation,
	)
	return err
}

const listDeliveries = `-- name: ListDeliveries :many
select m.id as message_id,m.session_id as message_session_id,m.from_kind,m.from_id,m.sequence,m.input,m.attachments,m.delivery_intent,
       m.requested_intent,coalesce(m.steer_target_turn_id,'') as steer_target_turn_id,m.refresh_skills,m.developer_instructions,m.observation,
       m.admitted_at,
       (ar.id is not null)::boolean as agent_run_present,
       coalesce(ar.id,'') as agent_run_id,coalesce(ar.session_id,'') as agent_run_session_id,
       coalesce(ar.message_id,'') as agent_run_message_id,coalesce(ar.state,'') as state,
       coalesce(ar.harness,'') as harness,coalesce(ar.thread_id,'') as thread_id,
       (ar.baseline_turn_id is not null)::boolean as baseline_recorded,
       coalesce(ar.baseline_turn_id,'') as baseline_turn_id,coalesce(ar.turn_id,'') as turn_id,
       coalesce(ar.turn_outcome,'') as turn_outcome,
       coalesce(ar.attention,'') as attention,
       coalesce(ar.sandbox_id,'') as sandbox_id,
       ar.started_at,ar.finished_at,
       -- Uncorrelated membership lets generic prepared plans hash identities once
       -- instead of scanning the Session's runs again for every Delivery.
       case when ar.harness is not null and ar.thread_id is not null
         and coalesce(ar.turn_id,m.steer_target_turn_id) is not null then
           (ar.session_id,ar.sandbox_id,ar.harness,ar.thread_id,coalesce(ar.turn_id,m.steer_target_turn_id)) in (
               select source.session_id,source.sandbox_id,source.harness,source.thread_id,source.turn_id
               from dorf.agent_runs source
               where source.session_id=$1 and source.interrupt_requested
           )
         else false
       end as interrupt_requested
from dorf.session_messages m
left join dorf.agent_runs ar on ar.message_id=m.id
where m.session_id=$1
order by m.sequence
`

type ListDeliveriesRow struct {
	MessageID             string
	MessageSessionID      string
	FromKind              core.MessageFromKind
	FromID                string
	Sequence              int64
	Input                 string
	Attachments           json.RawMessage
	DeliveryIntent        core.MessageDeliveryIntent
	RequestedIntent       string
	SteerTargetTurnID     string
	RefreshSkills         bool
	DeveloperInstructions sql.NullString
	Observation           bool
	AdmittedAt            time.Time
	AgentRunPresent       bool
	AgentRunID            string
	AgentRunSessionID     string
	AgentRunMessageID     string
	State                 core.AgentRunState
	Harness               string
	ThreadID              string
	BaselineRecorded      bool
	BaselineTurnID        string
	TurnID                string
	TurnOutcome           string
	Attention             string
	SandboxID             string
	StartedAt             sql.NullTime
	FinishedAt            sql.NullTime
	InterruptRequested    bool
}

func (q *Queries) ListDeliveries(ctx context.Context, sessionID string) ([]ListDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveries, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliveriesRow
	for rows.Next() {
		var i ListDeliveriesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.MessageSessionID,
			&i.FromKind,
			&i.FromID,
			&i.Sequence,
			&i.Input,
			&i.Attachments,
			&i.DeliveryIntent,
			&i.RequestedIntent,
			&i.SteerTargetTurnID,
			&i.RefreshSkills,
			&i.DeveloperInstructions,
			&i.Observation,
			&i.AdmittedAt,
			&i.AgentRunPresent,
			&i.AgentRunID,
			&i.AgentRunSessionID,
			&i.AgentRunMessageID,
			&i.State,
			&i.Harness,
			&i.ThreadID,
			&i.BaselineRecorded,
			&i.BaselineTurnID,
			&i.TurnID,
			&i.TurnOutcome,
			&i.Attention,
			&i.SandboxID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.InterruptRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMessageSequence = `-- name: NextMessageSequence :one
select (coalesce(max(sequence),0)+1)::bigint
from dorf.session_messages
where session_id=$1
`

func (q *Queries) NextMessageSequence(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextMessageSequence, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
