// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"database/sql"
)

type DorfReviewRunProjection struct {
	ID                   string
	JobID                string
	MessageID            string
	ActionID             string
	SessionID            string
	State                string
	BaselineRecorded     bool
	BaselineTurnID       string
	NativeTurnID         string
	NativeOutcome        string
	Attention            string
	Role                 string
	Revision             string
	Capability           string
	Workspace            string
	InputContract        string
	ClaimEvidenceID      string
	ObservedEvidenceID   string
	StartedAt            sql.NullTime
	FinishedAt           sql.NullTime
	InputTokens          int64
	CachedInputTokens    int64
	OutputTokens         int64
	CostMicrousd         int64
	UsageAvailable       bool
	YieldCount           int32
	ReviewerSandboxID    string
	ReviewerRouteID      string
	ReviewerAppServer    string
	ReviewerOwnerNonce   string
	SubmissionNonce      string
	InputDigest          string
	RevisionTree         string
	ReviewerSandboxState string
	ReviewerRouteState   string
	CheckoutState        string
	PostReviewState      string
}
