// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"database/sql"
)

type DorfReviewRunProjection struct {
	ID                    string
	JobID                 string
	MessageID             string
	State                 string
	Harness               string
	ThreadID              string
	BaselineRecorded      bool
	BaselineTurnID        string
	TurnID                string
	TurnOutcome           string
	Attention             string
	Role                  string
	Revision              string
	Capability            string
	StartedAt             sql.NullTime
	FinishedAt            sql.NullTime
	RequestFromKind       string
	RequestFromID         string
	RequestSequence       int64
	RequestInput          string
	RequestDeliveryIntent string
	RequestTargetTurnID   string
	SandboxID             string
	RouteID               string
	OwnershipNonce        string
	SubmissionNonce       string
	SandboxState          string
	RouteState            string
}

// One scoped provider route belonging to a Sandbox
type DorfRoute struct {
	ID        string
	SandboxID string
	State     string
}

// Job-owned isolated workstations used by one or more AgentRuns
type DorfSandbox struct {
	ID             string
	JobID          string
	State          string
	OwnershipNonce string
}
