// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"database/sql"
	"time"

	"github.com/aphronio/dorf/internal/core"
)

type DorfAction struct {
	ID        string
	JobID     string
	Kind      core.ActionKind
	State     core.ActionState
	ScopeKey  string
	CreatedAt time.Time
	SettledAt sql.NullTime
}

type DorfArtifact struct {
	ID         string
	JobID      string
	Name       string
	Digest     string
	ByteSize   int64
	MediaType  string
	Producer   string
	AgentRunID string
	CreatedAt  time.Time
}

// One exact-Revision GitHub proposal projection per Job
type DorfGithubProposal struct {
	JobID            string
	PRNumber         int64
	PRURL            string
	ProposedRevision string
	BodyDigest       string
}

type DorfJobTask struct {
	JobID      string
	Sequence   int64
	TaskID     string
	TaskName   string
	AttachedAt time.Time
}

type DorfReviewRunProjection struct {
	ID                    string
	JobID                 string
	MessageID             string
	State                 string
	Harness               string
	ThreadID              string
	BaselineRecorded      bool
	BaselineTurnID        string
	TurnID                string
	TurnOutcome           string
	Attention             string
	Role                  string
	InputRevision         string
	Capability            string
	StartedAt             sql.NullTime
	FinishedAt            sql.NullTime
	RequestFromKind       string
	RequestFromID         string
	RequestSequence       int64
	RequestInput          string
	RequestDeliveryIntent string
	RequestTargetTurnID   string
	RequestAdmittedAt     time.Time
	SandboxID             string
	OwnershipNonce        string
	SubmissionNonce       string
}

// Job-owned isolated workstations used by one or more AgentRuns
type DorfSandbox struct {
	ID             string
	JobID          string
	OwnershipNonce string
}
