// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: native.sql

package dbsql

import (
	"context"
	"database/sql"
)

const beginNativeMutation = `-- name: BeginNativeMutation :one
update dorf.sessions set native_revision=native_revision+1,
    native_pending_input_id=nullif($1::text,''),
    native_pending_turn_id=nullif($2::text,'')
where dorf.sessions.id=$3 and admission_open and cleanup_state='pending'
  and thread_id=$4
  and native_pending_input_id is null and native_pending_turn_id is null
  and not exists (
      select 1 from dorf.sandbox_delivery_holds h join dorf.sandboxes s on s.id=h.sandbox_id
      where s.session_id=dorf.sessions.id and h.released_at is null
  )
returning native_revision
`

type BeginNativeMutationParams struct {
	InputID   string
	TurnID    string
	SessionID string
	ThreadID  sql.NullString
}

func (q *Queries) BeginNativeMutation(ctx context.Context, arg BeginNativeMutationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, beginNativeMutation,
		arg.InputID,
		arg.TurnID,
		arg.SessionID,
		arg.ThreadID,
	)
	var native_revision int64
	err := row.Scan(&native_revision)
	return native_revision, err
}

const bindNativeThread = `-- name: BindNativeThread :execrows
update dorf.sessions set thread_id=$1
where dorf.sessions.id=$2 and admission_open and cleanup_state='pending'
  and (thread_id=$1 or (native_revision=0 and native_pending_input_id is null
       and native_pending_turn_id is null))
`

type BindNativeThreadParams struct {
	ThreadID  sql.NullString
	SessionID string
}

func (q *Queries) BindNativeThread(ctx context.Context, arg BindNativeThreadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindNativeThread, arg.ThreadID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishNativeMutation = `-- name: FinishNativeMutation :execrows
update dorf.sessions set native_pending_input_id=null,native_pending_turn_id=null
where id=$1 and native_revision=$2
`

type FinishNativeMutationParams struct {
	SessionID string
	Revision  int64
}

func (q *Queries) FinishNativeMutation(ctx context.Context, arg FinishNativeMutationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishNativeMutation, arg.SessionID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNativeState = `-- name: GetNativeState :one
select native_revision,coalesce(native_pending_input_id,'')::text as pending_input_id,
       coalesce(native_pending_turn_id,'')::text as pending_turn_id
from dorf.sessions where id=$1
`

type GetNativeStateRow struct {
	NativeRevision int64
	PendingInputID string
	PendingTurnID  string
}

func (q *Queries) GetNativeState(ctx context.Context, sessionID string) (GetNativeStateRow, error) {
	row := q.db.QueryRowContext(ctx, getNativeState, sessionID)
	var i GetNativeStateRow
	err := row.Scan(&i.NativeRevision, &i.PendingInputID, &i.PendingTurnID)
	return i, err
}
