// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outcomes.sql

package dbsql

import (
	"context"
	"time"

	"github.com/aphronio/dorf/internal/spine"
)

const closeAdmissionForOutcome = `-- name: CloseAdmissionForOutcome :execrows
update dorf.jobs
set admission_open=false
where id=$1 and admission_open and cleanup_state='pending'
`

func (q *Queries) CloseAdmissionForOutcome(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeAdmissionForOutcome, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOutcome = `-- name: GetOutcome :one
select job_id,outcome,coalesce(observed_state,'') as observed_state,observed_merged,
       coalesce(merge_commit_oid,'') as merge_commit_oid,observed_at
from dorf.job_outcomes
where job_id=$1
`

type GetOutcomeRow struct {
	JobID          string
	Outcome        spine.JobOutcomeKind
	ObservedState  string
	ObservedMerged bool
	MergeCommitOID string
	ObservedAt     time.Time
}

func (q *Queries) GetOutcome(ctx context.Context, jobID string) (GetOutcomeRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcome, jobID)
	var i GetOutcomeRow
	err := row.Scan(
		&i.JobID,
		&i.Outcome,
		&i.ObservedState,
		&i.ObservedMerged,
		&i.MergeCommitOID,
		&i.ObservedAt,
	)
	return i, err
}

const getOutcomeJobForUpdate = `-- name: GetOutcomeJobForUpdate :one
select revision,admission_open,cleanup_state
from dorf.jobs
where id=$1
for update
`

type GetOutcomeJobForUpdateRow struct {
	Revision      string
	AdmissionOpen bool
	CleanupState  spine.CleanupState
}

func (q *Queries) GetOutcomeJobForUpdate(ctx context.Context, jobID string) (GetOutcomeJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeJobForUpdate, jobID)
	var i GetOutcomeJobForUpdateRow
	err := row.Scan(&i.Revision, &i.AdmissionOpen, &i.CleanupState)
	return i, err
}

const insertOutcome = `-- name: InsertOutcome :one
insert into dorf.job_outcomes(
    job_id,outcome,observed_state,observed_merged,merge_commit_oid,observed_at
) values(
    $1,$2,nullif($3::text,''),
    $4,nullif($5::text,''),$6
)
returning job_id,outcome,coalesce(observed_state,'') as observed_state,observed_merged,
          coalesce(merge_commit_oid,'') as merge_commit_oid,observed_at
`

type InsertOutcomeParams struct {
	JobID          string
	Outcome        spine.JobOutcomeKind
	ObservedState  string
	ObservedMerged bool
	MergeCommitOID string
	ObservedAt     time.Time
}

type InsertOutcomeRow struct {
	JobID          string
	Outcome        spine.JobOutcomeKind
	ObservedState  string
	ObservedMerged bool
	MergeCommitOID string
	ObservedAt     time.Time
}

func (q *Queries) InsertOutcome(ctx context.Context, arg InsertOutcomeParams) (InsertOutcomeRow, error) {
	row := q.db.QueryRowContext(ctx, insertOutcome,
		arg.JobID,
		arg.Outcome,
		arg.ObservedState,
		arg.ObservedMerged,
		arg.MergeCommitOID,
		arg.ObservedAt,
	)
	var i InsertOutcomeRow
	err := row.Scan(
		&i.JobID,
		&i.Outcome,
		&i.ObservedState,
		&i.ObservedMerged,
		&i.MergeCommitOID,
		&i.ObservedAt,
	)
	return i, err
}

const outcomeImplementationSettled = `-- name: OutcomeImplementationSettled :one
select (
  not exists (
    select 1 from dorf.agent_runs ar
    where ar.job_id=$1 and ar.role='implement'
      and ar.state not in ('completed','failed','interrupted')
  )
  and coalesce((
    select ar.state='completed'
    from dorf.agent_runs ar
    join dorf.job_messages m on m.id=ar.message_id
    where ar.job_id=$1 and ar.role='implement'
    order by m.sequence desc
    limit 1
  ),false)
  and coalesce((
    select ar.state='completed' and exists (
      select 1 from dorf.evidence e
      where e.agent_run_id=ar.id and e.kind='git-revision' and e.revision=j.revision
    )
    from dorf.agent_runs ar
    join dorf.job_messages m on m.id=ar.message_id
    join dorf.jobs j on j.id=ar.job_id
    where ar.job_id=$1 and ar.role='implement'
      and (m.delivery_intent='follow' or (
        m.delivery_intent='steer' and ar.turn_id is not null and ar.turn_id<>m.steer_target_turn_id
      ))
    order by m.sequence desc
    limit 1
  ),false)
)::boolean as settled
`

func (q *Queries) OutcomeImplementationSettled(ctx context.Context, jobID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, outcomeImplementationSettled, jobID)
	var settled bool
	err := row.Scan(&settled)
	return settled, err
}

const outcomePublicationIntentExists = `-- name: OutcomePublicationIntentExists :one
select exists(
  select 1 from dorf.actions
  where job_id=$1 and kind='github-pull-request'
)::boolean
`

func (q *Queries) OutcomePublicationIntentExists(ctx context.Context, jobID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, outcomePublicationIntentExists, jobID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
