// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outcomes.sql

package dbsql

import (
	"context"
	"time"

	"github.com/aphronio/dorf/internal/spine"
)

const clearOutcomeAttention = `-- name: ClearOutcomeAttention :execrows
update dorf.jobs
set workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='published'
`

type ClearOutcomeAttentionParams struct {
	JobID    string
	Revision string
}

func (q *Queries) ClearOutcomeAttention(ctx context.Context, arg ClearOutcomeAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearOutcomeAttention, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOutcome = `-- name: GetOutcome :one
select job_id,outcome,observed_state,observed_merged,
       coalesce(merge_commit_oid,'') as merge_commit_oid,observed_at
from dorf.job_outcomes
where job_id=$1
`

type GetOutcomeRow struct {
	JobID          string
	Outcome        spine.JobOutcomeKind
	ObservedState  string
	ObservedMerged bool
	MergeCommitOID string
	ObservedAt     time.Time
}

func (q *Queries) GetOutcome(ctx context.Context, jobID string) (GetOutcomeRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcome, jobID)
	var i GetOutcomeRow
	err := row.Scan(
		&i.JobID,
		&i.Outcome,
		&i.ObservedState,
		&i.ObservedMerged,
		&i.MergeCommitOID,
		&i.ObservedAt,
	)
	return i, err
}

const getOutcomeJobForUpdate = `-- name: GetOutcomeJobForUpdate :one
select revision,workflow_phase
from dorf.jobs
where id=$1
for update
`

type GetOutcomeJobForUpdateRow struct {
	Revision      string
	WorkflowPhase string
}

func (q *Queries) GetOutcomeJobForUpdate(ctx context.Context, jobID string) (GetOutcomeJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeJobForUpdate, jobID)
	var i GetOutcomeJobForUpdateRow
	err := row.Scan(&i.Revision, &i.WorkflowPhase)
	return i, err
}

const insertOutcome = `-- name: InsertOutcome :one
insert into dorf.job_outcomes(
    job_id,outcome,observed_state,observed_merged,merge_commit_oid,observed_at
) values(
    $1,$2,$3,
    $4,nullif($5::text,''),$6
)
returning job_id,outcome,observed_state,observed_merged,
          coalesce(merge_commit_oid,'') as merge_commit_oid,observed_at
`

type InsertOutcomeParams struct {
	JobID          string
	Outcome        spine.JobOutcomeKind
	ObservedState  string
	ObservedMerged bool
	MergeCommitOID string
	ObservedAt     time.Time
}

type InsertOutcomeRow struct {
	JobID          string
	Outcome        spine.JobOutcomeKind
	ObservedState  string
	ObservedMerged bool
	MergeCommitOID string
	ObservedAt     time.Time
}

func (q *Queries) InsertOutcome(ctx context.Context, arg InsertOutcomeParams) (InsertOutcomeRow, error) {
	row := q.db.QueryRowContext(ctx, insertOutcome,
		arg.JobID,
		arg.Outcome,
		arg.ObservedState,
		arg.ObservedMerged,
		arg.MergeCommitOID,
		arg.ObservedAt,
	)
	var i InsertOutcomeRow
	err := row.Scan(
		&i.JobID,
		&i.Outcome,
		&i.ObservedState,
		&i.ObservedMerged,
		&i.MergeCommitOID,
		&i.ObservedAt,
	)
	return i, err
}
