// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publication.sql

package dbsql

import (
	"context"

	"github.com/aphronio/dorf/internal/spine"
)

const blockPublicationPhase = `-- name: BlockPublicationPhase :execrows
update dorf.jobs
set workflow_phase='publication-blocked',workflow_attention=$1::text
where id=$2 and revision=$3 and workflow_phase='publishing'
`

type BlockPublicationPhaseParams struct {
	Reason   string
	JobID    string
	Revision string
}

func (q *Queries) BlockPublicationPhase(ctx context.Context, arg BlockPublicationPhaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, blockPublicationPhase, arg.Reason, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeProposalAction = `-- name: CompleteProposalAction :execrows
update dorf.actions
set state='succeeded'
where id=$1 and job_id=$2
  and kind='github-pull-request' and scope_key=$3
`

type CompleteProposalActionParams struct {
	ActionID         string
	JobID            string
	ProposedRevision string
}

func (q *Queries) CompleteProposalAction(ctx context.Context, arg CompleteProposalActionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeProposalAction, arg.ActionID, arg.JobID, arg.ProposedRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completePublication = `-- name: CompletePublication :execrows
update dorf.jobs
set workflow_phase='published',workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='publishing'
`

type CompletePublicationParams struct {
	JobID    string
	Revision string
}

func (q *Queries) CompletePublication(ctx context.Context, arg CompletePublicationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completePublication, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeRepositoryPush = `-- name: CompleteRepositoryPush :execrows
update dorf.actions
set state='succeeded'
where id=$1 and kind='repository-push' and scope_key=$2
`

type CompleteRepositoryPushParams struct {
	ActionID string
	Revision string
}

func (q *Queries) CompleteRepositoryPush(ctx context.Context, arg CompleteRepositoryPushParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeRepositoryPush, arg.ActionID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProposal = `-- name: GetProposal :one
select job_id,repository,installation_id,base_branch,head_branch,pr_number,pr_url,
       proposed_revision,observed_remote_head,body_digest
from dorf.github_proposals
where job_id=$1
`

type GetProposalRow struct {
	JobID              string
	Repository         string
	InstallationID     string
	BaseBranch         string
	HeadBranch         string
	PRNumber           int64
	PRURL              string
	ProposedRevision   string
	ObservedRemoteHead string
	BodyDigest         string
}

// GetProposal is the one proposal projection shared by publication and outcome code.
func (q *Queries) GetProposal(ctx context.Context, jobID string) (GetProposalRow, error) {
	row := q.db.QueryRowContext(ctx, getProposal, jobID)
	var i GetProposalRow
	err := row.Scan(
		&i.JobID,
		&i.Repository,
		&i.InstallationID,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.PRNumber,
		&i.PRURL,
		&i.ProposedRevision,
		&i.ObservedRemoteHead,
		&i.BodyDigest,
	)
	return i, err
}

const getProposalAuthorityJobForUpdate = `-- name: GetProposalAuthorityJobForUpdate :one
select coalesce(github_repository,'') as github_repository,
       coalesce(github_installation_id,'') as github_installation_id,
       coalesce(base_branch,'') as base_branch,branch,revision,workflow_phase
from dorf.jobs
where id=$1
for update
`

type GetProposalAuthorityJobForUpdateRow struct {
	GithubRepository     string
	GithubInstallationID string
	BaseBranch           string
	Branch               string
	Revision             string
	WorkflowPhase        string
}

func (q *Queries) GetProposalAuthorityJobForUpdate(ctx context.Context, jobID string) (GetProposalAuthorityJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getProposalAuthorityJobForUpdate, jobID)
	var i GetProposalAuthorityJobForUpdateRow
	err := row.Scan(
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.BaseBranch,
		&i.Branch,
		&i.Revision,
		&i.WorkflowPhase,
	)
	return i, err
}

const getProposalCurrentRevision = `-- name: GetProposalCurrentRevision :one
select revision from dorf.jobs where id=$1
`

func (q *Queries) GetProposalCurrentRevision(ctx context.Context, jobID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getProposalCurrentRevision, jobID)
	var revision string
	err := row.Scan(&revision)
	return revision, err
}

const getPublicationAction = `-- name: GetPublicationAction :one
select id,job_id,kind,state,scope_key
from dorf.actions
where job_id=$1 and kind=$2 and scope_key=$3
`

type GetPublicationActionParams struct {
	JobID    string
	Kind     spine.ActionKind
	ScopeKey string
}

type GetPublicationActionRow struct {
	ID       string
	JobID    string
	Kind     spine.ActionKind
	State    spine.ActionState
	ScopeKey string
}

func (q *Queries) GetPublicationAction(ctx context.Context, arg GetPublicationActionParams) (GetPublicationActionRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicationAction, arg.JobID, arg.Kind, arg.ScopeKey)
	var i GetPublicationActionRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.State,
		&i.ScopeKey,
	)
	return i, err
}

const getPublicationActionForUpdate = `-- name: GetPublicationActionForUpdate :one
select id,job_id,kind,state,scope_key
from dorf.actions
where id=$1 and job_id=$2 and kind=$3 and scope_key=$4
for update
`

type GetPublicationActionForUpdateParams struct {
	ID       string
	JobID    string
	Kind     spine.ActionKind
	ScopeKey string
}

type GetPublicationActionForUpdateRow struct {
	ID       string
	JobID    string
	Kind     spine.ActionKind
	State    spine.ActionState
	ScopeKey string
}

func (q *Queries) GetPublicationActionForUpdate(ctx context.Context, arg GetPublicationActionForUpdateParams) (GetPublicationActionForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicationActionForUpdate,
		arg.ID,
		arg.JobID,
		arg.Kind,
		arg.ScopeKey,
	)
	var i GetPublicationActionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.State,
		&i.ScopeKey,
	)
	return i, err
}

const getPublicationJobForUpdate = `-- name: GetPublicationJobForUpdate :one
select revision,workflow_phase,coalesce(github_repository,'') as github_repository,
       coalesce(github_installation_id,'') as github_installation_id,
       coalesce(base_branch,'') as base_branch,branch,repository,
       admission_open,cleanup_state
from dorf.jobs
where id=$1
for update
`

type GetPublicationJobForUpdateRow struct {
	Revision             string
	WorkflowPhase        string
	GithubRepository     string
	GithubInstallationID string
	BaseBranch           string
	Branch               string
	Repository           string
	AdmissionOpen        bool
	CleanupState         spine.CleanupState
}

func (q *Queries) GetPublicationJobForUpdate(ctx context.Context, jobID string) (GetPublicationJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicationJobForUpdate, jobID)
	var i GetPublicationJobForUpdateRow
	err := row.Scan(
		&i.Revision,
		&i.WorkflowPhase,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.BaseBranch,
		&i.Branch,
		&i.Repository,
		&i.AdmissionOpen,
		&i.CleanupState,
	)
	return i, err
}

const getRepositoryPushState = `-- name: GetRepositoryPushState :one
select state
from dorf.actions
where job_id=$1 and kind='repository-push' and scope_key=$2
`

type GetRepositoryPushStateParams struct {
	JobID    string
	Revision string
}

func (q *Queries) GetRepositoryPushState(ctx context.Context, arg GetRepositoryPushStateParams) (spine.ActionState, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryPushState, arg.JobID, arg.Revision)
	var state spine.ActionState
	err := row.Scan(&state)
	return state, err
}

const insertPublicationAction = `-- name: InsertPublicationAction :exec
insert into dorf.actions(id,job_id,kind,state,scope_key)
values($1,$2,$3,'unsettled',$4)
on conflict do nothing
`

type InsertPublicationActionParams struct {
	ID       string
	JobID    string
	Kind     spine.ActionKind
	ScopeKey string
}

func (q *Queries) InsertPublicationAction(ctx context.Context, arg InsertPublicationActionParams) error {
	_, err := q.db.ExecContext(ctx, insertPublicationAction,
		arg.ID,
		arg.JobID,
		arg.Kind,
		arg.ScopeKey,
	)
	return err
}

const resumePublicationPhase = `-- name: ResumePublicationPhase :execrows
update dorf.jobs
set workflow_phase='publishing',workflow_attention=null
where id=$1 and revision=$2
  and workflow_phase='publication-blocked'
`

type ResumePublicationPhaseParams struct {
	JobID    string
	Revision string
}

func (q *Queries) ResumePublicationPhase(ctx context.Context, arg ResumePublicationPhaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resumePublicationPhase, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startPublicationIntent = `-- name: StartPublicationIntent :execrows
update dorf.jobs
set workflow_phase='publishing',workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='ready'
`

type StartPublicationIntentParams struct {
	JobID    string
	Revision string
}

func (q *Queries) StartPublicationIntent(ctx context.Context, arg StartPublicationIntentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startPublicationIntent, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertProposal = `-- name: UpsertProposal :execrows
insert into dorf.github_proposals(
    job_id,repository,installation_id,base_branch,head_branch,pr_number,pr_url,
    proposed_revision,observed_remote_head,body_digest
) values(
    $1,$2,$3,$4,
    $5,$6,$7,$8,
    $9,$10
)
on conflict(job_id) do update set
  pr_url=excluded.pr_url,proposed_revision=excluded.proposed_revision,
  observed_remote_head=excluded.observed_remote_head,body_digest=excluded.body_digest,
  observed_at=clock_timestamp()
where dorf.github_proposals.repository=excluded.repository
  and dorf.github_proposals.installation_id=excluded.installation_id
  and dorf.github_proposals.base_branch=excluded.base_branch
  and dorf.github_proposals.head_branch=excluded.head_branch
  and dorf.github_proposals.pr_number=excluded.pr_number
`

type UpsertProposalParams struct {
	JobID              string
	Repository         string
	InstallationID     string
	BaseBranch         string
	HeadBranch         string
	PRNumber           int64
	PRURL              string
	ProposedRevision   string
	ObservedRemoteHead string
	BodyDigest         string
}

func (q *Queries) UpsertProposal(ctx context.Context, arg UpsertProposalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertProposal,
		arg.JobID,
		arg.Repository,
		arg.InstallationID,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.PRNumber,
		arg.PRURL,
		arg.ProposedRevision,
		arg.ObservedRemoteHead,
		arg.BodyDigest,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
