// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publication.sql

package dbsql

import (
	"context"
	"database/sql"

	"github.com/aphronio/dorf/internal/spine"
)

const clearPublicationAttention = `-- name: ClearPublicationAttention :exec
update dorf.jobs
set workflow_attention=null,workflow_attention_source=null,workflow_attention_at=null
where id=$1 and revision=$2
  and workflow_attention_source=$3
`

type ClearPublicationAttentionParams struct {
	JobID    string
	Revision string
	ActionID sql.NullString
}

func (q *Queries) ClearPublicationAttention(ctx context.Context, arg ClearPublicationAttentionParams) error {
	_, err := q.db.ExecContext(ctx, clearPublicationAttention, arg.JobID, arg.Revision, arg.ActionID)
	return err
}

const clearPublicationAttentionForAction = `-- name: ClearPublicationAttentionForAction :exec
update dorf.jobs j
set workflow_attention=null,workflow_attention_source=null,workflow_attention_at=null
where j.revision=$1
  and j.workflow_attention_source=$2
  and exists (
    select 1 from dorf.actions a
    where a.id=$2 and a.job_id=j.id
      and a.scope_key=$1
  )
`

type ClearPublicationAttentionForActionParams struct {
	Revision string
	ActionID sql.NullString
}

func (q *Queries) ClearPublicationAttentionForAction(ctx context.Context, arg ClearPublicationAttentionForActionParams) error {
	_, err := q.db.ExecContext(ctx, clearPublicationAttentionForAction, arg.Revision, arg.ActionID)
	return err
}

const completeProposalAction = `-- name: CompleteProposalAction :execrows
update dorf.actions
set state='succeeded',settled_at=coalesce(settled_at,clock_timestamp())
where id=$1 and job_id=$2
  and kind='github-pull-request' and scope_key=$3
  and state in ('unsettled','succeeded')
`

type CompleteProposalActionParams struct {
	ActionID         string
	JobID            string
	ProposedRevision string
}

func (q *Queries) CompleteProposalAction(ctx context.Context, arg CompleteProposalActionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeProposalAction, arg.ActionID, arg.JobID, arg.ProposedRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeRepositoryPush = `-- name: CompleteRepositoryPush :execrows
update dorf.actions
set state='succeeded',settled_at=coalesce(settled_at,clock_timestamp())
where id=$1 and kind='repository-push' and scope_key=$2
  and state in ('unsettled','succeeded')
`

type CompleteRepositoryPushParams struct {
	ActionID string
	Revision string
}

func (q *Queries) CompleteRepositoryPush(ctx context.Context, arg CompleteRepositoryPushParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeRepositoryPush, arg.ActionID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProposal = `-- name: GetProposal :one
select job_id,pr_number,pr_url,proposed_revision,body_digest
from dorf.github_proposals
where job_id=$1
`

// GetProposal is the one proposal projection shared by publication and outcome code.
func (q *Queries) GetProposal(ctx context.Context, jobID string) (DorfGithubProposal, error) {
	row := q.db.QueryRowContext(ctx, getProposal, jobID)
	var i DorfGithubProposal
	err := row.Scan(
		&i.JobID,
		&i.PRNumber,
		&i.PRURL,
		&i.ProposedRevision,
		&i.BodyDigest,
	)
	return i, err
}

const getProposalJobForUpdate = `-- name: GetProposalJobForUpdate :one
select revision,admission_open,cleanup_state
from dorf.jobs
where id=$1
for update
`

type GetProposalJobForUpdateRow struct {
	Revision      string
	AdmissionOpen bool
	CleanupState  spine.CleanupState
}

func (q *Queries) GetProposalJobForUpdate(ctx context.Context, jobID string) (GetProposalJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getProposalJobForUpdate, jobID)
	var i GetProposalJobForUpdateRow
	err := row.Scan(&i.Revision, &i.AdmissionOpen, &i.CleanupState)
	return i, err
}

const getPublicationJobForUpdate = `-- name: GetPublicationJobForUpdate :one
select revision,coalesce(github_repository,'') as github_repository,
       coalesce(github_installation_id,'') as github_installation_id,
       coalesce(base_branch,'') as base_branch,branch,repository,
       admission_open,cleanup_state
from dorf.jobs
where id=$1
for update
`

type GetPublicationJobForUpdateRow struct {
	Revision             string
	GithubRepository     string
	GithubInstallationID string
	BaseBranch           string
	Branch               string
	Repository           string
	AdmissionOpen        bool
	CleanupState         spine.CleanupState
}

func (q *Queries) GetPublicationJobForUpdate(ctx context.Context, jobID string) (GetPublicationJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicationJobForUpdate, jobID)
	var i GetPublicationJobForUpdateRow
	err := row.Scan(
		&i.Revision,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.BaseBranch,
		&i.Branch,
		&i.Repository,
		&i.AdmissionOpen,
		&i.CleanupState,
	)
	return i, err
}

const setPublicationAttention = `-- name: SetPublicationAttention :execrows
update dorf.jobs
set workflow_attention=$1::text,
    workflow_attention_source=$2::text,
    workflow_attention_at=clock_timestamp()
where dorf.jobs.id=$3 and dorf.jobs.revision=$4
  and dorf.jobs.admission_open and dorf.jobs.cleanup_state='pending'
  and exists (
    select 1 from dorf.actions a
    where a.id=$2 and a.job_id=dorf.jobs.id
      and a.scope_key=$4
      and a.kind in ('repository-push','github-pull-request')
      and a.state='unsettled'
  )
`

type SetPublicationAttentionParams struct {
	Reason   string
	ActionID string
	JobID    string
	Revision string
}

func (q *Queries) SetPublicationAttention(ctx context.Context, arg SetPublicationAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPublicationAttention,
		arg.Reason,
		arg.ActionID,
		arg.JobID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertProposal = `-- name: UpsertProposal :execrows
insert into dorf.github_proposals(
    job_id,pr_number,pr_url,proposed_revision,body_digest
) values(
    $1,$2,$3,$4,$5
)
on conflict(job_id) do update set
  pr_url=excluded.pr_url,proposed_revision=excluded.proposed_revision,
  body_digest=excluded.body_digest
where dorf.github_proposals.pr_number=excluded.pr_number
`

type UpsertProposalParams struct {
	JobID            string
	PRNumber         int64
	PRURL            string
	ProposedRevision string
	BodyDigest       string
}

func (q *Queries) UpsertProposal(ctx context.Context, arg UpsertProposalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertProposal,
		arg.JobID,
		arg.PRNumber,
		arg.PRURL,
		arg.ProposedRevision,
		arg.BodyDigest,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
