// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"
)

const abandonCheckpointRecovery = `-- name: AbandonCheckpointRecovery :execrows
update dorf.sandbox_delivery_holds hold
set released_at=coalesce(hold.released_at,clock_timestamp())
from dorf.sandbox_recoveries recovery
join dorf.sandboxes sandbox on sandbox.id=recovery.sandbox_id
join dorf.jobs job on job.id=sandbox.job_id
join dorf.sandbox_resources destination on destination.id=recovery.destination_resource_id
where recovery.id=$1 and hold.id=recovery.id
  and hold.reason='checkpoint_recovery' and hold.sandbox_id=sandbox.id
  and recovery.finished_at is null and sandbox.active_resource_id=recovery.source_resource_id
  and destination.deleted_at is not null
  and not job.admission_open and job.cleanup_state='scheduled'
`

func (q *Queries) AbandonCheckpointRecovery(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, abandonCheckpointRecovery, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCheckpointRecovery = `-- name: GetCheckpointRecovery :one
select
    recovery.id, recovery.sandbox_id, recovery.checkpoint_repository, recovery.checkpoint_snapshot_id, recovery.source_resource_id, recovery.destination_resource_id, recovery.requested_at, recovery.verified_at, recovery.finished_at,
    source.deleted_at as source_deleted_at,
    destination.deleted_at as destination_deleted_at,
    sandbox.job_id,
    coalesce(source.provider_id,'') as source_provider_id,
    coalesce(destination.provider_id,'') as destination_provider_id,
    checkpoint.resource_id as checkpoint_resource_id,
    checkpoint.profile_name,
    checkpoint.profile_revision,
    coalesce(checkpoint.effective_upgrade_id,'') as effective_upgrade_id,
    checkpoint.last_activity_at,
    checkpoint.message_sequence,
    checkpoint.completed_turn_sequence,
    checkpoint.delivery_hold_count,
    checkpoint.cleanup,
    checkpoint.published_at,
    coalesce(package.package_path,'') as package_path,
    coalesce(package.version,'') as package_version
from dorf.sandbox_recoveries recovery
join dorf.sandboxes sandbox on sandbox.id=recovery.sandbox_id
join dorf.sandbox_resources source on source.id=recovery.source_resource_id
left join dorf.sandbox_resources destination on destination.id=recovery.destination_resource_id
join dorf.sandbox_checkpoints checkpoint
  on checkpoint.repository=recovery.checkpoint_repository
 and checkpoint.snapshot_id=recovery.checkpoint_snapshot_id
left join dorf.sandbox_upgrades package on package.id=checkpoint.effective_upgrade_id
where recovery.id=$1
`

type GetCheckpointRecoveryRow struct {
	ID                    string
	SandboxID             string
	CheckpointRepository  string
	CheckpointSnapshotID  string
	SourceResourceID      string
	DestinationResourceID string
	RequestedAt           time.Time
	VerifiedAt            sql.NullTime
	FinishedAt            sql.NullTime
	SourceDeletedAt       sql.NullTime
	DestinationDeletedAt  sql.NullTime
	JobID                 string
	SourceProviderID      string
	DestinationProviderID string
	CheckpointResourceID  string
	ProfileName           string
	ProfileRevision       string
	EffectiveUpgradeID    string
	LastActivityAt        time.Time
	MessageSequence       int64
	CompletedTurnSequence int64
	DeliveryHoldCount     int64
	Cleanup               bool
	PublishedAt           time.Time
	PackagePath           string
	PackageVersion        string
}

func (q *Queries) GetCheckpointRecovery(ctx context.Context, id string) (GetCheckpointRecoveryRow, error) {
	row := q.db.QueryRowContext(ctx, getCheckpointRecovery, id)
	var i GetCheckpointRecoveryRow
	err := row.Scan(
		&i.ID,
		&i.SandboxID,
		&i.CheckpointRepository,
		&i.CheckpointSnapshotID,
		&i.SourceResourceID,
		&i.DestinationResourceID,
		&i.RequestedAt,
		&i.VerifiedAt,
		&i.FinishedAt,
		&i.SourceDeletedAt,
		&i.DestinationDeletedAt,
		&i.JobID,
		&i.SourceProviderID,
		&i.DestinationProviderID,
		&i.CheckpointResourceID,
		&i.ProfileName,
		&i.ProfileRevision,
		&i.EffectiveUpgradeID,
		&i.LastActivityAt,
		&i.MessageSequence,
		&i.CompletedTurnSequence,
		&i.DeliveryHoldCount,
		&i.Cleanup,
		&i.PublishedAt,
		&i.PackagePath,
		&i.PackageVersion,
	)
	return i, err
}

const insertCheckpointRecovery = `-- name: InsertCheckpointRecovery :exec
insert into dorf.sandbox_recoveries(
    id,sandbox_id,checkpoint_repository,checkpoint_snapshot_id,source_resource_id,destination_resource_id
)
values(
    $1,$2,$3,
    $4,$5,$6
)
`

type InsertCheckpointRecoveryParams struct {
	ID                    string
	SandboxID             string
	CheckpointRepository  string
	CheckpointSnapshotID  string
	SourceResourceID      string
	DestinationResourceID string
}

func (q *Queries) InsertCheckpointRecovery(ctx context.Context, arg InsertCheckpointRecoveryParams) error {
	_, err := q.db.ExecContext(ctx, insertCheckpointRecovery,
		arg.ID,
		arg.SandboxID,
		arg.CheckpointRepository,
		arg.CheckpointSnapshotID,
		arg.SourceResourceID,
		arg.DestinationResourceID,
	)
	return err
}

const insertCheckpointRecoveryHold = `-- name: InsertCheckpointRecoveryHold :exec
insert into dorf.sandbox_delivery_holds(id,sandbox_id,reason)
values($1,$2,'checkpoint_recovery')
`

type InsertCheckpointRecoveryHoldParams struct {
	ID        string
	SandboxID string
}

func (q *Queries) InsertCheckpointRecoveryHold(ctx context.Context, arg InsertCheckpointRecoveryHoldParams) error {
	_, err := q.db.ExecContext(ctx, insertCheckpointRecoveryHold, arg.ID, arg.SandboxID)
	return err
}

const listJobCheckpointRecoveries = `-- name: ListJobCheckpointRecoveries :many
select
    recovery.id, recovery.sandbox_id, recovery.checkpoint_repository, recovery.checkpoint_snapshot_id, recovery.source_resource_id, recovery.destination_resource_id, recovery.requested_at, recovery.verified_at, recovery.finished_at,
    source.deleted_at as source_deleted_at,
    destination.deleted_at as destination_deleted_at,
    sandbox.job_id,
    coalesce(source.provider_id,'') as source_provider_id,
    coalesce(destination.provider_id,'') as destination_provider_id,
    checkpoint.resource_id as checkpoint_resource_id,
    checkpoint.profile_name,
    checkpoint.profile_revision,
    coalesce(checkpoint.effective_upgrade_id,'') as effective_upgrade_id,
    checkpoint.last_activity_at,
    checkpoint.message_sequence,
    checkpoint.completed_turn_sequence,
    checkpoint.delivery_hold_count,
    checkpoint.cleanup,
    checkpoint.published_at,
    coalesce(package.package_path,'') as package_path,
    coalesce(package.version,'') as package_version
from dorf.sandbox_recoveries recovery
join dorf.sandboxes sandbox on sandbox.id=recovery.sandbox_id
join dorf.sandbox_resources source on source.id=recovery.source_resource_id
left join dorf.sandbox_resources destination on destination.id=recovery.destination_resource_id
join dorf.sandbox_checkpoints checkpoint
  on checkpoint.repository=recovery.checkpoint_repository
 and checkpoint.snapshot_id=recovery.checkpoint_snapshot_id
left join dorf.sandbox_upgrades package on package.id=checkpoint.effective_upgrade_id
where sandbox.job_id=$1
order by recovery.requested_at,recovery.id
`

type ListJobCheckpointRecoveriesRow struct {
	ID                    string
	SandboxID             string
	CheckpointRepository  string
	CheckpointSnapshotID  string
	SourceResourceID      string
	DestinationResourceID string
	RequestedAt           time.Time
	VerifiedAt            sql.NullTime
	FinishedAt            sql.NullTime
	SourceDeletedAt       sql.NullTime
	DestinationDeletedAt  sql.NullTime
	JobID                 string
	SourceProviderID      string
	DestinationProviderID string
	CheckpointResourceID  string
	ProfileName           string
	ProfileRevision       string
	EffectiveUpgradeID    string
	LastActivityAt        time.Time
	MessageSequence       int64
	CompletedTurnSequence int64
	DeliveryHoldCount     int64
	Cleanup               bool
	PublishedAt           time.Time
	PackagePath           string
	PackageVersion        string
}

func (q *Queries) ListJobCheckpointRecoveries(ctx context.Context, jobID string) ([]ListJobCheckpointRecoveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobCheckpointRecoveries, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobCheckpointRecoveriesRow
	for rows.Next() {
		var i ListJobCheckpointRecoveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.CheckpointRepository,
			&i.CheckpointSnapshotID,
			&i.SourceResourceID,
			&i.DestinationResourceID,
			&i.RequestedAt,
			&i.VerifiedAt,
			&i.FinishedAt,
			&i.SourceDeletedAt,
			&i.DestinationDeletedAt,
			&i.JobID,
			&i.SourceProviderID,
			&i.DestinationProviderID,
			&i.CheckpointResourceID,
			&i.ProfileName,
			&i.ProfileRevision,
			&i.EffectiveUpgradeID,
			&i.LastActivityAt,
			&i.MessageSequence,
			&i.CompletedTurnSequence,
			&i.DeliveryHoldCount,
			&i.Cleanup,
			&i.PublishedAt,
			&i.PackagePath,
			&i.PackageVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCheckpointRecoveryFinished = `-- name: RecordCheckpointRecoveryFinished :execrows
update dorf.sandbox_recoveries set finished_at=coalesce(finished_at,clock_timestamp())
where id=$1 and verified_at is not null
`

func (q *Queries) RecordCheckpointRecoveryFinished(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordCheckpointRecoveryFinished, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordRecoveryVerified = `-- name: RecordRecoveryVerified :execrows
update dorf.sandbox_recoveries set verified_at=coalesce(verified_at,clock_timestamp())
where id=$1
`

func (q *Queries) RecordRecoveryVerified(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordRecoveryVerified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recoveryNativeStateSafe = `-- name: RecoveryNativeStateSafe :one
select not exists (
    select 1
    from dorf.agent_runs run
    join dorf.job_messages message on message.id=run.message_id
    where run.sandbox_id=$1
      and message.sequence>$2
      and (
        run.state<>'pending'
        or run.harness is not null
        or run.thread_id is not null
        or run.baseline_turn_id is not null
        or run.turn_id is not null
        or run.submission_nonce is not null
        or run.started_at is not null
        or run.finished_at is not null
      )
)::boolean as safe
`

type RecoveryNativeStateSafeParams struct {
	SandboxID       string
	MessageSequence int64
}

func (q *Queries) RecoveryNativeStateSafe(ctx context.Context, arg RecoveryNativeStateSafeParams) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, recoveryNativeStateSafe, arg.SandboxID, arg.MessageSequence)
	var safe sql.NullBool
	err := row.Scan(&safe)
	return safe, err
}
