// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"
)

const bindRecoveredResource = `-- name: BindRecoveredResource :execrows
update dorf.sandbox_resources set provider_id=$1::text,observed_at=coalesce(observed_at,clock_timestamp())
where id=$2 and deleted_at is null and (provider_id is null or provider_id=$1::text)
`

type BindRecoveredResourceParams struct {
	ProviderID string
	ResourceID string
}

func (q *Queries) BindRecoveredResource(ctx context.Context, arg BindRecoveredResourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindRecoveredResource, arg.ProviderID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindSandboxResource = `-- name: BindSandboxResource :execrows
update dorf.sandbox_resources r
set provider_id=$1::text,observed_at=coalesce(r.observed_at,clock_timestamp())
from dorf.sandboxes s
where s.id=r.sandbox_id and s.id=$2 and s.job_id=$3
  and s.active_resource_id=r.id and r.id=$4
  and r.ownership_nonce=$5 and r.deleted_at is null
  and (r.provider_id is null or r.provider_id=$1::text)
`

type BindSandboxResourceParams struct {
	ProviderID     string
	SandboxID      string
	JobID          string
	ResourceID     string
	OwnershipNonce string
}

func (q *Queries) BindSandboxResource(ctx context.Context, arg BindSandboxResourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindSandboxResource,
		arg.ProviderID,
		arg.SandboxID,
		arg.JobID,
		arg.ResourceID,
		arg.OwnershipNonce,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getJobSandboxByNameForUpdate = `-- name: GetJobSandboxByNameForUpdate :one
select s.id,s.job_id,s.name,r.ownership_nonce,s.active_resource_id,coalesce(r.provider_id,'') as provider_id
from dorf.sandboxes s join dorf.sandbox_resources r on r.id=s.active_resource_id
where s.job_id=$1 and s.name=$2
for update
`

type GetJobSandboxByNameForUpdateParams struct {
	JobID string
	Name  string
}

type GetJobSandboxByNameForUpdateRow struct {
	ID               string
	JobID            string
	Name             string
	OwnershipNonce   string
	ActiveResourceID string
	ProviderID       string
}

func (q *Queries) GetJobSandboxByNameForUpdate(ctx context.Context, arg GetJobSandboxByNameForUpdateParams) (GetJobSandboxByNameForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getJobSandboxByNameForUpdate, arg.JobID, arg.Name)
	var i GetJobSandboxByNameForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.OwnershipNonce,
		&i.ActiveResourceID,
		&i.ProviderID,
	)
	return i, err
}

const getSandbox = `-- name: GetSandbox :one
select s.id,s.job_id,s.name,r.ownership_nonce,s.active_resource_id,coalesce(r.provider_id,'') as provider_id
from dorf.sandboxes s join dorf.sandbox_resources r on r.id=s.active_resource_id
where s.id=$1
`

type GetSandboxRow struct {
	ID               string
	JobID            string
	Name             string
	OwnershipNonce   string
	ActiveResourceID string
	ProviderID       string
}

func (q *Queries) GetSandbox(ctx context.Context, id string) (GetSandboxRow, error) {
	row := q.db.QueryRowContext(ctx, getSandbox, id)
	var i GetSandboxRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.OwnershipNonce,
		&i.ActiveResourceID,
		&i.ProviderID,
	)
	return i, err
}

const getSandboxForUpdate = `-- name: GetSandboxForUpdate :one
select s.id,s.job_id,s.name,r.ownership_nonce,s.active_resource_id,coalesce(r.provider_id,'') as provider_id
from dorf.sandboxes s join dorf.sandbox_resources r on r.id=s.active_resource_id
where s.id=$1
for update
`

type GetSandboxForUpdateRow struct {
	ID               string
	JobID            string
	Name             string
	OwnershipNonce   string
	ActiveResourceID string
	ProviderID       string
}

func (q *Queries) GetSandboxForUpdate(ctx context.Context, id string) (GetSandboxForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getSandboxForUpdate, id)
	var i GetSandboxForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.OwnershipNonce,
		&i.ActiveResourceID,
		&i.ProviderID,
	)
	return i, err
}

const getSandboxResource = `-- name: GetSandboxResource :one
select s.id,s.job_id,s.name,r.id as resource_id,r.ownership_nonce,coalesce(r.provider_id,'') as provider_id
from dorf.sandboxes s join dorf.sandbox_resources r on r.sandbox_id=s.id
where s.job_id=$1 and s.id=$2 and r.id=$3
`

type GetSandboxResourceParams struct {
	JobID      string
	SandboxID  string
	ResourceID string
}

type GetSandboxResourceRow struct {
	ID             string
	JobID          string
	Name           string
	ResourceID     string
	OwnershipNonce string
	ProviderID     string
}

func (q *Queries) GetSandboxResource(ctx context.Context, arg GetSandboxResourceParams) (GetSandboxResourceRow, error) {
	row := q.db.QueryRowContext(ctx, getSandboxResource, arg.JobID, arg.SandboxID, arg.ResourceID)
	var i GetSandboxResourceRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.ResourceID,
		&i.OwnershipNonce,
		&i.ProviderID,
	)
	return i, err
}

const listJobSandboxes = `-- name: ListJobSandboxes :many
select s.id,s.job_id,s.name,r.ownership_nonce,s.active_resource_id,coalesce(r.provider_id,'') as provider_id
from dorf.sandboxes s join dorf.sandbox_resources r on r.id=s.active_resource_id
where s.job_id=$1
order by s.id
`

type ListJobSandboxesRow struct {
	ID               string
	JobID            string
	Name             string
	OwnershipNonce   string
	ActiveResourceID string
	ProviderID       string
}

func (q *Queries) ListJobSandboxes(ctx context.Context, jobID string) ([]ListJobSandboxesRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobSandboxes, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobSandboxesRow
	for rows.Next() {
		var i ListJobSandboxesRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.OwnershipNonce,
			&i.ActiveResourceID,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxResources = `-- name: ListSandboxResources :many
select r.id,r.sandbox_id,r.ownership_nonce,coalesce(r.provider_id,'') as provider_id,
       r.reserved_at,r.observed_at,r.deleted_at
from dorf.sandbox_resources r join dorf.sandboxes s on s.id=r.sandbox_id
where s.job_id=$1
order by r.reserved_at,r.id
`

type ListSandboxResourcesRow struct {
	ID             string
	SandboxID      string
	OwnershipNonce string
	ProviderID     string
	ReservedAt     time.Time
	ObservedAt     sql.NullTime
	DeletedAt      sql.NullTime
}

func (q *Queries) ListSandboxResources(ctx context.Context, jobID string) ([]ListSandboxResourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSandboxResources, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSandboxResourcesRow
	for rows.Next() {
		var i ListSandboxResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.OwnershipNonce,
			&i.ProviderID,
			&i.ReservedAt,
			&i.ObservedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSandboxResourceDeleted = `-- name: RecordSandboxResourceDeleted :execrows
update dorf.sandbox_resources
set deleted_at=coalesce(deleted_at,clock_timestamp())
where id=$1 and sandbox_id=$2
`

type RecordSandboxResourceDeletedParams struct {
	ResourceID string
	SandboxID  string
}

func (q *Queries) RecordSandboxResourceDeleted(ctx context.Context, arg RecordSandboxResourceDeletedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordSandboxResourceDeleted, arg.ResourceID, arg.SandboxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reserveSandboxResource = `-- name: ReserveSandboxResource :exec
insert into dorf.sandbox_resources(id,sandbox_id,ownership_nonce)
values($1,$2,$3)
`

type ReserveSandboxResourceParams struct {
	ID             string
	SandboxID      string
	OwnershipNonce string
}

func (q *Queries) ReserveSandboxResource(ctx context.Context, arg ReserveSandboxResourceParams) error {
	_, err := q.db.ExecContext(ctx, reserveSandboxResource, arg.ID, arg.SandboxID, arg.OwnershipNonce)
	return err
}

const switchSandboxResource = `-- name: SwitchSandboxResource :execrows
update dorf.sandboxes set active_resource_id=$1
where id=$2 and active_resource_id=$3
`

type SwitchSandboxResourceParams struct {
	DestinationResourceID string
	SandboxID             string
	SourceResourceID      string
}

func (q *Queries) SwitchSandboxResource(ctx context.Context, arg SwitchSandboxResourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, switchSandboxResource, arg.DestinationResourceID, arg.SandboxID, arg.SourceResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
