// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package dbsql

import (
	"context"

	"github.com/aphronio/dorf/internal/spine"
)

const getRouteBySandbox = `-- name: GetRouteBySandbox :one
select id,sandbox_id,state
from dorf.routes
where sandbox_id=$1
`

func (q *Queries) GetRouteBySandbox(ctx context.Context, sandboxID string) (DorfRoute, error) {
	row := q.db.QueryRowContext(ctx, getRouteBySandbox, sandboxID)
	var i DorfRoute
	err := row.Scan(&i.ID, &i.SandboxID, &i.State)
	return i, err
}

const getSandbox = `-- name: GetSandbox :one
select id,job_id,state,ownership_nonce
from dorf.sandboxes
where id=$1
`

func (q *Queries) GetSandbox(ctx context.Context, id string) (DorfSandbox, error) {
	row := q.db.QueryRowContext(ctx, getSandbox, id)
	var i DorfSandbox
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.State,
		&i.OwnershipNonce,
	)
	return i, err
}

const getScopedActionBySandbox = `-- name: GetScopedActionBySandbox :one
select id,job_id,kind,state,coalesce(external_id,'') as external_id,
       coalesce(external_outcome,'') as external_outcome,scope_key
from dorf.actions
where job_id=$1 and kind=$2 and scope_key=$3
`

type GetScopedActionBySandboxParams struct {
	JobID     string
	Kind      spine.ActionKind
	SandboxID string
}

type GetScopedActionBySandboxRow struct {
	ID              string
	JobID           string
	Kind            spine.ActionKind
	State           spine.ActionState
	ExternalID      string
	ExternalOutcome string
	ScopeKey        string
}

func (q *Queries) GetScopedActionBySandbox(ctx context.Context, arg GetScopedActionBySandboxParams) (GetScopedActionBySandboxRow, error) {
	row := q.db.QueryRowContext(ctx, getScopedActionBySandbox, arg.JobID, arg.Kind, arg.SandboxID)
	var i GetScopedActionBySandboxRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.State,
		&i.ExternalID,
		&i.ExternalOutcome,
		&i.ScopeKey,
	)
	return i, err
}

const listJobSandboxes = `-- name: ListJobSandboxes :many
select s.id,s.job_id,s.state,s.ownership_nonce,
       coalesce(r.id,'') as route_id,coalesce(r.state,'') as route_state
from dorf.sandboxes s
left join dorf.routes r on r.sandbox_id=s.id
where s.job_id=$1
order by s.id
`

type ListJobSandboxesRow struct {
	ID             string
	JobID          string
	State          string
	OwnershipNonce string
	RouteID        string
	RouteState     string
}

func (q *Queries) ListJobSandboxes(ctx context.Context, jobID string) ([]ListJobSandboxesRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobSandboxes, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobSandboxesRow
	for rows.Next() {
		var i ListJobSandboxesRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.State,
			&i.OwnershipNonce,
			&i.RouteID,
			&i.RouteState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
