// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retries.sql

package dbsql

import (
	"context"
)

const getJobRetryRequest = `-- name: GetJobRetryRequest :one
select request_key,job_id,task_id,run_id,attempt
from dorf.job_retry_requests
where request_key=$1
`

func (q *Queries) GetJobRetryRequest(ctx context.Context, requestKey string) (DorfJobRetryRequest, error) {
	row := q.db.QueryRowContext(ctx, getJobRetryRequest, requestKey)
	var i DorfJobRetryRequest
	err := row.Scan(
		&i.RequestKey,
		&i.JobID,
		&i.TaskID,
		&i.RunID,
		&i.Attempt,
	)
	return i, err
}

const insertJobRetryRequest = `-- name: InsertJobRetryRequest :exec
insert into dorf.job_retry_requests(request_key,job_id,task_id,run_id,attempt)
values($1,$2,$3,$4,$5)
`

type InsertJobRetryRequestParams struct {
	RequestKey string
	JobID      string
	TaskID     string
	RunID      string
	Attempt    int32
}

func (q *Queries) InsertJobRetryRequest(ctx context.Context, arg InsertJobRetryRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertJobRetryRequest,
		arg.RequestKey,
		arg.JobID,
		arg.TaskID,
		arg.RunID,
		arg.Attempt,
	)
	return err
}

const lockJobRetryRequest = `-- name: LockJobRetryRequest :exec
select pg_advisory_xact_lock(hashtextextended('dorf-job-retry:' || $1::text,0))
`

func (q *Queries) LockJobRetryRequest(ctx context.Context, requestKey string) error {
	_, err := q.db.ExecContext(ctx, lockJobRetryRequest, requestKey)
	return err
}
