// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retries.sql

package dbsql

import (
	"context"
)

const getSessionRetryRequest = `-- name: GetSessionRetryRequest :one
select request_key,session_id,task_id,run_id,attempt
from dorf.session_retry_requests
where request_key=$1
`

func (q *Queries) GetSessionRetryRequest(ctx context.Context, requestKey string) (DorfSessionRetryRequest, error) {
	row := q.db.QueryRowContext(ctx, getSessionRetryRequest, requestKey)
	var i DorfSessionRetryRequest
	err := row.Scan(
		&i.RequestKey,
		&i.SessionID,
		&i.TaskID,
		&i.RunID,
		&i.Attempt,
	)
	return i, err
}

const insertSessionRetryRequest = `-- name: InsertSessionRetryRequest :exec
insert into dorf.session_retry_requests(request_key,session_id,task_id,run_id,attempt)
values($1,$2,$3,$4,$5)
`

type InsertSessionRetryRequestParams struct {
	RequestKey string
	SessionID  string
	TaskID     string
	RunID      string
	Attempt    int32
}

func (q *Queries) InsertSessionRetryRequest(ctx context.Context, arg InsertSessionRetryRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertSessionRetryRequest,
		arg.RequestKey,
		arg.SessionID,
		arg.TaskID,
		arg.RunID,
		arg.Attempt,
	)
	return err
}

const lockSessionRetryRequest = `-- name: LockSessionRetryRequest :exec
select pg_advisory_xact_lock(hashtextextended('dorf-job-retry:' || $1::text,0))
`

func (q *Queries) LockSessionRetryRequest(ctx context.Context, requestKey string) error {
	_, err := q.db.ExecContext(ctx, lockSessionRetryRequest, requestKey)
	return err
}
