// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package dbsql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/aphronio/dorf/internal/spine"
)

const getReviewFeedbackRunForUpdate = `-- name: GetReviewFeedbackRunForUpdate :one
select ar.job_id,coalesce(ar.input_revision,'') as input_revision,ar.role,ar.state,coalesce(ar.turn_id,'') as turn_id,
       coalesce(ar.capability,'') as capability,j.revision as current_revision,j.admission_open,
       exists(select 1 from dorf.job_outcomes o where o.job_id=j.id)::boolean as outcome_exists,
       (ar.harness is not null and ar.thread_id is not null and ar.turn_id is not null
        and exists(select 1 from dorf.actions a where a.job_id=ar.job_id
            and a.kind='sandbox-create' and a.scope_key=ar.sandbox_id and a.state='succeeded')
        and exists(select 1 from dorf.actions a where a.job_id=ar.job_id
            and a.kind='provider-route-create' and a.scope_key=ar.sandbox_id and a.state='succeeded')
        and exists(select 1 from dorf.actions a where a.job_id=ar.job_id
            and a.kind='review-checkout' and a.scope_key=ar.sandbox_id and a.state='succeeded'))::boolean as boundary_ready
from dorf.agent_runs ar
join dorf.jobs j on j.id=ar.job_id
where ar.id=$1
for update of j,ar
`

type GetReviewFeedbackRunForUpdateRow struct {
	JobID           string
	InputRevision   string
	Role            string
	State           spine.AgentRunState
	TurnID          string
	Capability      string
	CurrentRevision string
	AdmissionOpen   bool
	OutcomeExists   bool
	BoundaryReady   bool
}

func (q *Queries) GetReviewFeedbackRunForUpdate(ctx context.Context, runID string) (GetReviewFeedbackRunForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewFeedbackRunForUpdate, runID)
	var i GetReviewFeedbackRunForUpdateRow
	err := row.Scan(
		&i.JobID,
		&i.InputRevision,
		&i.Role,
		&i.State,
		&i.TurnID,
		&i.Capability,
		&i.CurrentRevision,
		&i.AdmissionOpen,
		&i.OutcomeExists,
		&i.BoundaryReady,
	)
	return i, err
}

const getReviewJobForUpdate = `-- name: GetReviewJobForUpdate :one
select revision,admission_open,
       exists(select 1 from dorf.job_outcomes where job_id=dorf.jobs.id) as outcome_exists
from dorf.jobs
where id=$1
for update
`

type GetReviewJobForUpdateRow struct {
	Revision      string
	AdmissionOpen bool
	OutcomeExists bool
}

func (q *Queries) GetReviewJobForUpdate(ctx context.Context, jobID string) (GetReviewJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewJobForUpdate, jobID)
	var i GetReviewJobForUpdateRow
	err := row.Scan(&i.Revision, &i.AdmissionOpen, &i.OutcomeExists)
	return i, err
}

const getReviewPlan = `-- name: GetReviewPlan :one
select job_id,revision,facts::text as facts,plan::text as plan,
       policy_digest,created_at
from dorf.review_plans
where job_id=$1 and revision=$2
`

type GetReviewPlanParams struct {
	JobID    string
	Revision string
}

type GetReviewPlanRow struct {
	JobID        string
	Revision     string
	Facts        string
	Plan         string
	PolicyDigest string
	CreatedAt    time.Time
}

func (q *Queries) GetReviewPlan(ctx context.Context, arg GetReviewPlanParams) (GetReviewPlanRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewPlan, arg.JobID, arg.Revision)
	var i GetReviewPlanRow
	err := row.Scan(
		&i.JobID,
		&i.Revision,
		&i.Facts,
		&i.Plan,
		&i.PolicyDigest,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewPlanDigestForUpdate = `-- name: GetReviewPlanDigestForUpdate :one
select policy_digest
from dorf.review_plans
where job_id=$1 and revision=$2
for update
`

type GetReviewPlanDigestForUpdateParams struct {
	JobID    string
	Revision string
}

func (q *Queries) GetReviewPlanDigestForUpdate(ctx context.Context, arg GetReviewPlanDigestForUpdateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getReviewPlanDigestForUpdate, arg.JobID, arg.Revision)
	var policy_digest string
	err := row.Scan(&policy_digest)
	return policy_digest, err
}

const getReviewRun = `-- name: GetReviewRun :one
select id, job_id, message_id, state, harness, thread_id, baseline_recorded, baseline_turn_id, turn_id, turn_outcome, attention, role, input_revision, capability, started_at, finished_at, request_from_kind, request_from_id, request_sequence, request_input, request_delivery_intent, request_target_turn_id, request_admitted_at, sandbox_id, ownership_nonce, submission_nonce
from dorf.review_run_projection
where id=$1 and role<>'implement'
`

func (q *Queries) GetReviewRun(ctx context.Context, runID string) (DorfReviewRunProjection, error) {
	row := q.db.QueryRowContext(ctx, getReviewRun, runID)
	var i DorfReviewRunProjection
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.MessageID,
		&i.State,
		&i.Harness,
		&i.ThreadID,
		&i.BaselineRecorded,
		&i.BaselineTurnID,
		&i.TurnID,
		&i.TurnOutcome,
		&i.Attention,
		&i.Role,
		&i.InputRevision,
		&i.Capability,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RequestFromKind,
		&i.RequestFromID,
		&i.RequestSequence,
		&i.RequestInput,
		&i.RequestDeliveryIntent,
		&i.RequestTargetTurnID,
		&i.RequestAdmittedAt,
		&i.SandboxID,
		&i.OwnershipNonce,
		&i.SubmissionNonce,
	)
	return i, err
}

const insertReviewAgentRun = `-- name: InsertReviewAgentRun :execrows
insert into dorf.agent_runs(id,job_id,message_id,role,state,input_revision,capability,sandbox_id,submission_nonce)
values($1,$2,$3,$4,'pending',
       $5::text,$6::text,$7,$8::text)
on conflict do nothing
`

type InsertReviewAgentRunParams struct {
	ID              string
	JobID           string
	MessageID       string
	Role            string
	InputRevision   string
	Capability      string
	SandboxID       string
	SubmissionNonce string
}

func (q *Queries) InsertReviewAgentRun(ctx context.Context, arg InsertReviewAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertReviewAgentRun,
		arg.ID,
		arg.JobID,
		arg.MessageID,
		arg.Role,
		arg.InputRevision,
		arg.Capability,
		arg.SandboxID,
		arg.SubmissionNonce,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertReviewPlan = `-- name: InsertReviewPlan :execrows
insert into dorf.review_plans(job_id,revision,facts,plan,policy_digest)
values($1,$2,$3::jsonb,
       $4::jsonb,$5::text)
on conflict do nothing
`

type InsertReviewPlanParams struct {
	JobID        string
	Revision     string
	Facts        json.RawMessage
	Plan         json.RawMessage
	PolicyDigest string
}

func (q *Queries) InsertReviewPlan(ctx context.Context, arg InsertReviewPlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertReviewPlan,
		arg.JobID,
		arg.Revision,
		arg.Facts,
		arg.Plan,
		arg.PolicyDigest,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const interruptAgentRun = `-- name: InterruptAgentRun :execrows
update dorf.agent_runs
set state='interrupted',
    turn_outcome=case when turn_id is null then null else 'interrupted' end,
    attention=$1::text,
    finished_at=case when started_at is null then null else coalesce(finished_at,clock_timestamp()) end
where id=$2 and state in ('pending','submitting','active','uncertain')
`

type InterruptAgentRunParams struct {
	Reason string
	RunID  string
}

func (q *Queries) InterruptAgentRun(ctx context.Context, arg InterruptAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptAgentRun, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAllReviewRuns = `-- name: ListAllReviewRuns :many
select p.id, p.job_id, p.message_id, p.state, p.harness, p.thread_id, p.baseline_recorded, p.baseline_turn_id, p.turn_id, p.turn_outcome, p.attention, p.role, p.input_revision, p.capability, p.started_at, p.finished_at, p.request_from_kind, p.request_from_id, p.request_sequence, p.request_input, p.request_delivery_intent, p.request_target_turn_id, p.request_admitted_at, p.sandbox_id, p.ownership_nonce, p.submission_nonce
from dorf.review_run_projection p
where p.job_id=$1 and p.input_revision<>'' and p.role<>'implement'
order by p.input_revision,p.role
`

type ListAllReviewRunsRow struct {
	DorfReviewRunProjection DorfReviewRunProjection
}

func (q *Queries) ListAllReviewRuns(ctx context.Context, jobID string) ([]ListAllReviewRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllReviewRuns, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReviewRunsRow
	for rows.Next() {
		var i ListAllReviewRunsRow
		if err := rows.Scan(
			&i.DorfReviewRunProjection.ID,
			&i.DorfReviewRunProjection.JobID,
			&i.DorfReviewRunProjection.MessageID,
			&i.DorfReviewRunProjection.State,
			&i.DorfReviewRunProjection.Harness,
			&i.DorfReviewRunProjection.ThreadID,
			&i.DorfReviewRunProjection.BaselineRecorded,
			&i.DorfReviewRunProjection.BaselineTurnID,
			&i.DorfReviewRunProjection.TurnID,
			&i.DorfReviewRunProjection.TurnOutcome,
			&i.DorfReviewRunProjection.Attention,
			&i.DorfReviewRunProjection.Role,
			&i.DorfReviewRunProjection.InputRevision,
			&i.DorfReviewRunProjection.Capability,
			&i.DorfReviewRunProjection.StartedAt,
			&i.DorfReviewRunProjection.FinishedAt,
			&i.DorfReviewRunProjection.RequestFromKind,
			&i.DorfReviewRunProjection.RequestFromID,
			&i.DorfReviewRunProjection.RequestSequence,
			&i.DorfReviewRunProjection.RequestInput,
			&i.DorfReviewRunProjection.RequestDeliveryIntent,
			&i.DorfReviewRunProjection.RequestTargetTurnID,
			&i.DorfReviewRunProjection.RequestAdmittedAt,
			&i.DorfReviewRunProjection.SandboxID,
			&i.DorfReviewRunProjection.OwnershipNonce,
			&i.DorfReviewRunProjection.SubmissionNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewCheckInputs = `-- name: ListReviewCheckInputs :many
select r.name,coalesce(e.id,'') as evidence_id
from dorf.repository_commands r
left join dorf.checks c
  on c.job_id=r.job_id and c.name=r.name and c.command=r.command
 and c.revision=$1
 and c.state='passed' and c.exit_code=0
left join dorf.evidence e
  on e.id=c.evidence_id and e.job_id=c.job_id and e.check_id=c.id and e.revision=c.revision
where r.job_id=$2 and r.name in ('check','smoke')
order by r.name
`

type ListReviewCheckInputsParams struct {
	Revision string
	JobID    string
}

type ListReviewCheckInputsRow struct {
	Name       string
	EvidenceID string
}

func (q *Queries) ListReviewCheckInputs(ctx context.Context, arg ListReviewCheckInputsParams) ([]ListReviewCheckInputsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewCheckInputs, arg.Revision, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewCheckInputsRow
	for rows.Next() {
		var i ListReviewCheckInputsRow
		if err := rows.Scan(&i.Name, &i.EvidenceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewPlans = `-- name: ListReviewPlans :many
select job_id,revision,facts::text as facts,plan::text as plan,
       policy_digest,created_at
from dorf.review_plans
where job_id=$1
order by created_at
`

type ListReviewPlansRow struct {
	JobID        string
	Revision     string
	Facts        string
	Plan         string
	PolicyDigest string
	CreatedAt    time.Time
}

func (q *Queries) ListReviewPlans(ctx context.Context, jobID string) ([]ListReviewPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewPlans, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewPlansRow
	for rows.Next() {
		var i ListReviewPlansRow
		if err := rows.Scan(
			&i.JobID,
			&i.Revision,
			&i.Facts,
			&i.Plan,
			&i.PolicyDigest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
