// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package dbsql

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/aphronio/dorf/internal/spine"
)

const advanceJobReviewFeedbackToReady = `-- name: AdvanceJobReviewFeedbackToReady :execrows
update dorf.jobs
set workflow_phase='ready',workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='review-feedback'
`

type AdvanceJobReviewFeedbackToReadyParams struct {
	JobID    string
	Revision string
}

func (q *Queries) AdvanceJobReviewFeedbackToReady(ctx context.Context, arg AdvanceJobReviewFeedbackToReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceJobReviewFeedbackToReady, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceJobToReviewFeedback = `-- name: AdvanceJobToReviewFeedback :execrows
update dorf.jobs
set workflow_phase='review-feedback',workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='reviewing'
`

type AdvanceJobToReviewFeedbackParams struct {
	JobID    string
	Revision string
}

func (q *Queries) AdvanceJobToReviewFeedback(ctx context.Context, arg AdvanceJobToReviewFeedbackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceJobToReviewFeedback, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceJobToReviewPlanning = `-- name: AdvanceJobToReviewPlanning :execrows
update dorf.jobs
set workflow_phase='review-planning', workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='checking'
`

type AdvanceJobToReviewPlanningParams struct {
	JobID    string
	Revision string
}

func (q *Queries) AdvanceJobToReviewPlanning(ctx context.Context, arg AdvanceJobToReviewPlanningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceJobToReviewPlanning, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceReviewPolicyPhase = `-- name: AdvanceReviewPolicyPhase :execrows
update dorf.jobs
set workflow_phase=$1,workflow_attention=null
where id=$2 and revision=$3 and workflow_phase='review-planning'
`

type AdvanceReviewPolicyPhaseParams struct {
	WorkflowPhase string
	JobID         string
	Revision      string
}

func (q *Queries) AdvanceReviewPolicyPhase(ctx context.Context, arg AdvanceReviewPolicyPhaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceReviewPolicyPhase, arg.WorkflowPhase, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countDeclaredReviewChecks = `-- name: CountDeclaredReviewChecks :one
select count(*)
from dorf.repository_commands
where job_id=$1 and name in ('check','smoke')
`

func (q *Queries) CountDeclaredReviewChecks(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeclaredReviewChecks, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMissingReviewFeedback = `-- name: CountMissingReviewFeedback :one
select count(*)
from dorf.review_resources rr
where rr.job_id=$1 and rr.revision=$2
  and not exists(
      select 1 from dorf.job_messages m
      where m.job_id=rr.job_id and m.from_kind='agent' and m.from_id=rr.run_id
  )
`

type CountMissingReviewFeedbackParams struct {
	JobID    string
	Revision string
}

func (q *Queries) CountMissingReviewFeedback(ctx context.Context, arg CountMissingReviewFeedbackParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMissingReviewFeedback, arg.JobID, arg.Revision)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failInterruptedReviewAction = `-- name: FailInterruptedReviewAction :exec
update dorf.actions
set state='failed',external_outcome=$1::text
where id=$2 and state in ('pending','uncertain')
`

type FailInterruptedReviewActionParams struct {
	Reason   string
	ActionID string
}

func (q *Queries) FailInterruptedReviewAction(ctx context.Context, arg FailInterruptedReviewActionParams) error {
	_, err := q.db.ExecContext(ctx, failInterruptedReviewAction, arg.Reason, arg.ActionID)
	return err
}

const finalizeReviewPlan = `-- name: FinalizeReviewPlan :exec
update dorf.review_plans
set state='final',facts=$1::jsonb,plan=$2::jsonb,
    policy_digest=$3::text,finalized_at=clock_timestamp()
where job_id=$4 and revision=$5 and policy_digest is null
`

type FinalizeReviewPlanParams struct {
	Facts        json.RawMessage
	Plan         json.RawMessage
	PolicyDigest string
	JobID        string
	Revision     string
}

func (q *Queries) FinalizeReviewPlan(ctx context.Context, arg FinalizeReviewPlanParams) error {
	_, err := q.db.ExecContext(ctx, finalizeReviewPlan,
		arg.Facts,
		arg.Plan,
		arg.PolicyDigest,
		arg.JobID,
		arg.Revision,
	)
	return err
}

const getReviewActionForUpdate = `-- name: GetReviewActionForUpdate :one
select id,job_id,coalesce(message_id,'') as message_id,kind,state,coalesce(external_id,'') as external_id,
       coalesce(external_outcome,'') as external_outcome,scope_key
from dorf.actions
where id=$1
for update
`

type GetReviewActionForUpdateRow struct {
	ID              string
	JobID           string
	MessageID       string
	Kind            spine.ActionKind
	State           spine.ActionState
	ExternalID      string
	ExternalOutcome string
	ScopeKey        string
}

func (q *Queries) GetReviewActionForUpdate(ctx context.Context, actionID string) (GetReviewActionForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewActionForUpdate, actionID)
	var i GetReviewActionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.MessageID,
		&i.Kind,
		&i.State,
		&i.ExternalID,
		&i.ExternalOutcome,
		&i.ScopeKey,
	)
	return i, err
}

const getReviewActionID = `-- name: GetReviewActionID :one
select case $1::text
    when 'sandbox-create' then rr.sandbox_create_action_id
    when 'provider-route-create' then rr.route_create_action_id
    when 'review-workspace-create' then rr.materialize_action_id
    when 'codex-session-start' then (
        select a.id from dorf.actions a where a.kind=$1 and a.scope_key=rr.run_id
    )
    when 'provider-route-revoke' then rr.route_revoke_action_id
    when 'sandbox-delete' then rr.sandbox_delete_action_id
end::text as action_id
from dorf.review_resources rr
where rr.run_id=$2
`

type GetReviewActionIDParams struct {
	Kind  string
	RunID string
}

func (q *Queries) GetReviewActionID(ctx context.Context, arg GetReviewActionIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getReviewActionID, arg.Kind, arg.RunID)
	var action_id string
	err := row.Scan(&action_id)
	return action_id, err
}

const getReviewCurrentRevision = `-- name: GetReviewCurrentRevision :one
select revision
from dorf.jobs
where id=$1
`

func (q *Queries) GetReviewCurrentRevision(ctx context.Context, jobID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getReviewCurrentRevision, jobID)
	var revision string
	err := row.Scan(&revision)
	return revision, err
}

const getReviewEvidenceIDs = `-- name: GetReviewEvidenceIDs :one
select coalesce(claim_evidence_id,'') as claim_evidence_id,
       coalesce(observed_evidence_id,'') as observed_evidence_id
from dorf.agent_runs
where id=$1
`

type GetReviewEvidenceIDsRow struct {
	ClaimEvidenceID    string
	ObservedEvidenceID string
}

func (q *Queries) GetReviewEvidenceIDs(ctx context.Context, runID string) (GetReviewEvidenceIDsRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewEvidenceIDs, runID)
	var i GetReviewEvidenceIDsRow
	err := row.Scan(&i.ClaimEvidenceID, &i.ObservedEvidenceID)
	return i, err
}

const getReviewFeedbackMessage = `-- name: GetReviewFeedbackMessage :one
select id,job_id,from_kind,from_id,sequence,input,delivery_intent,
       coalesce(steer_target_turn_id,'') as steer_target_turn_id
from dorf.job_messages m
where m.job_id=$1 and m.from_kind='agent' and m.from_id=$2
`

type GetReviewFeedbackMessageParams struct {
	JobID string
	RunID string
}

type GetReviewFeedbackMessageRow struct {
	ID                string
	JobID             string
	FromKind          spine.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	DeliveryIntent    spine.MessageDeliveryIntent
	SteerTargetTurnID string
}

func (q *Queries) GetReviewFeedbackMessage(ctx context.Context, arg GetReviewFeedbackMessageParams) (GetReviewFeedbackMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewFeedbackMessage, arg.JobID, arg.RunID)
	var i GetReviewFeedbackMessageRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.DeliveryIntent,
		&i.SteerTargetTurnID,
	)
	return i, err
}

const getReviewFeedbackRunForUpdate = `-- name: GetReviewFeedbackRunForUpdate :one
select ar.job_id,coalesce(ar.revision,'') as revision,ar.role,ar.state,coalesce(ar.native_turn_id,'') as native_turn_id,
       coalesce(ar.capability,'') as capability,j.revision as current_revision,j.workflow_phase
from dorf.agent_runs ar
join dorf.jobs j on j.id=ar.job_id
where ar.id=$1
for update of j,ar
`

type GetReviewFeedbackRunForUpdateRow struct {
	JobID           string
	Revision        string
	Role            string
	State           spine.AgentRunState
	NativeTurnID    string
	Capability      string
	CurrentRevision string
	WorkflowPhase   string
}

func (q *Queries) GetReviewFeedbackRunForUpdate(ctx context.Context, runID string) (GetReviewFeedbackRunForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewFeedbackRunForUpdate, runID)
	var i GetReviewFeedbackRunForUpdateRow
	err := row.Scan(
		&i.JobID,
		&i.Revision,
		&i.Role,
		&i.State,
		&i.NativeTurnID,
		&i.Capability,
		&i.CurrentRevision,
		&i.WorkflowPhase,
	)
	return i, err
}

const getReviewJobForUpdate = `-- name: GetReviewJobForUpdate :one
select revision, workflow_phase
from dorf.jobs
where id=$1
for update
`

type GetReviewJobForUpdateRow struct {
	Revision      string
	WorkflowPhase string
}

func (q *Queries) GetReviewJobForUpdate(ctx context.Context, jobID string) (GetReviewJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewJobForUpdate, jobID)
	var i GetReviewJobForUpdateRow
	err := row.Scan(&i.Revision, &i.WorkflowPhase)
	return i, err
}

const getReviewPlan = `-- name: GetReviewPlan :one
select job_id,revision,state,coalesce(facts,'{}'::jsonb)::text as facts,coalesce(plan,'{}'::jsonb)::text as plan,
       coalesce(policy_digest,'') as policy_digest,created_at,finalized_at
from dorf.review_plans
where job_id=$1 and revision=$2
`

type GetReviewPlanParams struct {
	JobID    string
	Revision string
}

type GetReviewPlanRow struct {
	JobID        string
	Revision     string
	State        string
	Facts        string
	Plan         string
	PolicyDigest string
	CreatedAt    time.Time
	FinalizedAt  sql.NullTime
}

func (q *Queries) GetReviewPlan(ctx context.Context, arg GetReviewPlanParams) (GetReviewPlanRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewPlan, arg.JobID, arg.Revision)
	var i GetReviewPlanRow
	err := row.Scan(
		&i.JobID,
		&i.Revision,
		&i.State,
		&i.Facts,
		&i.Plan,
		&i.PolicyDigest,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getReviewPlanForUpdate = `-- name: GetReviewPlanForUpdate :one
select job_id,revision,state,coalesce(facts,'{}'::jsonb)::text as facts,coalesce(plan,'{}'::jsonb)::text as plan,
       coalesce(policy_digest,'') as policy_digest,created_at,finalized_at
from dorf.review_plans
where job_id=$1 and revision=$2
for update
`

type GetReviewPlanForUpdateParams struct {
	JobID    string
	Revision string
}

type GetReviewPlanForUpdateRow struct {
	JobID        string
	Revision     string
	State        string
	Facts        string
	Plan         string
	PolicyDigest string
	CreatedAt    time.Time
	FinalizedAt  sql.NullTime
}

func (q *Queries) GetReviewPlanForUpdate(ctx context.Context, arg GetReviewPlanForUpdateParams) (GetReviewPlanForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewPlanForUpdate, arg.JobID, arg.Revision)
	var i GetReviewPlanForUpdateRow
	err := row.Scan(
		&i.JobID,
		&i.Revision,
		&i.State,
		&i.Facts,
		&i.Plan,
		&i.PolicyDigest,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getReviewRun = `-- name: GetReviewRun :one
select id, job_id, message_id, action_id, session_id, state, baseline_recorded, baseline_turn_id, native_turn_id, native_outcome, attention, role, revision, capability, workspace, input_contract, claim_evidence_id, observed_evidence_id, started_at, finished_at, input_tokens, cached_input_tokens, output_tokens, cost_microusd, usage_available, yield_count, reviewer_sandbox_id, reviewer_route_id, reviewer_app_server, reviewer_owner_nonce, submission_nonce, input_digest, revision_tree, reviewer_sandbox_state, reviewer_route_state, checkout_state, post_review_state
from dorf.review_run_projection
where id=$1
`

func (q *Queries) GetReviewRun(ctx context.Context, runID string) (DorfReviewRunProjection, error) {
	row := q.db.QueryRowContext(ctx, getReviewRun, runID)
	var i DorfReviewRunProjection
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.MessageID,
		&i.ActionID,
		&i.SessionID,
		&i.State,
		&i.BaselineRecorded,
		&i.BaselineTurnID,
		&i.NativeTurnID,
		&i.NativeOutcome,
		&i.Attention,
		&i.Role,
		&i.Revision,
		&i.Capability,
		&i.Workspace,
		&i.InputContract,
		&i.ClaimEvidenceID,
		&i.ObservedEvidenceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.CostMicrousd,
		&i.UsageAvailable,
		&i.YieldCount,
		&i.ReviewerSandboxID,
		&i.ReviewerRouteID,
		&i.ReviewerAppServer,
		&i.ReviewerOwnerNonce,
		&i.SubmissionNonce,
		&i.InputDigest,
		&i.RevisionTree,
		&i.ReviewerSandboxState,
		&i.ReviewerRouteState,
		&i.CheckoutState,
		&i.PostReviewState,
	)
	return i, err
}

const getReviewRunStateForUpdate = `-- name: GetReviewRunStateForUpdate :one
select ar.state
from dorf.agent_runs ar
join dorf.review_resources rr on rr.run_id=ar.id
where ar.id=$1 and ar.capability=$2::text
for update of ar
`

type GetReviewRunStateForUpdateParams struct {
	RunID      string
	Capability string
}

func (q *Queries) GetReviewRunStateForUpdate(ctx context.Context, arg GetReviewRunStateForUpdateParams) (spine.AgentRunState, error) {
	row := q.db.QueryRowContext(ctx, getReviewRunStateForUpdate, arg.RunID, arg.Capability)
	var state spine.AgentRunState
	err := row.Scan(&state)
	return state, err
}

const getReviewTurnActionForUpdate = `-- name: GetReviewTurnActionForUpdate :one
select ar.action_id
from dorf.agent_runs ar
join dorf.review_resources rr on rr.run_id=ar.id
where ar.id=$1 and ar.state in ('submitting','uncertain') and ar.capability=$2::text
for update of ar
`

type GetReviewTurnActionForUpdateParams struct {
	RunID      string
	Capability string
}

func (q *Queries) GetReviewTurnActionForUpdate(ctx context.Context, arg GetReviewTurnActionForUpdateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getReviewTurnActionForUpdate, arg.RunID, arg.Capability)
	var action_id string
	err := row.Scan(&action_id)
	return action_id, err
}

const insertReviewAction = `-- name: InsertReviewAction :exec
insert into dorf.actions(id,job_id,kind,state,scope_key)
values($1,$2,$3,'pending',$4)
on conflict do nothing
`

type InsertReviewActionParams struct {
	ID       string
	JobID    string
	Kind     spine.ActionKind
	ScopeKey string
}

func (q *Queries) InsertReviewAction(ctx context.Context, arg InsertReviewActionParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewAction,
		arg.ID,
		arg.JobID,
		arg.Kind,
		arg.ScopeKey,
	)
	return err
}

const insertReviewAgentRun = `-- name: InsertReviewAgentRun :exec
insert into dorf.agent_runs(id,job_id,action_id,role,state,revision,capability,workspace,input_contract)
values($1,$2,$3,$4,'pending',$5::text,
       $6::text,$7::text,$8::text)
on conflict do nothing
`

type InsertReviewAgentRunParams struct {
	ID            string
	JobID         string
	ActionID      string
	Role          string
	Revision      string
	Capability    string
	Workspace     string
	InputContract string
}

func (q *Queries) InsertReviewAgentRun(ctx context.Context, arg InsertReviewAgentRunParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewAgentRun,
		arg.ID,
		arg.JobID,
		arg.ActionID,
		arg.Role,
		arg.Revision,
		arg.Capability,
		arg.Workspace,
		arg.InputContract,
	)
	return err
}

const insertReviewFeedbackAction = `-- name: InsertReviewFeedbackAction :exec
insert into dorf.actions(id,job_id,message_id,kind,state)
values($1,$2,$3::text,$4,'pending')
`

type InsertReviewFeedbackActionParams struct {
	ID        string
	JobID     string
	MessageID string
	Kind      spine.ActionKind
}

func (q *Queries) InsertReviewFeedbackAction(ctx context.Context, arg InsertReviewFeedbackActionParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewFeedbackAction,
		arg.ID,
		arg.JobID,
		arg.MessageID,
		arg.Kind,
	)
	return err
}

const insertReviewFeedbackAgentRun = `-- name: InsertReviewFeedbackAgentRun :execrows
insert into dorf.agent_runs(id,job_id,message_id,action_id,session_id,role,state)
select $1,$2,$3::text,$4,native_session_id,'implement','pending'
from dorf.sessions
where job_id=$2
`

type InsertReviewFeedbackAgentRunParams struct {
	ID        string
	JobID     string
	MessageID string
	ActionID  string
}

func (q *Queries) InsertReviewFeedbackAgentRun(ctx context.Context, arg InsertReviewFeedbackAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertReviewFeedbackAgentRun,
		arg.ID,
		arg.JobID,
		arg.MessageID,
		arg.ActionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertReviewFeedbackMessage = `-- name: InsertReviewFeedbackMessage :exec
insert into dorf.job_messages(id,job_id,from_kind,from_id,sequence,input)
values($1,$2,$3,$4,$5,$6)
`

type InsertReviewFeedbackMessageParams struct {
	ID       string
	JobID    string
	FromKind spine.MessageFromKind
	FromID   string
	Sequence int64
	Input    string
}

func (q *Queries) InsertReviewFeedbackMessage(ctx context.Context, arg InsertReviewFeedbackMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewFeedbackMessage,
		arg.ID,
		arg.JobID,
		arg.FromKind,
		arg.FromID,
		arg.Sequence,
		arg.Input,
	)
	return err
}

const insertReviewPlan = `-- name: InsertReviewPlan :exec
insert into dorf.review_plans(job_id,revision,state)
values($1,$2,'pending')
`

type InsertReviewPlanParams struct {
	JobID    string
	Revision string
}

func (q *Queries) InsertReviewPlan(ctx context.Context, arg InsertReviewPlanParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewPlan, arg.JobID, arg.Revision)
	return err
}

const insertReviewResource = `-- name: InsertReviewResource :exec
insert into dorf.review_resources(
    run_id,job_id,revision,sandbox_name,ownership_nonce,submission_nonce,input_digest,
    sandbox_create_action_id,route_create_action_id,materialize_action_id,route_revoke_action_id,sandbox_delete_action_id
) values(
    $1,$2,$3,$4,$5,
    $6,$7,$8,$9,
    $10,$11,$12
)
on conflict do nothing
`

type InsertReviewResourceParams struct {
	RunID                 string
	JobID                 string
	Revision              string
	SandboxName           string
	OwnershipNonce        string
	SubmissionNonce       string
	InputDigest           string
	SandboxCreateActionID string
	RouteCreateActionID   string
	MaterializeActionID   string
	RouteRevokeActionID   string
	SandboxDeleteActionID string
}

func (q *Queries) InsertReviewResource(ctx context.Context, arg InsertReviewResourceParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewResource,
		arg.RunID,
		arg.JobID,
		arg.Revision,
		arg.SandboxName,
		arg.OwnershipNonce,
		arg.SubmissionNonce,
		arg.InputDigest,
		arg.SandboxCreateActionID,
		arg.RouteCreateActionID,
		arg.MaterializeActionID,
		arg.RouteRevokeActionID,
		arg.SandboxDeleteActionID,
	)
	return err
}

const interruptReviewAgentRun = `-- name: InterruptReviewAgentRun :one
update dorf.agent_runs
set state='interrupted',
    native_outcome=case when native_turn_id is null then null else 'interrupted' end,
    attention=$1::text,
    finished_at=case when started_at is null then null else coalesce(finished_at,clock_timestamp()) end,
    updated_at=clock_timestamp()
where id=$2 and state in ('pending','submitting','active','uncertain')
returning action_id
`

type InterruptReviewAgentRunParams struct {
	Reason string
	RunID  string
}

func (q *Queries) InterruptReviewAgentRun(ctx context.Context, arg InterruptReviewAgentRunParams) (string, error) {
	row := q.db.QueryRowContext(ctx, interruptReviewAgentRun, arg.Reason, arg.RunID)
	var action_id string
	err := row.Scan(&action_id)
	return action_id, err
}

const listAllReviewRuns = `-- name: ListAllReviewRuns :many
select p.id, p.job_id, p.message_id, p.action_id, p.session_id, p.state, p.baseline_recorded, p.baseline_turn_id, p.native_turn_id, p.native_outcome, p.attention, p.role, p.revision, p.capability, p.workspace, p.input_contract, p.claim_evidence_id, p.observed_evidence_id, p.started_at, p.finished_at, p.input_tokens, p.cached_input_tokens, p.output_tokens, p.cost_microusd, p.usage_available, p.yield_count, p.reviewer_sandbox_id, p.reviewer_route_id, p.reviewer_app_server, p.reviewer_owner_nonce, p.submission_nonce, p.input_digest, p.revision_tree, p.reviewer_sandbox_state, p.reviewer_route_state, p.checkout_state, p.post_review_state,coalesce(m.id,'') as feedback_message_id,(p.revision<>j.revision)::boolean as stale
from dorf.review_run_projection p
join dorf.jobs j on j.id=p.job_id
left join dorf.job_messages m
  on m.job_id=p.job_id and m.from_kind='agent' and m.from_id=p.id
where p.job_id=$1 and p.revision<>''
order by p.revision,p.role
`

type ListAllReviewRunsRow struct {
	DorfReviewRunProjection DorfReviewRunProjection
	FeedbackMessageID       string
	Stale                   bool
}

func (q *Queries) ListAllReviewRuns(ctx context.Context, jobID string) ([]ListAllReviewRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllReviewRuns, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReviewRunsRow
	for rows.Next() {
		var i ListAllReviewRunsRow
		if err := rows.Scan(
			&i.DorfReviewRunProjection.ID,
			&i.DorfReviewRunProjection.JobID,
			&i.DorfReviewRunProjection.MessageID,
			&i.DorfReviewRunProjection.ActionID,
			&i.DorfReviewRunProjection.SessionID,
			&i.DorfReviewRunProjection.State,
			&i.DorfReviewRunProjection.BaselineRecorded,
			&i.DorfReviewRunProjection.BaselineTurnID,
			&i.DorfReviewRunProjection.NativeTurnID,
			&i.DorfReviewRunProjection.NativeOutcome,
			&i.DorfReviewRunProjection.Attention,
			&i.DorfReviewRunProjection.Role,
			&i.DorfReviewRunProjection.Revision,
			&i.DorfReviewRunProjection.Capability,
			&i.DorfReviewRunProjection.Workspace,
			&i.DorfReviewRunProjection.InputContract,
			&i.DorfReviewRunProjection.ClaimEvidenceID,
			&i.DorfReviewRunProjection.ObservedEvidenceID,
			&i.DorfReviewRunProjection.StartedAt,
			&i.DorfReviewRunProjection.FinishedAt,
			&i.DorfReviewRunProjection.InputTokens,
			&i.DorfReviewRunProjection.CachedInputTokens,
			&i.DorfReviewRunProjection.OutputTokens,
			&i.DorfReviewRunProjection.CostMicrousd,
			&i.DorfReviewRunProjection.UsageAvailable,
			&i.DorfReviewRunProjection.YieldCount,
			&i.DorfReviewRunProjection.ReviewerSandboxID,
			&i.DorfReviewRunProjection.ReviewerRouteID,
			&i.DorfReviewRunProjection.ReviewerAppServer,
			&i.DorfReviewRunProjection.ReviewerOwnerNonce,
			&i.DorfReviewRunProjection.SubmissionNonce,
			&i.DorfReviewRunProjection.InputDigest,
			&i.DorfReviewRunProjection.RevisionTree,
			&i.DorfReviewRunProjection.ReviewerSandboxState,
			&i.DorfReviewRunProjection.ReviewerRouteState,
			&i.DorfReviewRunProjection.CheckoutState,
			&i.DorfReviewRunProjection.PostReviewState,
			&i.FeedbackMessageID,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCleanupReviewRuns = `-- name: ListCleanupReviewRuns :many
select p.id, p.job_id, p.message_id, p.action_id, p.session_id, p.state, p.baseline_recorded, p.baseline_turn_id, p.native_turn_id, p.native_outcome, p.attention, p.role, p.revision, p.capability, p.workspace, p.input_contract, p.claim_evidence_id, p.observed_evidence_id, p.started_at, p.finished_at, p.input_tokens, p.cached_input_tokens, p.output_tokens, p.cost_microusd, p.usage_available, p.yield_count, p.reviewer_sandbox_id, p.reviewer_route_id, p.reviewer_app_server, p.reviewer_owner_nonce, p.submission_nonce, p.input_digest, p.revision_tree, p.reviewer_sandbox_state, p.reviewer_route_state, p.checkout_state, p.post_review_state
from dorf.review_run_projection p
join dorf.review_resources rr on rr.run_id=p.id
where rr.job_id=$1
order by rr.revision,p.role
`

func (q *Queries) ListCleanupReviewRuns(ctx context.Context, jobID string) ([]DorfReviewRunProjection, error) {
	rows, err := q.db.QueryContext(ctx, listCleanupReviewRuns, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DorfReviewRunProjection
	for rows.Next() {
		var i DorfReviewRunProjection
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.MessageID,
			&i.ActionID,
			&i.SessionID,
			&i.State,
			&i.BaselineRecorded,
			&i.BaselineTurnID,
			&i.NativeTurnID,
			&i.NativeOutcome,
			&i.Attention,
			&i.Role,
			&i.Revision,
			&i.Capability,
			&i.Workspace,
			&i.InputContract,
			&i.ClaimEvidenceID,
			&i.ObservedEvidenceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.InputTokens,
			&i.CachedInputTokens,
			&i.OutputTokens,
			&i.CostMicrousd,
			&i.UsageAvailable,
			&i.YieldCount,
			&i.ReviewerSandboxID,
			&i.ReviewerRouteID,
			&i.ReviewerAppServer,
			&i.ReviewerOwnerNonce,
			&i.SubmissionNonce,
			&i.InputDigest,
			&i.RevisionTree,
			&i.ReviewerSandboxState,
			&i.ReviewerRouteState,
			&i.CheckoutState,
			&i.PostReviewState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeclaredReviewCheckNames = `-- name: ListDeclaredReviewCheckNames :many
select name
from dorf.repository_commands
where job_id=$1 and name in ('check','smoke')
order by name
`

func (q *Queries) ListDeclaredReviewCheckNames(ctx context.Context, jobID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeclaredReviewCheckNames, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewPlans = `-- name: ListReviewPlans :many
select job_id,revision,state,coalesce(facts,'{}'::jsonb)::text as facts,coalesce(plan,'{}'::jsonb)::text as plan,
       coalesce(policy_digest,'') as policy_digest,created_at,finalized_at
from dorf.review_plans
where job_id=$1
order by created_at
`

type ListReviewPlansRow struct {
	JobID        string
	Revision     string
	State        string
	Facts        string
	Plan         string
	PolicyDigest string
	CreatedAt    time.Time
	FinalizedAt  sql.NullTime
}

func (q *Queries) ListReviewPlans(ctx context.Context, jobID string) ([]ListReviewPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewPlans, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewPlansRow
	for rows.Next() {
		var i ListReviewPlansRow
		if err := rows.Scan(
			&i.JobID,
			&i.Revision,
			&i.State,
			&i.Facts,
			&i.Plan,
			&i.PolicyDigest,
			&i.CreatedAt,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRuns = `-- name: ListReviewRuns :many
select p.id, p.job_id, p.message_id, p.action_id, p.session_id, p.state, p.baseline_recorded, p.baseline_turn_id, p.native_turn_id, p.native_outcome, p.attention, p.role, p.revision, p.capability, p.workspace, p.input_contract, p.claim_evidence_id, p.observed_evidence_id, p.started_at, p.finished_at, p.input_tokens, p.cached_input_tokens, p.output_tokens, p.cost_microusd, p.usage_available, p.yield_count, p.reviewer_sandbox_id, p.reviewer_route_id, p.reviewer_app_server, p.reviewer_owner_nonce, p.submission_nonce, p.input_digest, p.revision_tree, p.reviewer_sandbox_state, p.reviewer_route_state, p.checkout_state, p.post_review_state,coalesce(m.id,'') as feedback_message_id,(p.revision<>j.revision)::boolean as stale
from dorf.review_run_projection p
join dorf.jobs j on j.id=p.job_id
left join dorf.job_messages m
  on m.job_id=p.job_id and m.from_kind='agent' and m.from_id=p.id
where p.job_id=$1 and p.revision=$2
order by p.role
`

type ListReviewRunsParams struct {
	JobID    string
	Revision string
}

type ListReviewRunsRow struct {
	DorfReviewRunProjection DorfReviewRunProjection
	FeedbackMessageID       string
	Stale                   bool
}

func (q *Queries) ListReviewRuns(ctx context.Context, arg ListReviewRunsParams) ([]ListReviewRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewRuns, arg.JobID, arg.Revision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewRunsRow
	for rows.Next() {
		var i ListReviewRunsRow
		if err := rows.Scan(
			&i.DorfReviewRunProjection.ID,
			&i.DorfReviewRunProjection.JobID,
			&i.DorfReviewRunProjection.MessageID,
			&i.DorfReviewRunProjection.ActionID,
			&i.DorfReviewRunProjection.SessionID,
			&i.DorfReviewRunProjection.State,
			&i.DorfReviewRunProjection.BaselineRecorded,
			&i.DorfReviewRunProjection.BaselineTurnID,
			&i.DorfReviewRunProjection.NativeTurnID,
			&i.DorfReviewRunProjection.NativeOutcome,
			&i.DorfReviewRunProjection.Attention,
			&i.DorfReviewRunProjection.Role,
			&i.DorfReviewRunProjection.Revision,
			&i.DorfReviewRunProjection.Capability,
			&i.DorfReviewRunProjection.Workspace,
			&i.DorfReviewRunProjection.InputContract,
			&i.DorfReviewRunProjection.ClaimEvidenceID,
			&i.DorfReviewRunProjection.ObservedEvidenceID,
			&i.DorfReviewRunProjection.StartedAt,
			&i.DorfReviewRunProjection.FinishedAt,
			&i.DorfReviewRunProjection.InputTokens,
			&i.DorfReviewRunProjection.CachedInputTokens,
			&i.DorfReviewRunProjection.OutputTokens,
			&i.DorfReviewRunProjection.CostMicrousd,
			&i.DorfReviewRunProjection.UsageAvailable,
			&i.DorfReviewRunProjection.YieldCount,
			&i.DorfReviewRunProjection.ReviewerSandboxID,
			&i.DorfReviewRunProjection.ReviewerRouteID,
			&i.DorfReviewRunProjection.ReviewerAppServer,
			&i.DorfReviewRunProjection.ReviewerOwnerNonce,
			&i.DorfReviewRunProjection.SubmissionNonce,
			&i.DorfReviewRunProjection.InputDigest,
			&i.DorfReviewRunProjection.RevisionTree,
			&i.DorfReviewRunProjection.ReviewerSandboxState,
			&i.DorfReviewRunProjection.ReviewerRouteState,
			&i.DorfReviewRunProjection.CheckoutState,
			&i.DorfReviewRunProjection.PostReviewState,
			&i.FeedbackMessageID,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedReviewEvidenceIDs = `-- name: ListVerifiedReviewEvidenceIDs :many
select c.evidence_id
from dorf.repository_commands r
join dorf.checks c
  on c.job_id=r.job_id and c.name=r.name and c.command=r.command and c.revision=$1
where r.job_id=$2 and r.name in ('check','smoke') and c.state='passed' and c.exit_code=0
order by r.name
`

type ListVerifiedReviewEvidenceIDsParams struct {
	Revision string
	JobID    string
}

func (q *Queries) ListVerifiedReviewEvidenceIDs(ctx context.Context, arg ListVerifiedReviewEvidenceIDsParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listVerifiedReviewEvidenceIDs, arg.Revision, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var evidence_id sql.NullString
		if err := rows.Scan(&evidence_id); err != nil {
			return nil, err
		}
		items = append(items, evidence_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReviewRunUncertain = `-- name: MarkReviewRunUncertain :execrows
update dorf.agent_runs
set state='uncertain',attention=$1::text,updated_at=clock_timestamp()
where id=$2 and session_id is null and native_turn_id is null
`

type MarkReviewRunUncertainParams struct {
	Reason string
	RunID  string
}

func (q *Queries) MarkReviewRunUncertain(ctx context.Context, arg MarkReviewRunUncertainParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markReviewRunUncertain, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markReviewSessionActionUncertain = `-- name: MarkReviewSessionActionUncertain :execrows
update dorf.actions
set state='uncertain',external_outcome=$1::text
where id=$2 and scope_key=$3 and kind='codex-session-start'
  and state in ('pending','uncertain')
`

type MarkReviewSessionActionUncertainParams struct {
	Outcome  string
	ActionID string
	RunID    string
}

func (q *Queries) MarkReviewSessionActionUncertain(ctx context.Context, arg MarkReviewSessionActionUncertainParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markReviewSessionActionUncertain, arg.Outcome, arg.ActionID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markReviewTurnActionUncertain = `-- name: MarkReviewTurnActionUncertain :execrows
update dorf.actions
set state='uncertain',external_outcome=$1::text
where id=$2 and state in ('pending','uncertain')
`

type MarkReviewTurnActionUncertainParams struct {
	Outcome  string
	ActionID string
}

func (q *Queries) MarkReviewTurnActionUncertain(ctx context.Context, arg MarkReviewTurnActionUncertainParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markReviewTurnActionUncertain, arg.Outcome, arg.ActionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reviewBoundaryReady = `-- name: ReviewBoundaryReady :one
select exists(
    select 1 from dorf.review_resources
    where run_id=$1 and sandbox_state='created' and route_state='active'
      and checkout_state='verified' and post_review_state='verified'
      and app_server_id is not null and revision_tree is not null
)
`

func (q *Queries) ReviewBoundaryReady(ctx context.Context, runID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, reviewBoundaryReady, runID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateReviewEvidenceAndUsage = `-- name: UpdateReviewEvidenceAndUsage :exec
update dorf.agent_runs
set claim_evidence_id=$1::text,observed_evidence_id=$2::text,
    input_tokens=$3,cached_input_tokens=$4,
    output_tokens=$5,cost_microusd=$6,usage_available=$7,
    finished_at=coalesce(finished_at,clock_timestamp())
where id=$8
`

type UpdateReviewEvidenceAndUsageParams struct {
	ClaimEvidenceID    string
	ObservedEvidenceID string
	InputTokens        int64
	CachedInputTokens  int64
	OutputTokens       int64
	CostMicrousd       int64
	UsageAvailable     bool
	RunID              string
}

func (q *Queries) UpdateReviewEvidenceAndUsage(ctx context.Context, arg UpdateReviewEvidenceAndUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateReviewEvidenceAndUsage,
		arg.ClaimEvidenceID,
		arg.ObservedEvidenceID,
		arg.InputTokens,
		arg.CachedInputTokens,
		arg.OutputTokens,
		arg.CostMicrousd,
		arg.UsageAvailable,
		arg.RunID,
	)
	return err
}

const verifyReviewPostState = `-- name: VerifyReviewPostState :execrows
update dorf.review_resources rr
set post_review_state='verified',post_review_verified_at=coalesce(post_review_verified_at,clock_timestamp())
from dorf.agent_runs ar
where rr.run_id=$1 and ar.id=rr.run_id and rr.sandbox_state='created' and rr.route_state='active'
  and rr.checkout_state='verified' and rr.revision=$2 and rr.revision_tree=$3::text
  and ar.workspace=$4::text
`

type VerifyReviewPostStateParams struct {
	RunID        string
	Revision     string
	RevisionTree string
	Workspace    string
}

func (q *Queries) VerifyReviewPostState(ctx context.Context, arg VerifyReviewPostStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, verifyReviewPostState,
		arg.RunID,
		arg.Revision,
		arg.RevisionTree,
		arg.Workspace,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
