// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package dbsql

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/aphronio/dorf/internal/spine"
)

const advanceJobReviewFeedbackToReady = `-- name: AdvanceJobReviewFeedbackToReady :execrows
update dorf.jobs
set workflow_phase='ready',workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='review-feedback'
`

type AdvanceJobReviewFeedbackToReadyParams struct {
	JobID    string
	Revision string
}

func (q *Queries) AdvanceJobReviewFeedbackToReady(ctx context.Context, arg AdvanceJobReviewFeedbackToReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceJobReviewFeedbackToReady, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceJobToReviewFeedback = `-- name: AdvanceJobToReviewFeedback :execrows
update dorf.jobs
set workflow_phase='review-feedback',workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='reviewing'
`

type AdvanceJobToReviewFeedbackParams struct {
	JobID    string
	Revision string
}

func (q *Queries) AdvanceJobToReviewFeedback(ctx context.Context, arg AdvanceJobToReviewFeedbackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceJobToReviewFeedback, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceJobToReviewPlanning = `-- name: AdvanceJobToReviewPlanning :execrows
update dorf.jobs
set workflow_phase='review-planning', workflow_attention=null
where id=$1 and revision=$2 and workflow_phase='checking'
`

type AdvanceJobToReviewPlanningParams struct {
	JobID    string
	Revision string
}

func (q *Queries) AdvanceJobToReviewPlanning(ctx context.Context, arg AdvanceJobToReviewPlanningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceJobToReviewPlanning, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceReviewPolicyPhase = `-- name: AdvanceReviewPolicyPhase :execrows
update dorf.jobs
set workflow_phase=$1,workflow_attention=null
where id=$2 and revision=$3 and workflow_phase='review-planning'
`

type AdvanceReviewPolicyPhaseParams struct {
	WorkflowPhase string
	JobID         string
	Revision      string
}

func (q *Queries) AdvanceReviewPolicyPhase(ctx context.Context, arg AdvanceReviewPolicyPhaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceReviewPolicyPhase, arg.WorkflowPhase, arg.JobID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countDeclaredReviewChecks = `-- name: CountDeclaredReviewChecks :one
select count(*)
from dorf.repository_commands
where job_id=$1 and name in ('check','smoke')
`

func (q *Queries) CountDeclaredReviewChecks(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeclaredReviewChecks, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMissingReviewFeedback = `-- name: CountMissingReviewFeedback :one
select count(*)
from dorf.agent_runs ar
where ar.job_id=$1 and ar.revision=$2
  and not exists(
      select 1 from dorf.job_messages m
      where m.job_id=ar.job_id and m.from_kind='agent' and m.from_id=ar.id
  )
`

type CountMissingReviewFeedbackParams struct {
	JobID    string
	Revision sql.NullString
}

func (q *Queries) CountMissingReviewFeedback(ctx context.Context, arg CountMissingReviewFeedbackParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMissingReviewFeedback, arg.JobID, arg.Revision)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finalizeReviewPlan = `-- name: FinalizeReviewPlan :exec
update dorf.review_plans
set state='final',facts=$1::jsonb,plan=$2::jsonb,
    policy_digest=$3::text,finalized_at=clock_timestamp()
where job_id=$4 and revision=$5 and policy_digest is null
`

type FinalizeReviewPlanParams struct {
	Facts        json.RawMessage
	Plan         json.RawMessage
	PolicyDigest string
	JobID        string
	Revision     string
}

func (q *Queries) FinalizeReviewPlan(ctx context.Context, arg FinalizeReviewPlanParams) error {
	_, err := q.db.ExecContext(ctx, finalizeReviewPlan,
		arg.Facts,
		arg.Plan,
		arg.PolicyDigest,
		arg.JobID,
		arg.Revision,
	)
	return err
}

const getReviewCurrentRevision = `-- name: GetReviewCurrentRevision :one
select revision
from dorf.jobs
where id=$1
`

func (q *Queries) GetReviewCurrentRevision(ctx context.Context, jobID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getReviewCurrentRevision, jobID)
	var revision string
	err := row.Scan(&revision)
	return revision, err
}

const getReviewFeedbackMessage = `-- name: GetReviewFeedbackMessage :one
select id,job_id,from_kind,from_id,sequence,input,delivery_intent,
       coalesce(steer_target_turn_id,'') as steer_target_turn_id
from dorf.job_messages m
where m.job_id=$1 and m.from_kind='agent' and m.from_id=$2
`

type GetReviewFeedbackMessageParams struct {
	JobID string
	RunID string
}

type GetReviewFeedbackMessageRow struct {
	ID                string
	JobID             string
	FromKind          spine.MessageFromKind
	FromID            string
	Sequence          int64
	Input             string
	DeliveryIntent    spine.MessageDeliveryIntent
	SteerTargetTurnID string
}

func (q *Queries) GetReviewFeedbackMessage(ctx context.Context, arg GetReviewFeedbackMessageParams) (GetReviewFeedbackMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewFeedbackMessage, arg.JobID, arg.RunID)
	var i GetReviewFeedbackMessageRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.FromKind,
		&i.FromID,
		&i.Sequence,
		&i.Input,
		&i.DeliveryIntent,
		&i.SteerTargetTurnID,
	)
	return i, err
}

const getReviewFeedbackRunForUpdate = `-- name: GetReviewFeedbackRunForUpdate :one
select ar.job_id,coalesce(ar.revision,'') as revision,ar.role,ar.state,coalesce(ar.turn_id,'') as turn_id,
       coalesce(ar.capability,'') as capability,j.revision as current_revision,j.workflow_phase
from dorf.agent_runs ar
join dorf.jobs j on j.id=ar.job_id
where ar.id=$1
for update of j,ar
`

type GetReviewFeedbackRunForUpdateRow struct {
	JobID           string
	Revision        string
	Role            string
	State           spine.AgentRunState
	TurnID          string
	Capability      string
	CurrentRevision string
	WorkflowPhase   string
}

func (q *Queries) GetReviewFeedbackRunForUpdate(ctx context.Context, runID string) (GetReviewFeedbackRunForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewFeedbackRunForUpdate, runID)
	var i GetReviewFeedbackRunForUpdateRow
	err := row.Scan(
		&i.JobID,
		&i.Revision,
		&i.Role,
		&i.State,
		&i.TurnID,
		&i.Capability,
		&i.CurrentRevision,
		&i.WorkflowPhase,
	)
	return i, err
}

const getReviewJobForUpdate = `-- name: GetReviewJobForUpdate :one
select revision, workflow_phase
from dorf.jobs
where id=$1
for update
`

type GetReviewJobForUpdateRow struct {
	Revision      string
	WorkflowPhase string
}

func (q *Queries) GetReviewJobForUpdate(ctx context.Context, jobID string) (GetReviewJobForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewJobForUpdate, jobID)
	var i GetReviewJobForUpdateRow
	err := row.Scan(&i.Revision, &i.WorkflowPhase)
	return i, err
}

const getReviewPlan = `-- name: GetReviewPlan :one
select job_id,revision,state,coalesce(facts,'{}'::jsonb)::text as facts,coalesce(plan,'{}'::jsonb)::text as plan,
       coalesce(policy_digest,'') as policy_digest,created_at,finalized_at
from dorf.review_plans
where job_id=$1 and revision=$2
`

type GetReviewPlanParams struct {
	JobID    string
	Revision string
}

type GetReviewPlanRow struct {
	JobID        string
	Revision     string
	State        string
	Facts        string
	Plan         string
	PolicyDigest string
	CreatedAt    time.Time
	FinalizedAt  sql.NullTime
}

func (q *Queries) GetReviewPlan(ctx context.Context, arg GetReviewPlanParams) (GetReviewPlanRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewPlan, arg.JobID, arg.Revision)
	var i GetReviewPlanRow
	err := row.Scan(
		&i.JobID,
		&i.Revision,
		&i.State,
		&i.Facts,
		&i.Plan,
		&i.PolicyDigest,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getReviewPlanForUpdate = `-- name: GetReviewPlanForUpdate :one
select job_id,revision,state,coalesce(facts,'{}'::jsonb)::text as facts,coalesce(plan,'{}'::jsonb)::text as plan,
       coalesce(policy_digest,'') as policy_digest,created_at,finalized_at
from dorf.review_plans
where job_id=$1 and revision=$2
for update
`

type GetReviewPlanForUpdateParams struct {
	JobID    string
	Revision string
}

type GetReviewPlanForUpdateRow struct {
	JobID        string
	Revision     string
	State        string
	Facts        string
	Plan         string
	PolicyDigest string
	CreatedAt    time.Time
	FinalizedAt  sql.NullTime
}

func (q *Queries) GetReviewPlanForUpdate(ctx context.Context, arg GetReviewPlanForUpdateParams) (GetReviewPlanForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewPlanForUpdate, arg.JobID, arg.Revision)
	var i GetReviewPlanForUpdateRow
	err := row.Scan(
		&i.JobID,
		&i.Revision,
		&i.State,
		&i.Facts,
		&i.Plan,
		&i.PolicyDigest,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getReviewRun = `-- name: GetReviewRun :one
select id, job_id, message_id, state, harness, thread_id, baseline_recorded, baseline_turn_id, turn_id, turn_outcome, attention, role, revision, capability, started_at, finished_at, request_from_kind, request_from_id, request_sequence, request_input, request_delivery_intent, request_target_turn_id, sandbox_id, ownership_nonce, submission_nonce
from dorf.review_run_projection
where id=$1
`

func (q *Queries) GetReviewRun(ctx context.Context, runID string) (DorfReviewRunProjection, error) {
	row := q.db.QueryRowContext(ctx, getReviewRun, runID)
	var i DorfReviewRunProjection
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.MessageID,
		&i.State,
		&i.Harness,
		&i.ThreadID,
		&i.BaselineRecorded,
		&i.BaselineTurnID,
		&i.TurnID,
		&i.TurnOutcome,
		&i.Attention,
		&i.Role,
		&i.Revision,
		&i.Capability,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RequestFromKind,
		&i.RequestFromID,
		&i.RequestSequence,
		&i.RequestInput,
		&i.RequestDeliveryIntent,
		&i.RequestTargetTurnID,
		&i.SandboxID,
		&i.OwnershipNonce,
		&i.SubmissionNonce,
	)
	return i, err
}

const insertReviewAction = `-- name: InsertReviewAction :exec
insert into dorf.actions(id,job_id,kind,state,scope_key)
values($1,$2,$3,'pending',$4)
on conflict do nothing
`

type InsertReviewActionParams struct {
	ID       string
	JobID    string
	Kind     spine.ActionKind
	ScopeKey string
}

func (q *Queries) InsertReviewAction(ctx context.Context, arg InsertReviewActionParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewAction,
		arg.ID,
		arg.JobID,
		arg.Kind,
		arg.ScopeKey,
	)
	return err
}

const insertReviewAgentRun = `-- name: InsertReviewAgentRun :exec
insert into dorf.agent_runs(id,job_id,message_id,role,state,revision,capability,sandbox_id,submission_nonce)
values($1,$2,$3,$4,'pending',
       $5::text,$6::text,$7,$8::text)
on conflict do nothing
`

type InsertReviewAgentRunParams struct {
	ID              string
	JobID           string
	MessageID       string
	Role            string
	Revision        string
	Capability      string
	SandboxID       string
	SubmissionNonce string
}

func (q *Queries) InsertReviewAgentRun(ctx context.Context, arg InsertReviewAgentRunParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewAgentRun,
		arg.ID,
		arg.JobID,
		arg.MessageID,
		arg.Role,
		arg.Revision,
		arg.Capability,
		arg.SandboxID,
		arg.SubmissionNonce,
	)
	return err
}

const insertReviewPlan = `-- name: InsertReviewPlan :exec
insert into dorf.review_plans(job_id,revision,state)
values($1,$2,'pending')
`

type InsertReviewPlanParams struct {
	JobID    string
	Revision string
}

func (q *Queries) InsertReviewPlan(ctx context.Context, arg InsertReviewPlanParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewPlan, arg.JobID, arg.Revision)
	return err
}

const interruptAgentRun = `-- name: InterruptAgentRun :execrows
update dorf.agent_runs
set state='interrupted',
    turn_outcome=case when turn_id is null then null else 'interrupted' end,
    attention=$1::text,
    finished_at=case when started_at is null then null else coalesce(finished_at,clock_timestamp()) end
where id=$2 and state in ('pending','submitting','active','uncertain')
`

type InterruptAgentRunParams struct {
	Reason string
	RunID  string
}

func (q *Queries) InterruptAgentRun(ctx context.Context, arg InterruptAgentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptAgentRun, arg.Reason, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAllReviewRuns = `-- name: ListAllReviewRuns :many
select p.id, p.job_id, p.message_id, p.state, p.harness, p.thread_id, p.baseline_recorded, p.baseline_turn_id, p.turn_id, p.turn_outcome, p.attention, p.role, p.revision, p.capability, p.started_at, p.finished_at, p.request_from_kind, p.request_from_id, p.request_sequence, p.request_input, p.request_delivery_intent, p.request_target_turn_id, p.sandbox_id, p.ownership_nonce, p.submission_nonce,coalesce(m.id,'') as feedback_message_id,(p.revision<>j.revision)::boolean as stale
from dorf.review_run_projection p
join dorf.jobs j on j.id=p.job_id
left join dorf.job_messages m
  on m.job_id=p.job_id and m.from_kind='agent' and m.from_id=p.id
where p.job_id=$1 and p.revision<>''
order by p.revision,p.role
`

type ListAllReviewRunsRow struct {
	DorfReviewRunProjection DorfReviewRunProjection
	FeedbackMessageID       string
	Stale                   bool
}

func (q *Queries) ListAllReviewRuns(ctx context.Context, jobID string) ([]ListAllReviewRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllReviewRuns, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReviewRunsRow
	for rows.Next() {
		var i ListAllReviewRunsRow
		if err := rows.Scan(
			&i.DorfReviewRunProjection.ID,
			&i.DorfReviewRunProjection.JobID,
			&i.DorfReviewRunProjection.MessageID,
			&i.DorfReviewRunProjection.State,
			&i.DorfReviewRunProjection.Harness,
			&i.DorfReviewRunProjection.ThreadID,
			&i.DorfReviewRunProjection.BaselineRecorded,
			&i.DorfReviewRunProjection.BaselineTurnID,
			&i.DorfReviewRunProjection.TurnID,
			&i.DorfReviewRunProjection.TurnOutcome,
			&i.DorfReviewRunProjection.Attention,
			&i.DorfReviewRunProjection.Role,
			&i.DorfReviewRunProjection.Revision,
			&i.DorfReviewRunProjection.Capability,
			&i.DorfReviewRunProjection.StartedAt,
			&i.DorfReviewRunProjection.FinishedAt,
			&i.DorfReviewRunProjection.RequestFromKind,
			&i.DorfReviewRunProjection.RequestFromID,
			&i.DorfReviewRunProjection.RequestSequence,
			&i.DorfReviewRunProjection.RequestInput,
			&i.DorfReviewRunProjection.RequestDeliveryIntent,
			&i.DorfReviewRunProjection.RequestTargetTurnID,
			&i.DorfReviewRunProjection.SandboxID,
			&i.DorfReviewRunProjection.OwnershipNonce,
			&i.DorfReviewRunProjection.SubmissionNonce,
			&i.FeedbackMessageID,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeclaredReviewCheckNames = `-- name: ListDeclaredReviewCheckNames :many
select name
from dorf.repository_commands
where job_id=$1 and name in ('check','smoke')
order by name
`

func (q *Queries) ListDeclaredReviewCheckNames(ctx context.Context, jobID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeclaredReviewCheckNames, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewPlans = `-- name: ListReviewPlans :many
select job_id,revision,state,coalesce(facts,'{}'::jsonb)::text as facts,coalesce(plan,'{}'::jsonb)::text as plan,
       coalesce(policy_digest,'') as policy_digest,created_at,finalized_at
from dorf.review_plans
where job_id=$1
order by created_at
`

type ListReviewPlansRow struct {
	JobID        string
	Revision     string
	State        string
	Facts        string
	Plan         string
	PolicyDigest string
	CreatedAt    time.Time
	FinalizedAt  sql.NullTime
}

func (q *Queries) ListReviewPlans(ctx context.Context, jobID string) ([]ListReviewPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewPlans, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewPlansRow
	for rows.Next() {
		var i ListReviewPlansRow
		if err := rows.Scan(
			&i.JobID,
			&i.Revision,
			&i.State,
			&i.Facts,
			&i.Plan,
			&i.PolicyDigest,
			&i.CreatedAt,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRuns = `-- name: ListReviewRuns :many
select p.id, p.job_id, p.message_id, p.state, p.harness, p.thread_id, p.baseline_recorded, p.baseline_turn_id, p.turn_id, p.turn_outcome, p.attention, p.role, p.revision, p.capability, p.started_at, p.finished_at, p.request_from_kind, p.request_from_id, p.request_sequence, p.request_input, p.request_delivery_intent, p.request_target_turn_id, p.sandbox_id, p.ownership_nonce, p.submission_nonce,coalesce(m.id,'') as feedback_message_id,(p.revision<>j.revision)::boolean as stale
from dorf.review_run_projection p
join dorf.jobs j on j.id=p.job_id
left join dorf.job_messages m
  on m.job_id=p.job_id and m.from_kind='agent' and m.from_id=p.id
where p.job_id=$1 and p.revision=$2
order by p.role
`

type ListReviewRunsParams struct {
	JobID    string
	Revision string
}

type ListReviewRunsRow struct {
	DorfReviewRunProjection DorfReviewRunProjection
	FeedbackMessageID       string
	Stale                   bool
}

func (q *Queries) ListReviewRuns(ctx context.Context, arg ListReviewRunsParams) ([]ListReviewRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewRuns, arg.JobID, arg.Revision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewRunsRow
	for rows.Next() {
		var i ListReviewRunsRow
		if err := rows.Scan(
			&i.DorfReviewRunProjection.ID,
			&i.DorfReviewRunProjection.JobID,
			&i.DorfReviewRunProjection.MessageID,
			&i.DorfReviewRunProjection.State,
			&i.DorfReviewRunProjection.Harness,
			&i.DorfReviewRunProjection.ThreadID,
			&i.DorfReviewRunProjection.BaselineRecorded,
			&i.DorfReviewRunProjection.BaselineTurnID,
			&i.DorfReviewRunProjection.TurnID,
			&i.DorfReviewRunProjection.TurnOutcome,
			&i.DorfReviewRunProjection.Attention,
			&i.DorfReviewRunProjection.Role,
			&i.DorfReviewRunProjection.Revision,
			&i.DorfReviewRunProjection.Capability,
			&i.DorfReviewRunProjection.StartedAt,
			&i.DorfReviewRunProjection.FinishedAt,
			&i.DorfReviewRunProjection.RequestFromKind,
			&i.DorfReviewRunProjection.RequestFromID,
			&i.DorfReviewRunProjection.RequestSequence,
			&i.DorfReviewRunProjection.RequestInput,
			&i.DorfReviewRunProjection.RequestDeliveryIntent,
			&i.DorfReviewRunProjection.RequestTargetTurnID,
			&i.DorfReviewRunProjection.SandboxID,
			&i.DorfReviewRunProjection.OwnershipNonce,
			&i.DorfReviewRunProjection.SubmissionNonce,
			&i.FeedbackMessageID,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedReviewEvidenceIDs = `-- name: ListVerifiedReviewEvidenceIDs :many
select c.evidence_id
from dorf.repository_commands r
join dorf.checks c
  on c.job_id=r.job_id and c.name=r.name and c.command=r.command and c.revision=$1
where r.job_id=$2 and r.name in ('check','smoke') and c.state='passed' and c.exit_code=0
order by r.name
`

type ListVerifiedReviewEvidenceIDsParams struct {
	Revision string
	JobID    string
}

func (q *Queries) ListVerifiedReviewEvidenceIDs(ctx context.Context, arg ListVerifiedReviewEvidenceIDsParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listVerifiedReviewEvidenceIDs, arg.Revision, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var evidence_id sql.NullString
		if err := rows.Scan(&evidence_id); err != nil {
			return nil, err
		}
		items = append(items, evidence_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewBoundaryReady = `-- name: ReviewBoundaryReady :one
select exists(
    select 1 from dorf.agent_runs ar
    join dorf.sandboxes s on s.id=ar.sandbox_id
    where ar.id=$1
      and ar.harness is not null and ar.thread_id is not null and ar.turn_id is not null
      and exists(select 1 from dorf.actions a where a.job_id=ar.job_id
          and a.kind='sandbox-create' and a.scope_key=s.id and a.state='succeeded')
      and exists(select 1 from dorf.actions a where a.job_id=ar.job_id
          and a.kind='provider-route-create' and a.scope_key=s.id and a.state='succeeded')
      and exists(select 1 from dorf.actions a where a.job_id=ar.job_id
          and a.kind='review-checkout' and a.scope_key=s.id and a.state='succeeded')
)
`

func (q *Queries) ReviewBoundaryReady(ctx context.Context, runID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, reviewBoundaryReady, runID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
