// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upgrades.sql

package dbsql

import (
	"context"
	"database/sql"
	"time"
)

const bindRecoveredResource = `-- name: BindRecoveredResource :execrows
update dorf.sandbox_resources set provider_id=$1::text,observed_at=coalesce(observed_at,clock_timestamp())
where id=$2 and deleted_at is null and (provider_id is null or provider_id=$1::text)
`

type BindRecoveredResourceParams struct {
	ProviderID string
	ResourceID string
}

func (q *Queries) BindRecoveredResource(ctx context.Context, arg BindRecoveredResourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindRecoveredResource, arg.ProviderID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindUpgradeDestination = `-- name: BindUpgradeDestination :execrows
update dorf.sandbox_upgrades set destination_resource_id=$1::text
where id=$2 and rollback_at is not null and
(destination_resource_id is null or destination_resource_id=$1::text)
`

type BindUpgradeDestinationParams struct {
	ResourceID string
	ID         string
}

func (q *Queries) BindUpgradeDestination(ctx context.Context, arg BindUpgradeDestinationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindUpgradeDestination, arg.ResourceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSandboxUpgrade = `-- name: GetSandboxUpgrade :one
select u.id, u.sandbox_id, u.source_resource_id, u.destination_resource_id, u.package_path, u.version, u.requested_at, u.previous_version, u.quiesced_at, u.checkpoint_key, u.checkpoint_reference, u.checkpoint_source_id, u.activated_at, u.rollback_at, u.failure_code, u.restored_at, u.verified_at, u.checkpoint_deleted_at, u.finished_at,s.job_id,coalesce(src.provider_id,'') as source_provider_id,coalesce(dst.provider_id,'') as destination_provider_id from dorf.sandbox_upgrades u join dorf.sandboxes s on s.id=u.sandbox_id join dorf.sandbox_resources src on src.id=u.source_resource_id left join dorf.sandbox_resources dst on dst.id=u.destination_resource_id where u.id=$1
`

type GetSandboxUpgradeRow struct {
	ID                    string
	SandboxID             string
	SourceResourceID      string
	DestinationResourceID sql.NullString
	PackagePath           string
	Version               string
	RequestedAt           time.Time
	PreviousVersion       sql.NullString
	QuiescedAt            sql.NullTime
	CheckpointKey         sql.NullString
	CheckpointReference   sql.NullString
	CheckpointSourceID    sql.NullString
	ActivatedAt           sql.NullTime
	RollbackAt            sql.NullTime
	FailureCode           sql.NullString
	RestoredAt            sql.NullTime
	VerifiedAt            sql.NullTime
	CheckpointDeletedAt   sql.NullTime
	FinishedAt            sql.NullTime
	JobID                 string
	SourceProviderID      string
	DestinationProviderID string
}

func (q *Queries) GetSandboxUpgrade(ctx context.Context, id string) (GetSandboxUpgradeRow, error) {
	row := q.db.QueryRowContext(ctx, getSandboxUpgrade, id)
	var i GetSandboxUpgradeRow
	err := row.Scan(
		&i.ID,
		&i.SandboxID,
		&i.SourceResourceID,
		&i.DestinationResourceID,
		&i.PackagePath,
		&i.Version,
		&i.RequestedAt,
		&i.PreviousVersion,
		&i.QuiescedAt,
		&i.CheckpointKey,
		&i.CheckpointReference,
		&i.CheckpointSourceID,
		&i.ActivatedAt,
		&i.RollbackAt,
		&i.FailureCode,
		&i.RestoredAt,
		&i.VerifiedAt,
		&i.CheckpointDeletedAt,
		&i.FinishedAt,
		&i.JobID,
		&i.SourceProviderID,
		&i.DestinationProviderID,
	)
	return i, err
}

const insertSandboxUpgrade = `-- name: InsertSandboxUpgrade :exec
insert into dorf.sandbox_upgrades(id,sandbox_id,source_resource_id,package_path,version)
values($1,$2,$3,$4,$5)
`

type InsertSandboxUpgradeParams struct {
	ID               string
	SandboxID        string
	SourceResourceID string
	PackagePath      string
	Version          string
}

func (q *Queries) InsertSandboxUpgrade(ctx context.Context, arg InsertSandboxUpgradeParams) error {
	_, err := q.db.ExecContext(ctx, insertSandboxUpgrade,
		arg.ID,
		arg.SandboxID,
		arg.SourceResourceID,
		arg.PackagePath,
		arg.Version,
	)
	return err
}

const listJobUpgrades = `-- name: ListJobUpgrades :many
select u.id, u.sandbox_id, u.source_resource_id, u.destination_resource_id, u.package_path, u.version, u.requested_at, u.previous_version, u.quiesced_at, u.checkpoint_key, u.checkpoint_reference, u.checkpoint_source_id, u.activated_at, u.rollback_at, u.failure_code, u.restored_at, u.verified_at, u.checkpoint_deleted_at, u.finished_at,s.job_id,coalesce(src.provider_id,'') as source_provider_id,coalesce(dst.provider_id,'') as destination_provider_id from dorf.sandbox_upgrades u join dorf.sandboxes s on s.id=u.sandbox_id join dorf.sandbox_resources src on src.id=u.source_resource_id left join dorf.sandbox_resources dst on dst.id=u.destination_resource_id
where s.job_id=$1 order by u.requested_at,u.id
`

type ListJobUpgradesRow struct {
	ID                    string
	SandboxID             string
	SourceResourceID      string
	DestinationResourceID sql.NullString
	PackagePath           string
	Version               string
	RequestedAt           time.Time
	PreviousVersion       sql.NullString
	QuiescedAt            sql.NullTime
	CheckpointKey         sql.NullString
	CheckpointReference   sql.NullString
	CheckpointSourceID    sql.NullString
	ActivatedAt           sql.NullTime
	RollbackAt            sql.NullTime
	FailureCode           sql.NullString
	RestoredAt            sql.NullTime
	VerifiedAt            sql.NullTime
	CheckpointDeletedAt   sql.NullTime
	FinishedAt            sql.NullTime
	JobID                 string
	SourceProviderID      string
	DestinationProviderID string
}

func (q *Queries) ListJobUpgrades(ctx context.Context, jobID string) ([]ListJobUpgradesRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobUpgrades, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobUpgradesRow
	for rows.Next() {
		var i ListJobUpgradesRow
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.SourceResourceID,
			&i.DestinationResourceID,
			&i.PackagePath,
			&i.Version,
			&i.RequestedAt,
			&i.PreviousVersion,
			&i.QuiescedAt,
			&i.CheckpointKey,
			&i.CheckpointReference,
			&i.CheckpointSourceID,
			&i.ActivatedAt,
			&i.RollbackAt,
			&i.FailureCode,
			&i.RestoredAt,
			&i.VerifiedAt,
			&i.CheckpointDeletedAt,
			&i.FinishedAt,
			&i.JobID,
			&i.SourceProviderID,
			&i.DestinationProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordUpgradeActivated = `-- name: RecordUpgradeActivated :execrows
update dorf.sandbox_upgrades set activated_at=coalesce(activated_at,clock_timestamp())
where id=$1 and checkpoint_reference is not null and rollback_at is null
`

func (q *Queries) RecordUpgradeActivated(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordUpgradeActivated, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordUpgradeCheckpoint = `-- name: RecordUpgradeCheckpoint :execrows
update dorf.sandbox_upgrades set checkpoint_key=$1::text,
checkpoint_reference=$2::text,checkpoint_source_id=$3::text
where id=$4 and quiesced_at is not null and
(checkpoint_reference is null or (checkpoint_key=$1::text
and checkpoint_reference=$2::text and checkpoint_source_id=$3::text))
`

type RecordUpgradeCheckpointParams struct {
	CheckpointKey       string
	CheckpointReference string
	CheckpointSourceID  string
	ID                  string
}

func (q *Queries) RecordUpgradeCheckpoint(ctx context.Context, arg RecordUpgradeCheckpointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordUpgradeCheckpoint,
		arg.CheckpointKey,
		arg.CheckpointReference,
		arg.CheckpointSourceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordUpgradeCheckpointDeleted = `-- name: RecordUpgradeCheckpointDeleted :execrows
update dorf.sandbox_upgrades set checkpoint_deleted_at=coalesce(checkpoint_deleted_at,clock_timestamp())
where id=$1 and checkpoint_reference is not null
`

func (q *Queries) RecordUpgradeCheckpointDeleted(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordUpgradeCheckpointDeleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordUpgradeFinished = `-- name: RecordUpgradeFinished :execrows
update dorf.sandbox_upgrades set finished_at=coalesce(finished_at,clock_timestamp())
where id=$1 and verified_at is not null
`

func (q *Queries) RecordUpgradeFinished(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordUpgradeFinished, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordUpgradePreparation = `-- name: RecordUpgradePreparation :execrows
update dorf.sandbox_upgrades set previous_version=$1::text
where id=$2 and (previous_version is null or previous_version=$1::text)
`

type RecordUpgradePreparationParams struct {
	PreviousVersion string
	ID              string
}

func (q *Queries) RecordUpgradePreparation(ctx context.Context, arg RecordUpgradePreparationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordUpgradePreparation, arg.PreviousVersion, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordUpgradeQuiesced = `-- name: RecordUpgradeQuiesced :execrows
update dorf.sandbox_upgrades set quiesced_at=coalesce(quiesced_at,clock_timestamp())
where id=$1 and previous_version is not null
`

func (q *Queries) RecordUpgradeQuiesced(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordUpgradeQuiesced, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordUpgradeRestored = `-- name: RecordUpgradeRestored :execrows
update dorf.sandbox_upgrades set restored_at=coalesce(restored_at,clock_timestamp())
where id=$1 and destination_resource_id is not null and rollback_at is not null
`

func (q *Queries) RecordUpgradeRestored(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordUpgradeRestored, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordUpgradeVerified = `-- name: RecordUpgradeVerified :execrows
update dorf.sandbox_upgrades set verified_at=coalesce(verified_at,clock_timestamp())
where id=$1 and (activated_at is not null or restored_at is not null)
and (rollback_at is null or restored_at is not null)
`

func (q *Queries) RecordUpgradeVerified(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordUpgradeVerified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestUpgradeRollback = `-- name: RequestUpgradeRollback :execrows
update dorf.sandbox_upgrades set rollback_at=coalesce(rollback_at,clock_timestamp()),failure_code=coalesce(failure_code,$1::text)
where id=$2 and checkpoint_reference is not null and verified_at is null
`

type RequestUpgradeRollbackParams struct {
	FailureCode string
	ID          string
}

func (q *Queries) RequestUpgradeRollback(ctx context.Context, arg RequestUpgradeRollbackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestUpgradeRollback, arg.FailureCode, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reserveUpgradeResource = `-- name: ReserveUpgradeResource :exec
insert into dorf.sandbox_resources(id,sandbox_id,ownership_nonce)
values($1,$2,$3)
`

type ReserveUpgradeResourceParams struct {
	ID             string
	SandboxID      string
	OwnershipNonce string
}

func (q *Queries) ReserveUpgradeResource(ctx context.Context, arg ReserveUpgradeResourceParams) error {
	_, err := q.db.ExecContext(ctx, reserveUpgradeResource, arg.ID, arg.SandboxID, arg.OwnershipNonce)
	return err
}

const switchUpgradeResource = `-- name: SwitchUpgradeResource :execrows
update dorf.sandboxes set active_resource_id=$1
where id=$2 and active_resource_id=$3
`

type SwitchUpgradeResourceParams struct {
	DestinationResourceID string
	SandboxID             string
	SourceResourceID      string
}

func (q *Queries) SwitchUpgradeResource(ctx context.Context, arg SwitchUpgradeResourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, switchUpgradeResource, arg.DestinationResourceID, arg.SandboxID, arg.SourceResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upgradeQuiescent = `-- name: UpgradeQuiescent :one
select coalesce(not exists(select 1 from dorf.agent_runs ar join dorf.job_messages m on m.id=ar.message_id
where ar.sandbox_id=$1 and ar.state not in ('completed','failed','interrupted')
and (ar.state <> 'pending' or ar.baseline_turn_id is not null or m.delivery_intent='steer')),false)::boolean as quiet
`

func (q *Queries) UpgradeQuiescent(ctx context.Context, sandboxID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, upgradeQuiescent, sandboxID)
	var quiet bool
	err := row.Scan(&quiet)
	return quiet, err
}
