// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wakes.sql

package dbsql

import (
	"context"

	"github.com/aphronio/dorf/internal/core"
)

const ensureSessionExecutionWake = `-- name: EnsureSessionExecutionWake :exec
insert into dorf.session_execution_wakes(session_id)
values($1)
on conflict(session_id) do nothing
`

func (q *Queries) EnsureSessionExecutionWake(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, ensureSessionExecutionWake, sessionID)
	return err
}

const getNativeTerminalWakeBinding = `-- name: GetNativeTerminalWakeBinding :one
select j.id as session_id,s.id as sandbox_id,coalesce(j.thread_id,'') as thread_id,
       j.admission_open,j.cleanup_state
from dorf.sessions j join dorf.sandboxes s on s.session_id=j.id
where j.id=$1 and s.id=$2
`

type GetNativeTerminalWakeBindingParams struct {
	SessionID string
	SandboxID string
}

type GetNativeTerminalWakeBindingRow struct {
	SessionID     string
	SandboxID     string
	ThreadID      string
	AdmissionOpen bool
	CleanupState  core.CleanupState
}

func (q *Queries) GetNativeTerminalWakeBinding(ctx context.Context, arg GetNativeTerminalWakeBindingParams) (GetNativeTerminalWakeBindingRow, error) {
	row := q.db.QueryRowContext(ctx, getNativeTerminalWakeBinding, arg.SessionID, arg.SandboxID)
	var i GetNativeTerminalWakeBindingRow
	err := row.Scan(
		&i.SessionID,
		&i.SandboxID,
		&i.ThreadID,
		&i.AdmissionOpen,
		&i.CleanupState,
	)
	return i, err
}

const getSessionExecutionWakeCause = `-- name: GetSessionExecutionWakeCause :one
select revision
from dorf.session_execution_wake_causes
where session_id=$1 and cause_key=$2
`

type GetSessionExecutionWakeCauseParams struct {
	SessionID string
	CauseKey  string
}

func (q *Queries) GetSessionExecutionWakeCause(ctx context.Context, arg GetSessionExecutionWakeCauseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSessionExecutionWakeCause, arg.SessionID, arg.CauseKey)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const getSessionExecutionWakeRevision = `-- name: GetSessionExecutionWakeRevision :one
select coalesce(w.revision,0)::bigint as revision
from dorf.sessions j
left join dorf.session_execution_wakes w on w.session_id=j.id
where j.id=$1
`

func (q *Queries) GetSessionExecutionWakeRevision(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSessionExecutionWakeRevision, sessionID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const insertSessionExecutionWakeCause = `-- name: InsertSessionExecutionWakeCause :exec
insert into dorf.session_execution_wake_causes(session_id,cause_key,revision)
values($1,$2,$3)
`

type InsertSessionExecutionWakeCauseParams struct {
	SessionID string
	CauseKey  string
	Revision  int64
}

func (q *Queries) InsertSessionExecutionWakeCause(ctx context.Context, arg InsertSessionExecutionWakeCauseParams) error {
	_, err := q.db.ExecContext(ctx, insertSessionExecutionWakeCause, arg.SessionID, arg.CauseKey, arg.Revision)
	return err
}

const lockSessionExecutionWake = `-- name: LockSessionExecutionWake :one
select revision
from dorf.session_execution_wakes
where session_id=$1
for update
`

func (q *Queries) LockSessionExecutionWake(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockSessionExecutionWake, sessionID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const setSessionExecutionWakeRevision = `-- name: SetSessionExecutionWakeRevision :execrows
update dorf.session_execution_wakes
set revision=$1
where session_id=$2
`

type SetSessionExecutionWakeRevisionParams struct {
	Revision  int64
	SessionID string
}

func (q *Queries) SetSessionExecutionWakeRevision(ctx context.Context, arg SetSessionExecutionWakeRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSessionExecutionWakeRevision, arg.Revision, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
